### ISSUE TITLE
surveyor - respondent mode

### ISSUE THREAD

**Issue by 363568233** [nanomsg/nanomsg#1001]
the surveyor  send frequency  seems to be  once per second ?  
Can't this mode send high frequency as a lot of data ?
I want to use pubsub with respond(default not respond),  what should I do?

**Comment by gdamore** [comment]
surveyor can send a lot of data. you can tune down the interval but of course if your responders take longer to reply then you will lose those replies.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by 363568233** [comment]
Oh, I find setting socket option NN_SURVEYOR_DEADLINE can decrease the wait time, but I think that the surveyor mode is not suitable for my situation,   I want to high-efficiency pub sub with respond, but testing req and rep mode is not high-efficiency,  could you give me some advices? Please.

**Comment by gdamore** [comment]
It may be that you need to use multiple sockets.  If your publishers are
going to be distinct from subscribers then maybe you can build what you
need using BUS.

  - Garrett

**Comment by 363568233** [comment]
The Bus mode is only to local level (within a single machine or within a single LAN).
Now, I'm going to use the req-rep multiple sockets. 
There is another question,  nanomsg can't get remote endpoint's IP?  the same as zmq?
It's only get remote ip within data.

**Comment by gdamore** [comment]
On Oct 26, 2018, 7:32 AM -0400, Eric <notifications@github.com>, wrote:
> The Bus mode is only to local level (within a single machine or within a single LAN).
> Now, I'm going to use the req-rep multiple sockets.
> There is another question, nanomsg can't get remote endpoint's IP? the same as zmq?
> It's only get remote ip within data.


That’s true for nanomsg.  However, NNG will let you obtain the address of the immediate peer, and works with nanomsg seamlessly.  You might want to have a look at it.  (GitHub.com/nanomsg/nng)

Note that you still can’t obtain the address of a peer that is on the other side of a proxy/device.

 - Garrett

**Comment by gdamore** [comment]
I think this is just support questions, and hopefully we've resolved them.  If you have further questions, please use the mailing or our gitter chat.  You can also post back here and I will try to follow up.
