### ISSUE TITLE
How to improve tcp req-rep performance?

### ISSUE THREAD

**Issue by 363568233** [nanomsg/nanomsg#1002]
Single thread  block mode,  client 1KB data to send and serveral bytes to recv ,  test about 2500 tps on my laptop.
I can not increase lots of threads, because I must send to multiple different servers(the num is unknow),  
I want to find a good way,  multiple threads、nn_poll?

**Comment by gdamore** [comment]
For nanomsg, you need to use nn_poll.

However, I recommend you consider using NNG, which offers nicer APIs for this.  You can use multiple threads, each thread having an NNG context (all contexts share the same socket), or you can use asynchronous I/O with some kind of callback scheme.

NNG is compatible with nanomsg, and its really the "next generation" of nanomsg.  See github.com/nanomsg/nng for details.

**Comment by gdamore** [comment]
This is a question, and I think I've answered it.  Feel free to post follow ups here, but for now I'm closing it.
