### ISSUE TITLE
Please have separate options for manpages and docs

### ISSUE THREAD

**Issue by yurivict** [nanomsg/nanomsg#1012]
It's a common practice to always install manpages because they are usually small. But docs could be large, and some users prefer to choose DOCS=off.

In any case, it would be better if the project could accommodate such user preferences, and have 2 separate cmake options for them.

Thank you.

**Comment by gdamore** [comment]
Our docs *are* the man pages.  I'll consider this for NNG (which has much much larger documentation), but for nanomsg I'm unlikely to bother at this late stage in libnanomsg's lifecycle.

**Comment by gdamore** [comment]
Closing this, as I won't be doing it at all for libnanomsg.
