### ISSUE TITLE
MSVC2015  build with static nanomsg-1.1.5 link error : LNK2001 unresolved external 

### ISSUE THREAD

**Issue by 363568233** [nanomsg/nanomsg#1014]
![image](https://user-images.githubusercontent.com/6778018/50469675-71557780-09e8-11e9-89c3-0f63b2e3ec6a.png)

**Comment by 363568233** [comment]
I add NN_STATIC_LIB in preprocessor flags in my project, but  error LNK1120:  unresolved external 
 _AcceptEx@32

**Comment by 363568233** [comment]
AcceptEx is in Mswsock.lib, so I add   #pragma comment(lib,"Mswsock.lib") in my code,  It's ok.  Am I right to do this?

**Comment by gdamore** [comment]
You should not have to do that, but you probably do because the static library configuration rules in cmake may not be expressing this dependency properly.  (Meaning that this is probably a bug in my cmake files.)  For now, if that works for you then stick with it.

**Comment by gdamore** [comment]
I'm closing this ... whatever happened was probably some issue with your build environment.
