### ISSUE TITLE
linux link static nanomsg in .so

### ISSUE THREAD

**Issue by 363568233** [nanomsg/nanomsg#1015]
/usr/bin/ld: /usr/local/lib64/libnanomsg.a(global.c.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib64/libnanomsg.a: could not read symbols: Bad value

**Comment by gdamore** [comment]
So this is an usual build case -- you're wanting to stick a static library into a dynamic library -- generally you either are going to build this into an executable (no PIC needed) or you build a shared object.

The thing is -fPIC is not free, and so you don't want it on by default when building a shared library. The fact that for your toolchain you do is unusual, and you're going to have to take special steps here.

My question for you is, why do you want to do this?

**Comment by gdamore** [comment]
I recommend going either all static, or all dynamic.  Mixing and matching can work, but you're probably on your own when it comes to configuring the compiler flags.  CMake will let you specify alternate flags (-fPIC in this case); see the CMake docs for more detail.

I'm unlikely to make changes to libnanomsg for this unconventional use case at this late stage in nanomsg's life cycle -- there is an easy workaround available for you by configuring CMake flags explicitly.
