### ISSUE TITLE
Please help, when I use bus samples and other protocols (such as ipc or tcp), the test fails.

### ISSUE THREAD

**Issue by jzaicn** [nanomsg/nanomsg#1016]

**Comment by gdamore** [comment]
This description is far too inadequate for me to help you.  I need more specific details: does the self test fail?  What platform did you use?  What was the expected behavior?  What was the observed behavior (precisely)?

**Comment by jzaicn** [comment]
Thanks for your reply, it may have been my fault. Sorry for bothering.

It seems that using bus socket in the ipc socket will lose some messages.
