### ISSUE TITLE
Unable to build for emscripten environment.

### ISSUE THREAD

**Issue by kavikumarN** [nanomsg/nanomsg#1017]
I have tried to build nanomsg for emscripten framework. I have failed to succeed the installation using instruction in github along with emmake cmd. Now i would like to know whether is there any way to build?

CMake Warning (dev) at CMakeLists.txt:172 (message):
  Please consider opening an issue at https://github.com/nanomsg/nanomsg
This warning is for project developers.  Use -Wno-dev to suppress it.

**Comment by gdamore** [comment]
You may be able to ignore the above message.  I would need more details.  Having said that, all new development has shifted to NNG.  ( GitHub.com/nanomsg/nng )

**Comment by kavikumarN** [comment]
Hi thanks for the reply. I have tried NNG too. But the emscripten doesnt support Cmake Ninja. with Nanomsg i have used typical build system ie., "emcmake cmake nanomsg"  to build. No tests were run successfully.

**Comment by gdamore** [comment]
You can use CMake with normal make.

**Comment by gdamore** [comment]
At any rate, I would need a bit more detail in order to help you debug this.  I suspect that emscripten may not work with some aspects of libnanomsg (and even NNG), as the browser environment is fairly restricted when it comes to network access.

**Comment by kavikumarN** [comment]
yes, i have tried with nng,nanomsg and zeromq to build with emscripten environment. It fails to run as a c /c++ binding. Now i am trying to run zeromq externally from node binding, although it works but i would like to execute it from c/c++ environment.

**Comment by gdamore** [comment]
There are node bindings already available for nanomsg and NNG.  You should use those if you're just trying to use a node JS thing.

If you're in the browser, its a bit more complicated.

**Comment by gdamore** [comment]
Aging this one off.  Feel free to reach out to me on the chat (discord) if you have further questions.
