### ISSUE TITLE
Errors when making the static library

### ISSUE THREAD

**Issue by Fidelin50** [nanomsg/nanomsg#1018]
Hello, when I try to compile with the static library I get these errors
gcc nanomsg_pair.c  /usr/local/lib/libnanomsg.a /usr/local/lib/libnanomsg.a (mutex.c.o): In function `nn_mutex_init':
mutex.c:(.text+0x23): undefined reference to `pthread_mutexattr_init'
mutex.c:(.text+0x34): undefined reference to `pthread_mutexattr_settype'
mutex.c:(.text+0x121): undefined reference to `pthread_mutexattr_destroy'
/usr/local/lib/libnanomsg.a(once.c.o): In function `nn_do_once':
once.c:(.text+0x1f): undefined reference to `pthread_once'
/usr/local/lib/libnanomsg.a(sem.c.o): In function `nn_sem_init':
sem.c:(.text+0x1f): undefined reference to `sem_init'
/usr/local/lib/libnanomsg.a(sem.c.o): In function `nn_sem_term':
sem.c:(.text+0xad): undefined reference to `sem_destroy'
/usr/local/lib/libnanomsg.a(sem.c.o): In function `nn_sem_post':
sem.c:(.text+0x13b): undefined reference to `sem_post'
/usr/local/lib/libnanomsg.a(sem.c.o): In function `nn_sem_wait':
sem.c:(.text+0x1c9): undefined reference to `sem_wait'
/usr/local/lib/libnanomsg.a(thread.c.o): In function `nn_thread_init':
thread.c:(.text+0xf8): undefined reference to `pthread_sigmask'
thread.c:(.text+0x1b5): undefined reference to `pthread_create'
thread.c:(.text+0x242): undefined reference to `pthread_sigmask'
/usr/local/lib/libnanomsg.a(thread.c.o): In function `nn_thread_term':
thread.c:(.text+0x2f6): undefined reference to `pthread_join'
/usr/local/lib/libnanomsg.a(dns.c.o): In function `nn_dns_start':
dns.c:(.text+0x528): undefined reference to `getaddrinfo_a'
/usr/local/lib/libnanomsg.a(dns.c.o): In function `nn_dns_notify':
dns.c:(.text+0x60e): undefined reference to `gai_error'
/usr/local/lib/libnanomsg.a(dns.c.o): In function `nn_dns_shutdown':
dns.c:(.text+0x7cc): undefined reference to `gai_cancel'
collect2: error: ld returned 1 exit status

And I created the library by following these steps
#!/bin/bash

#Download nanomsg library 1.0 stable
wget https://github.com/nanomsg/nanomsg/archive/1.0.0.zip

#Extract from archive and delete archive
unzip 1.0.0.zip && rm 1.0.0.zip

#Rename source file
mv nanomsg-1.0.0 nanomsgsrc

#Create destination folder
mkdir nanomsglib

#Switch into nanomsgsrc folder
cd nanomsgsrc

#Create build directory and switch into it
mkdir build && cd build

#Compile
cmake .. -DCMAKE_INSTALL_PREFIX=../../nanomsglib/ -DCMAKE_BUILD_TYPE=Debug -DNN_STATIC_LIB=1
cmake --build .
ctest -C Debug .
cmake --build . --target install

**Comment by gdamore** [comment]
So while you made a static version of libnanomsg, you still have to link in the libraries upon which libnanomsg depends.  On your platform that appears to be libpthread, and probably libresolv.  You would add those to your link line: -lpthread -lresolv right after the -lnanomsg.

**Comment by gdamore** [comment]
Nothing I can do here -- this is the consequence of static libraries -- all dependencies must be listed when using them because static libraries have no way to record their dependencies like dynamic libraries can.

**Comment by Fidelin50** [comment]
Thank you!
