### ISSUE TITLE
Error when compile in Eclipse 

### ISSUE THREAD

**Issue by Fidelin50** [nanomsg/nanomsg#1019]
Hello, when i compiled for a stm32l073rz... I have this error:

arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -L/usr/local/lib -specs=nosys.specs -specs=nano.specs -T"../STM32L073RZTx_FLASH.ld" -Wl,-Map=output.map -Wl,--gc-sections -o "Final_Libreria.elf" @"objects.list"  -lnanomsg -lm
/usr/local/lib/libnanomsg.a: error adding symbols: File format not recognized
collect2: error: ld returned 1 exit status

¿Any solution?

**Comment by gdamore** [comment]
This looks to me like a problem with your toolchain.  Are you sure you can build libraries using it?  Was the /usr/local/lib/libnanomsg.a produced using the same toolchain?

At first glance it looks like you may be attempting to use a cross compiler.

**Comment by Fidelin50** [comment]
Yes, you are rigth but when i compile  library with the toolchain (TrueStudio), it gives more errors.

The doubt I have is the following.
What code do I have to take to compile the library? The src of github?

**Comment by gdamore** [comment]
You can build from a tarball (see the releases page) or git clone.  I usually recommend using git clone these days.
