### ISSUE TITLE
Entry point not found for CancelIoEx on XP

### ISSUE THREAD

**Issue by brunoqc** [nanomsg/nanomsg#102]
I'm unable to test nanomsg on XP since CancelIoEx was introduced in Vista.

![image](https://f.cloud.github.com/assets/24027/1011564/f6867f82-0b5e-11e3-83aa-82a7a718994e.png)

> Minimum supported client: Windows Vista [desktop apps only]
Minimum supported server: Windows Server 2008 [desktop apps only]

http://msdn.microsoft.com/en-us/library/windows/desktop/aa363792(v=vs.85).aspx

CancelIoEx is used in  [src/aio/usock_win.inc](https://github.com/250bpm/nanomsg/blob/master/src/aio/usock_win.inc#L742).

**Comment by gdamore** [comment]
So I don't have Windows XP available to me, and the XP platform itself is no longer supported by Microsoft outside of unusual extended supported arrangements for the embedded edition.

If nobody steps forward with a suitable fix that does not negatively impact existing Windows support, then its unlikely we will ever fix this.  Frankly, I'm not sure this is a problem that warrants attention.

**Comment by gdamore** [comment]
Closing as a dup of #334  -- which is the real issue.

**Comment by httpstorm** [comment]
Hey @gdamore 
Not sure if this is still relevant, but after some reverse-engineering, I implemented the following solution for one of my projects. In my case the code is selected at build time: Windows 2003 has Visual Studio 2010, where `WINVER` matches `_WIN32_WINNT_WIN7`, so it will fall-back to simulating `CancelIoEx`:
1. Mark the overlapped IO with `STATUS_CANCELLED`
2. Signal the event to wake the waiting thread
3. Which in turn can call `CancelIo`
4. Note that `CancelIo` affects only the thread which started the async operation

```
#ifndef STATUS_CANCELLED
#define STATUS_CANCELLED ((NTSTATUS)0xC0000120L)
#endif

BOOL async_cancel_r()
{
#if (WINVER > _WIN32_WINNT_WIN7)
	return CancelIoEx(h_file, p_async_r);
#else
	// XP and 2003 do not support CancelIoEx
	p_async_r->Internal = STATUS_CANCELLED;
	return SetEvent(p_async_r->hEvent);
#endif
}

size_t async_wait_r()
{
	DWORD size = 0;
	DWORD error_code = 0;

	if (!GetOverlappedResult(h_file, p_async_r, &size, true))
	{
		error_code = GetLastError();

#if !(WINVER > _WIN32_WINNT_WIN7)
		// XP and 2003 do not support CancelIoEx
		if (error_code == ERROR_OPERATION_ABORTED)
		{
			CancelIo(h_file);
		}
#endif

		return -1;
	}

	return size;
}
```

**Comment by gdamore** [comment]
That was 8 years ago. XP is ancient now and I have zero interest in even trying to support it. I don't have a copy of the OS nor do I even know where I would get one to test with.

Even Windows 7 is rather old at this point.
