### ISSUE TITLE
some of perf test hangs

### ISSUE THREAD

**Issue by shek2994** [nanomsg/nanomsg#1020]
performance test not working for some module.
inproc_lat works fine. e.g 
nanomsg/nanomsg/build$ ./inproc_lat 10 10
inproc://inproc_lat
inproc://inproc_lat
message size: 10 [B]
roundtrip count: 10
average latency: 7.600 [us]

But does not work for local_lat and remote_lat
my cmd: $ ./local_lat ipc://a 10 10 --> hangs

**Comment by gdamore** [comment]
local_lat blocks until remote_lat is run and it connects.  The local side is the server.

**Comment by gdamore** [comment]
There is no bug here, just a confusion about how to use the performance test programs.  Closing.
