### ISSUE TITLE
nn_allocmsg/nn_freemsg and pub/sub

### ISSUE THREAD

**Issue by d01010101** [nanomsg/nanomsg#1021]
Hi. I do not know how the pair nn_allocmsg/nn_freemsg is related to the pubsub mechanism. In the docs, I see nn_allocmsg called at the publisher side, and nn_freemsg called on the subscribed side.

But what if a published message is never received? What if it is received multiple times? Does nanomsg provide some automated mechanism for that? If not, how to handle this? How do I know, that a published message can be deallocated? By the way, in the source, you can find a comment that nanomsg never really does zero-copy.

**Comment by gdamore** [comment]
When you do nn_send() with NN_MSG, the library takes care of disposing of the memory (doing the freemsg).  This is done regardless of whether it is received or not.

Likewise, on the receiver, when receiving a message with NN_MSG, you have to dispose of the received message each time.  Each receiver will have its own message.
