### ISSUE TITLE
Tests with nn_sleep() after connect

### ISSUE THREAD

**Issue by nanosonde** [nanomsg/nanomsg#1031]
How could those tests be improved that one can be sure that any following operating like nn_send() etc. will work out and not loose any data?

Example: https://github.com/nanomsg/nanomsg/blob/master/tests/ipc_stress.c#L92

**Comment by gdamore** [comment]
The nature of nanomsg is that the connection establishment is asynchronous.  Thus, there isn't a good way to achieve what you're asking.

Note that with NNG there are some options, but generally still one should assume that connection is asynchronous.

The reason that this is true is to allow the library to be fully asynchronous and self-healing.  (For example, if a connection is dropped for any reason, the library will reconnect under the hood.)
