### ISSUE TITLE
about nn_term

### ISSUE THREAD

**Issue by Slzde** [nanomsg/nanomsg#1032]
A simple question: how do I reset nn_socket to useful after i call nn_term

From document:
Attempting to open a new socket with nn_socket(3) will result in an ETERM error.

Example:
Using nn_device forward, I need to use nn_term to close it, then ? How to use nn_socket again .
I will make my own forwarding wheel if it is not allowed.
Please give me an accurate answer or a available solution !  Thanks!

**Comment by gdamore** [comment]
If you're just wanting to close the device, use nn_close() on one of the sockets used with the device.

nn_term() should only be used when shutting down the entire library.  I actually discourage using nn_term() unless you need to do this e.g. via atexit() to facilitate memory leak analysis.

**Comment by Slzde** [comment]
Thanks! I got it!
