### ISSUE TITLE
Not able to use with cmake FetchContent

### ISSUE THREAD

**Issue by renjipanicker** [nanomsg/nanomsg#1034]
nanomsg does not build when used as a cmake subproject with FetchContent.
The following error is observed:

`CMake Error: File /Users/<project-path>/bld/_deps/nanomsg-src/src/cmake/nanomsg-config.cmake.in does not exist.
Call Stack (most recent call first):
  bld/_deps/nanomsg-src/src/CMakeLists.txt:395 (configure_package_config_file)
`

This can be rectified using the following change at line number 395:

```
configure_package_config_file(
-    ${CMAKE_SOURCE_DIR}/cmake/${PROJECT_NAME}-config.cmake.in
+    ${CMAKE_CURRENT_SOURCE_DIR}/../cmake/${PROJECT_NAME}-config.cmake.in
     ${CMAKE_CURRENT_BINARY_DIR}/${PROJECT_NAME}-config.cmake
     INSTALL_DESTINATION ${PACKAGE_INSTALL_DESTINATION}
     PATH_VARS CMAKE_INSTALL_PREFIX

```

**Comment by gdamore** [comment]
Another change was made to use PROJECT_SOURCE_DIR.
Can you please let me know if this is still an issue?

**Comment by gdamore** [comment]
Closing due to no feedback.
