### ISSUE TITLE
pub and sub

### ISSUE THREAD

**Issue by breakisx** [nanomsg/nanomsg#1035]
When I use the pub/usb mechanism， I just send the max size of data that is 1MB, if more than 1MB, nn_send() method is like success, because it return the size of data,  but nn_recv() method can't receive message. could you help me to solve this problem ? thank you!

**Comment by gdamore** [comment]
You need to set the NN_RECVMAXSZ option.  The 1MB limit is there to guard against DoS attacks from untrustworthy peers.

**Comment by breakisx** [comment]
@gdamore 
Thank you ! I have successed to send and receive the data exceeds 1MB.

**Comment by breakisx** [comment]
@gdamore 
I have another question, when I test the pub/usb mechanism,  I observed that previous frame messages will be lost, The quantity is not fixed， do you know the reason ?

**Comment by breakisx** [comment]
first, I start client program, then I tart the server program

**Comment by gdamore** [comment]
Any messages "sent" before the connection is established will be dropped.  PUB/SUB is best effort delivery only.
