### ISSUE TITLE
Version nanomsg-1.1.2 Send a lot of data and receiver will lost all of data.

### ISSUE THREAD

**Issue by BIGCATDOG** [nanomsg/nanomsg#1039]
This is debug log :
`message :  {"p":"nanomsg","v":"1.1.2","id":3,"s":"Sender","r":"Receiver","t":1578389299603,"c":"Recent Flipcharts","args":["{"path":"C:/Users/Administrator/Desktop/flipchartTest/無標題9.flipchart","date":"1578386639108"}","{"path":"C:/Users/Administrator/Desktop/flipchartTest/無標題789.flipchart","date":"1578382877213"}","{"path":"C:/Users/Administrator/Desktop/flipchartTest/無標題568.flipchart","date":"1578382861398"}","{"path":"C:/Users/Administrator/Desktop/flipchartTest/無標題22.flipchart","date":"1578382735798"}","{"path":"C:/Users/Administrator/Desktop/flipchartTest/test2.flipchart","date":"1578382525545"}","{"path":"C:/Users/Administrator/Desktop/flipchartTest/CreatFlipChartOrInsertObject.flipchart","date":"1578380372610"}","{"path":"C:/Users/Administrator/Desktop/flipchartTest/无标题2.flipchart","date":"1571236837294"}","{"path":"C:/Users/Administrator/Desktop/flipchartTest/TEST文件格式/2.16版本.flipchart","date":"1573180783180"}"]} , length :  965`

After i send  about 965 bytes to receiver , the receiver can not receiver the data .But if i decrease the transmit package length  ,it can be transmited successfully.

**Comment by gdamore** [comment]
I need more detail.  What protocol are you using?  (PUB/SUB, PAIR, etc.?)  What rate are you sending?  What transport?

**Comment by BIGCATDOG** [comment]
Thank you for your reply. After a lot of debugging , i found that this issue can not be reproduce . And  there are some issues  in my code , it is not relate to nanomsg library.
So i will close this issue. Thank you !
