### ISSUE TITLE
Assertion failed: !nn_fsm_event_active (&sinproc->event_sent)

### ISSUE THREAD

**Issue by coversb** [nanomsg/nanomsg#1040]
Hi, thank you for your wonderful nanomsg first! 
I have met this abort error "Assertion failed: !nn_fsm_event_active (&sinproc->event_sent)" in 1.0.0, and I think may be when I call nn_shutdown or nn_close, this error will raise sometimes, do you have any suggestion?

Thank you!

**Comment by coversb** [comment]
nn_close will cause this ASSERT

**Comment by coversb** [comment]
Hi, I have found if I use "inproc",  nn_close sometimes will abort while "ipc" has never met that situation.

test code is like

while (1)
{
        int fd = nn_socket (AF_SP, NN_SUB);
        nn_setsockopt (fd, NN_SUB, NN_SUB_SUBSCRIBE, "", 0);
        nn_connect(fd, "inproc://tmp/nnmq/test");
        usleep(50*1000);
        nn_close(fd);
}

**Comment by gdamore** [comment]
Please try updating to a newer version - release 1.1.5 is out, and there have been a lot of bug fixes.

I'm also not doing much more work on this older version of nanomsg -- there is nng (see github.com/nanomsg/nng) which gets a lot more of my attention these days.

**Comment by coversb** [comment]
> Please try updating to a newer version - release 1.1.5 is out, and there have been a lot of bug fixes.
> 
> I'm also not doing much more work on this older version of nanomsg -- there is nng (see github.com/nanomsg/nng) which gets a lot more of my attention these days.

Thanks for your replay, I have already use the 1.1.5 in our project! Now it works fine in "ipc" mode.
