### ISSUE TITLE
is this a dead project ? 

### ISSUE THREAD

**Issue by MyraBaba** [nanomsg/nanomsg#1046]
I saw its not actively developing last 1,5 year?

**Comment by gdamore** [comment]
libnanomsg is in sustaining mode.  The focus is definitely on NNG (github.com/nanomsg/nng) which is a substantial improvement over nanomsg.  libnanomsg itself is in sustaining mode.

**Comment by MyraBaba** [comment]
should we choose NNG over zeromq ?

**Comment by SG7** [comment]
Definitely yes! I took a look into zeromq features and its code as well.
NNG is superior! Just make a small project and compare.
It is much easier to do same things with NNG.

**Comment by arthuriantech** [comment]
@SG7  Really? Does NNG have something like ZMQ RADIO/DISH sockets? Or some UDP-based protocol with multicasting support?

**Comment by gdamore** [comment]
I'm closing this -- it's not dead.  But in sustaining mode.
