### ISSUE TITLE
chunk.c line 68 130  

### ISSUE THREAD

**Issue by Lyuxi8006** [nanomsg/nanomsg#1048]
sz = hdrsz +size
if ((sz  < hdrsz) 
{
     return -ENOMEM;
}

if ((hdr_size +size < size) 
{
     return -ENOMEM;
}

Is this possible?

**Comment by gdamore** [comment]
on a 32-bit system, you could wind up allocating more than 4GB, wrapping the counter.  Its a protection against overflow.
