### ISSUE TITLE
POSIX-compliance of Nanomsg library

### ISSUE THREAD

**Issue by magnusmusngi** [nanomsg/nanomsg#1049]
I am planning to port a code that uses this Nanomsg library into a POSIX-compliant OS that is neither Linux nor Unix. Given this, I would like to know if this library is POSIX-compliant, and if so, does that mean that I will not have any issues with this library while porting it to the aforementioned OS? Thank you.

**Comment by gdamore** [comment]
It should mostly be POSIX compliant.  However, if you can, I'd recommend attempting to use NNG, which is newer, and more actively maintained at this point.
