### ISSUE TITLE
nano支持自定义 消息的格式吗，例如 支持protobuf格式吗？

### ISSUE THREAD

**Issue by zhaoyangwyyx** [nanomsg/nanomsg#1051]

**Comment by zjj9850** [comment]
可以用protobuf序列化为wireformat的二进制啊，上层应用协议和网络传输协议应该是解耦无关的。。

**Comment by zjj9850** [comment]
> _No description provided._

可以用protobuf序列化为wireformat的二进制啊，上层应用协议和网络传输协议应该是解耦无关的。。

**Comment by zhaoyangwyyx** [comment]
ok，谢谢
