### ISSUE TITLE
sub can not reconnect on Linux

### ISSUE THREAD

**Issue by ren-zhihao** [nanomsg/nanomsg#1057]
centos 7(server) : sub
windows 10(client) : pub

If the server network is disconnected for more than 20 seconds, when the network is restored, sub can not reconnect.

**Comment by gdamore** [comment]
the reconnection times are configurable.  if you've been disconnected for a while, the retry times go up, doubling until they hit a maximum threshold.  So its possible that you just need to wait a bit for that to pass before it retries connecting.  How long did you wait?

**Comment by gdamore** [comment]
Closing due to no feedback.

Note that the upper time for this is absolutely configurable.  See nn_options for more info.
