### ISSUE TITLE
An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full.

### ISSUE THREAD

**Issue by phr34k** [nanomsg/nanomsg#1063]
On one machine I run a  nanomsg based system (NNanoMsg, C#) on, I keep frequently hitting a generic Winsock error 10055. First, the system just exists instead of propagating the error higher up to let the application handle it properly. This is likely because `asserts` in release mode gets converted into exit call (`DebugBreak` is only called in debug).

```
An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full.
[10055] (d:\git\nanomsg-0.5-beta\src\aio\usock_win.inc:474)
```

Secondary, I'm wondering if there are any odd things in nanomsg that could cause this error to be triggered. I'm using it in an application with maybe 5 clients connecting, to 2-3 different tcp based protocol ports, and then a couple of one-off ports (pair sockets). On average I might use 40-50 sockets, not really enough to cause port exhaustion application side.

The really weird thing is that even after I reboot the machine or kill off the application the system just won't recover from this error, and other application (teamviewer, tightvnc) seems to behave normally. So I'm wondering if there's any chance nanomsg could be corrupting some application memory, maybe affecting the winsock loaded memory or something?

**Comment by gdamore** [comment]
Restarting the application should not have any ramification for this.  Is there some limit on memory or address space (such as needing more than 4GB and using a 32bit app?)

**Comment by phr34k** [comment]
These particular machines are constrained running 32-bit yes. I'm using this library to replicate data in real-time, and on occasion to provide updates (sending a larger file/stream ~ 50MB) over a paired socket, to a handful of clients. Here's an so with more details surrounding the network error/state:

https://stackoverflow.com/questions/67467024/what-are-other-conditions-for-winsock-error-wsaenobufs-10055-to-be-thrown

Unfortunately, I haven't been able to pinpoint the direct circumstances leading up to this error. Eventually, the error disappeared without having had a chance to confirm what actually was and was not conclusive in terms of changes. Likely, some form, of dodgy state the application enters was the initial trigger. 


That being said, I'd be more interested in the ways nanomsg can handle these errors. In this particular situation, the 'server' process gets in a dodgy state- but it is actually the 'client' who is confronted with the `wsaenobufs` error.  Any of the `clients` could at any point receive a trigger to interact with the dodgy 'server' and just crash. Without having a possibility of handling the error internally, save the user's data, or at least tell them.

**Comment by gdamore** [comment]
To fully handle all the failure conditions -- especially out of memory conditions -- you'd really be advised to look into upgrading to NNG.  nanomsg itself has many corners where it simply asserts and bails out, whereas NNG was designed to never fail, and deal even with OOM as gracefully as it can.

Having said all that, it might be worth profiling your clients to determine why they are running out of resources.  A bad server should not cause that to happen.  Even legacy libnanomsg should not be leaking resources or something like that.

**Comment by gdamore** [comment]
I'm closing this as there isn't anything actionable we can do.
