### ISSUE TITLE
Is there some architecture material?

### ISSUE THREAD

**Issue by tongyishu** [nanomsg/nanomsg#1068]
I think there should be some architecture material for nanomsg to make it easier for newcomers to learn quickly, even though it's in "sustaining" mode.

**Comment by gdamore** [comment]
I'm not going to work on providing architecture docs for libnanomsg.  There's quite a lot out there already, and what you probably want is a guide, but if I invest in in a guide (which I intend to do) it will be focused on NNG rather than the legacy library.
