### ISSUE TITLE
sys/cdefs.h: No such file or directory

### ISSUE THREAD

**Issue by cekvenich2** [nanomsg/nanomsg#1070]
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild
npm ERR! make: Entering directory '/root/proj/anis-srv/srv/node_modules/nanomsg/build'
npm ERR!   CC(target) Release/obj.target/nanomsg/deps/nanomsg/src/aio/ctx.o
npm ERR! make: Leaving directory '/root/proj/anis-srv/srv/node_modules/nanomsg/build'
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@16.13.1 | linux | x64
npm ERR! gyp info find Python using Python version 3.9.7 found at "/usr/bin/python3"
npm ERR! (node:21054) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
npm ERR! (Use `node --trace-deprecation ...` to show where the warning was created)
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/root/proj/anis-srv/srv/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/root/proj/anis-srv/srv/node_modules/nanomsg/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/root/proj/anis-srv/srv/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/root/.cache/node-gyp/16.13.1/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/16.13.1',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/root/proj/anis-srv/srv/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/16.13.1/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/root/proj/anis-srv/srv/node_modules/nanomsg',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! In file included from /usr/include/pthread.h:21,
npm ERR!                  from ../deps/nanomsg/src/aio/../utils/mutex.h:29,
npm ERR!                  from ../deps/nanomsg/src/aio/ctx.h:26,
npm ERR!                  from ../deps/nanomsg/src/aio/ctx.c:23:
npm ERR! /usr/include/features.h:484:12: fatal error: sys/cdefs.h: No such file or directory
npm ERR!   484 | #  include <sys/cdefs.h>
npm ERR!       |            ^~~~~~~~~~~~~
npm ERR! compilation terminated.
npm ERR! make: *** [deps/nanomsg.target.mk:256: Release/obj.target/nanomsg/deps/nanomsg/src/aio/ctx.o] Error 1
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/root/proj/anis-srv/srv/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Linux 5.13.0-22-generic
npm ERR! gyp ERR! command "/usr/local/bin/node" "/root/proj/anis-srv/srv/node_modules/.bin/node-gyp" "rebuild"
npm ERR! gyp ERR! cwd /root/proj/anis-srv/srv/node_modules/nanomsg
npm ERR! gyp ERR! node -v v16.13.1
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok

**Comment by gdamore** [comment]
This looks like a problem with your build environment.  That file is typically found on BSD systems only and is part of the standard system headers there.

**Comment by cekvenich2** [comment]
It is latest ubuntu server with Linux 5.13.0-22-generic

**Comment by gdamore** [comment]
Strange.  Nonetheless the error is a missing header file that is being referenced from another header that is supplied by the system and is not part of nanomsg.

There isn't really anything I can do to fix it.

**Comment by cekvenich2** [comment]
Some of the other packages are including pre-built binaries somehow so consider something like that in the future.

**Comment by cekvenich2** [comment]
sudo DEBIAN_FRONTEND=noninteractive apt --reinstall install libc6 libc6-dev -yq
