### ISSUE TITLE
Bad file descriptor [9]

### ISSUE THREAD

**Issue by CYuSir** [nanomsg/nanomsg#1084]
/home/root/application/latest/lib64/libnanomsg.so.5(nn_efd_signal+0x44)[0x7fae3938b4]
/home/root/application/latest/lib64/libnanomsg.so.5(+0x121e4)[0x7fae38e1e4]
/home/root/application/latest/lib64/libnanomsg.so.5(nn_ctx_leave+0x3c)[0x7fae38fa34]
/home/root/application/latest/lib64/libnanomsg.so.5(+0x16930)[0x7fae392930]
/home/root/application/latest/lib64/libnanomsg.so.5(+0x18ecc)[0x7fae394ecc]
/home/root/application/latest/lib/libpthread.so.0(+0x77ac)[0x7fadb707ac]
/lib/libc.so.6(+0xda70c)[0x7fad85d70c]
Bad file descriptor [9] (/home/work/nanomsg/nanomsg-1.1.5/src/utils/efd_eventfd.inc:78)

This error caused my program crash

**Comment by gdamore** [comment]
I don't have enough information here to tell you what happened.  Typically this is an indication that the application closed a file it should not have.

Unfortunately libnanomsg is in minimal sustaining mode, so I'm not really investing much effort into it -- it has a number of limitations and can be brittle in the face of errors.  I recommend trying out NNG instead, if you can.

**Comment by gdamore** [comment]
Closed to age.  Not enough information here.
