### ISSUE TITLE
"fg: no job control" build error

### ISSUE THREAD

**Issue by HKGY** [nanomsg/nanomsg#1088]
While I try to build a rpm package with the spec file downloaded from other distributions like [fedoraproject](https://src.fedoraproject.org/rpms/nanomsg/blob/rawhide/f/nanomsg.spec),
rpmbuild says:
```
...
+ cd nanomsg-1.1.5
+ %cmake
/var/tmp/rpm-tmp.yQW7pQ: line 29: fg: no job control
error: Bad exit status from /var/tmp/rpm-tmp.yQW7pQ (%build)
...
```
and then failed.

I don't why build of this package works on other distributions but not my computer or my distribution.
Could you please help me with this problem?

**Comment by gdamore** [comment]
Your build process appears to be using job control (fg in particular).  There is nothing in libnanomsg that does this, and we don't supply an RPM, so talk to whoever gave you the RPM.

Alternatively use a shell with actual job control. :-) bash is known to possess this, as is zsh, and most modern shells.  Only extremely restricted shells lack it.

**Comment by gdamore** [comment]
Closing as this is nothing to do with libnanomsg itself.
