### ISSUE TITLE
function nn_chunkref_mv copy size is right?

### ISSUE THREAD

**Issue by MegamindLS** [nanomsg/nanomsg#1090]
void nn_chunkref_mv (struct nn_chunkref *dst, struct nn_chunkref *src)
{
    memcpy (dst, src, src->u.ref [0] == 0xff ?
        (int)sizeof (struct nn_chunkref_chunk) : src->u.ref [0] + 1);
}

if src->u.ref [0] equal 0xff，copy size sizeof (struct nn_chunkref_chunk)  should be nn_chunk_size (((struct nn_chunkref_chunk*) src)->chunk) ?

**Comment by gdamore** [comment]
The code is defective, but it's also a bit bizarre.  I've reimplemented it as part of the fix for #1105.
