### ISSUE TITLE
Assessment of the difficulty in porting CPU architecture for nanomsg

### ISSUE THREAD

**Issue by wangyuliu** [nanomsg/nanomsg#1093]
Hello everyone! I am working on implementing a tool to assess the complexity of CPU architecture porting. It primarily focuses on RISC-V architecture porting. In fact, the tool may have an average estimate of various architecture porting efforts.My focus is on the overall workload and difficulty of transplantation in the past and future,even if a project has already been ported.As part of my dataset, I have collected the **nanomsg** project. **I would like to gather community opinions to support my assessment. I appreciate your help and response!** Based on scanning tools, the porting complexity is determined to be  simple, with a simple amount of code related to the CPU architecture in the project.  Is this assessment accurate? I look forward to your help and response.

**Comment by gdamore** [comment]
A new processor should be trivial although only if it is ILP32 or LP64 and runs one of the operating systems we already support.

There is no CPU specific code in NNG itself.

**Comment by gdamore** [comment]
Ah this was for libnanomsg.  Well there is a known alignment bug which I'm about to fix (#1105) but otherwise RISCV-64 should Just Work.
