### ISSUE TITLE
The client can't receive the first message sent by the server with pub/sub protocol

### ISSUE THREAD

**Issue by lanceyao1009** [nanomsg/nanomsg#1094]
I add follow code to demo/pubsub_demo.cc to check the messages.

```
+        time_t t;
+        char hhmmss[9]; /* HH:MM:SS\0 */
+        t = (time_t)ntohl(secs);
+        strftime(hhmmss, sizeof(hhmmss), "%T", localtime(&t));
+        fprintf(stderr, "nn_send: %s\n", hhmmss);

         rc = nn_send (fd, msg, sizeof (msg), 0);
```

And the result like this:
lance$ ./src/nanomsg/demo/pubsub_demo ipc:///tmp/test.ipc -s
nn_send: 15:50:53
nn_send: 15:51:03
nn_send: 15:51:13
nn_send: 15:51:23

lance$ ./src/nanomsg/demo/pubsub_demo ipc:///tmp/test.ipc
15:51:03 <pid 1221982> There are 1 clients connected.
15:51:13 <pid 1221982> There are 1 clients connected.
15:51:23 <pid 1221982> There are 1 clients connected.

The first message(15:50:53) disappear even I start the client firstly.
Please help me, thanks.

**Comment by gdamore** [comment]
Please add a short delay ... it takes time for the connection to be established - usually a few dozen milliseconds, and if you send a message before that happens, it won't be accepted.

There really isn't a good way to fix this -- it is a limitation of the protocol, and a well known problem.
