### ISSUE TITLE
[BUG]I noticed that the first packet of data is lost when using nn_send. Upon testing, I discovered that this occurs due to asynchronous processing during initialization. The first packet is sent before the initialization process is complete, resulting in its loss.

### ISSUE THREAD

**Issue by lobmoo** [nanomsg/nanomsg#1095]
I noticed that the first packet of data is lost when using nn_send. Upon testing, I discovered that this occurs due to asynchronous processing during initialization. The first packet is sent before the initialization process is complete, resulting in its loss.
while(1)
    { 
        
        char str[4] = {0};
        snprintf(str, 4, "%d", i++);
        iRet =  nnmsg_send(iNnmsgFd, str, sizeof(str), NNMSG_WAIT);
        if (iRet != sizeof(str))
        {
            CLI_ERROR("Write %s\n", strerror(errno));
            return -1;
        }
        sleep(1);
    }

**Comment by gdamore** [comment]
This is normal.  If the connection takes longer to initialize and setup, then your attempt to send messages too soon might cause them to be lost (discarded) as the best effort pattern doesn't think there is a connection yet.

The usual workaround is to wait a little bit before you try sending messages right after connection.  A half second should be plenty. 

nanomsg was designed mostly with long-lived applications in mind, and the protocol simply doesn't have short lived connections in part of its core design.  Sorry about that.

(A similar problem happens on shut down -- if you shut down too quickly you can lose the message as well.)

There is no way to fix this without breakign the protocol compatibility.  We will probably do something about it in a future protocol revision, but that will be done for NNG and mangos, and not legacy libnanomsg.
