### ISSUE TITLE
Will the libnanomsg supports optimization

### ISSUE THREAD

**Issue by Anil9436** [nanomsg/nanomsg#1097]
Hi I tried optimizing my project which has the  libnanomsg in it so i'm getting this issue 
ERROR: could not determine socket polling method.
ERROR: could not determine socket signaling method.

**Comment by gdamore** [comment]
What do you mean by optimization?   What OS are you building for?

**Comment by Anil9436** [comment]
Okay first thing optimization I mean is we are compiling our binary with the -O2 optimization and other thing the OS. I am working on is aarch64 embedded yocto.

**Comment by gdamore** [comment]
Closing as this was just a question.
