### ISSUE TITLE
what is means of "Solves recurring messaging problems", "Buffer loaning to reduce data copies" in the nng_presentation ppt?

### ISSUE THREAD

**Issue by fengmao31** [nanomsg/nanomsg#1106]
I found some interesting points in the ppt 《[Scalability Protocols](https://staysail.github.io/nng_presentation/nng_presentation.html) presentation by Garrett D’Amore (Feb 2018)  https://staysail.github.io/nng_presentation/nng_presentation.html

**Solves recurring messaging problems**, **Buffer loaning to reduce data copies.**

I want to know if it is means when I have two subscribers in some processes/different processes in same device and they subscribe a topic from a publihser in another device. It only transport one copy than two copy in the socket stream between the two devices?

By the way, I found it is looks like that the nanomsg cancel the message zero-cpoy design in the zeromq?

**Comment by gdamore** [comment]
CLosing this , as nothing actionable here.
