### ISSUE TITLE
NN_TCP_NODELAY doesn't cause TCP_NODELAY to be set.

### ISSUE THREAD

**Issue by sustrik** [nanomsg/nanomsg#118]

**Comment by gdamore** [comment]
Huh.  I just noticed this yesterday while I was adding other options to websocket.

**Comment by gdamore** [comment]
I've become convinced that not only do we need to do this asap, but NN_TCP_NODELAY should really be the *default*. Nagle is pretty evil on platforms that do delayed TCP ACK, and I think this may be at the root of some very very long timeouts when trying to establish connections.  (Windows seems to need > 200 msec to establish a connection, which is consistent with some delayed TCP ACKs.)
