### ISSUE TITLE
Need to delay accepting connections on EMFILE

### ISSUE THREAD

**Issue by tailhook** [nanomsg/nanomsg#152]
Currently EMFILE processing is OK, except it eats 100% CPU. Need to sleep a bit before starting to accept again. Same probably true for ENFILE.

**Comment by gdamore** [comment]
WOW.  EMFILE is hard to hit with "reasonable" systems.  Its it actually appropriate to try to muddle on when hitting this?  (As opposed to just aborting the socket?)  In mangos I just terminate that endpoint, rather than attempting to carry on.

**Comment by tailhook** [comment]
@gdamore, I'm not sure where I was hitting it. But think about some application which has nanomsg among the other things. If app has a bug, i.e. it opened 1000 files, and nanomsg opens next one, you will get crash, instead of getting EMFILE (ENFILE) inside the application (i.e. when opening next application specific file). In fact currently you get 100% cpu instead crash, but it's hard to debug either.

I got this in practice. And no, EMFILE is not hard to hit, it's just limit of 1024 file descriptors per process on linux by default.

**Comment by gdamore** [comment]
Fair enuff.  Got a diff to address it?  I think adding a simple delay (10 msec is probably adequate) ought to be enough.

**Comment by gdamore** [comment]
Fixing this probably requires a new backoff state to be added to the various accept state machines.  This is a lot of work to do at this point.  One could look at the backoff's used for nn_bind() in the 0.9 and earlier releases for inspiration as to how to do this.

**Comment by gdamore** [comment]
libnng has fixed this, we inject a backoff for any kind of error like ENOMEM or EMFILE.

For libnanomsg, I'm not going to address this -- I'm focused entirely on getting nng ready so that we can use it to replace libnanomsg.
