### ISSUE TITLE
inproc test hangs

### ISSUE THREAD

**Issue by sustrik** [nanomsg/nanomsg#158]
To reproduce run inproc test in a tight loop on Win7. After few minutes the test will hang.

The problem seems to be that although the send buffer is set to 200 bytes, the sender can write only 190 bytes, then nn_send() call blocks and waits for the buffer to be emptied.

**Comment by gdamore** [comment]
The inproc_lat test suffers from thread safety issues.  inproc is fundamentally busted and needs a major refactoring.

**Comment by gdamore** [comment]
This is another inproc safety issue.  Closing as a dup of #429.
