### ISSUE TITLE
autogen.sh fails on Mac OS 10.9

### ISSUE THREAD

**Issue by hillegass** [nanomsg/nanomsg#171]
Cloned the github repo.  Tried to run ./autogen.sh:
    $ ./autogen.sh 
    main::scan_file() called too early to check prototype at /Developer/usr/bin/aclocal line 607.
    autoreconf: Entering directory `.'
    autoreconf: configure.ac: not using Gettext
    autoreconf: running: aclocal --force -I m4
    main::scan_file() called too early to check prototype at /Developer/usr/bin/aclocal line 607.
    configure.ac:31: warning: macro `AM_SILENT_RULES' not found in library
    autom4te: m4sugar/m4sugar.m4: no such file or directory
    aclocal: /Developer/usr/bin/autom4te failed with exit status: 1
    autoreconf: aclocal failed with exit status: 1

(Version? GNU Autoconf 2.61)

**Comment by marchon** [comment]
Unable to replicate this can we close this issue now?

nanomsg marchon$ ./autogen.sh
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: running: glibtoolize --copy --force
glibtoolize: putting auxiliary files in `.'.
glibtoolize: copying file `./ltmain.sh'
glibtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
glibtoolize: copying file `m4/libtool.m4'
glibtoolize: copying file `m4/ltoptions.m4'
glibtoolize: copying file `m4/ltsugar.m4'
glibtoolize: copying file `m4/ltversion.m4'
glibtoolize: copying file `m4/lt~obsolete.m4'
autoreconf: running: /opt/local/bin/autoconf --force
autoreconf: configure.ac: not using Autoheader
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:60: installing './compile'
configure.ac:36: installing './config.guess'
configure.ac:36: installing './config.sub'
configure.ac:31: installing './install-sh'
configure.ac:31: installing './missing'
Makefile.am: installing './depcomp'
parallel-tests: installing './test-driver'
autoreconf: Leaving directory `.'

**Comment by djc** [comment]
Closing. Feel free to reopen if you can still reproduce using latest master!

**Comment by sroycode** [comment]
working now
