### ISSUE TITLE
tests: throughput calculation may overflow

### ISSUE THREAD

**Issue by ostorj** [nanomsg/nanomsg#179]
In tests inproc_thr and local_thr the throughput is calculated in megabits per second.
However, the calculation may silently overflow if big enough message size / number combinations used, and a small value is displayed for the user, which is very misleading.
Suggested solution: type of messages per second variable should be changed to double.

**Comment by gdamore** [comment]
uint64_t would correspond to what other operating systems for NIC statistics, for example.

**Comment by gdamore** [comment]
I'll fix this in libnng.  Not going to bother with it for nanomsg.
