### ISSUE TITLE
linger doesn't seem to wait

### ISSUE THREAD

**Issue by rbx** [nanomsg/nanomsg#206]
When running tests included in perf directory, sometimes they fail to finish when message sizes are 1000000 bytes or higher, sometimes also with lower size.

With the latency test, local_lat returns with no output (as also in a successful run), but remote_lat never finishes and does not output anything. For example:

```
~/nanomsg/perf$ ./local_lat tcp://*:5555 1000000 100
~/nanomsg/perf$ 
```

```
~/nanomsg/perf$ ./remote_lat tcp://localhost:5555 1000000 100

```

With the throughput test, it is the other way around - remote_thr returns and local_thr hangs.

This occurs both over IPC and TCP. TCP both locally and over network - over network it sometimes fails also for lower message sizes, for example of 50000 bytes.

**Comment by rbx** [comment]
I am still able to reproduce this with 0.6 beta.
Upon some further investigation, it seems that the problem comes from the sender calling nn_close() too soon after the send() call. So that the queue gets terminated before the data is sent out. Thus the receiver keeps waiting for it forever.

I was able to fix this by introducing a sleep (for example 10 seconds) on the sender side. It allows the sender queue to finish before nn_close() is called.

I tried to increase the NN_LINGER to 10 seconds, but strangely it didn't help at all. So perhaps the bug is with the lingering?

**Comment by gdamore** [comment]
Any chance this is fixed with what's in git right now?

**Comment by gdamore** [comment]
Nope.

**Comment by gdamore** [comment]
So I think linger isn't just the TCP lingering, but also the upper layers of libnanomsg.  I need to think about how to fix this.  Probably not going to happen right away.

To be honest, unidirectional latency always feels a little sketchy to me.  I prefer to make round trip latency measurements, and divide by two.

**Comment by gdamore** [comment]
I'm not going to fix this in nanomsg itself -- in fact I'm pretty sure I removed the linger option from nanomsg altogether. 

libnng is a different matter -- there we can use linger and it is indeed meaningful.  We can't guarantee that the operating system will respect it, but we can.  I've done the work to make this work in libnng already.

Closing this one against nanomsg though.
