### ISSUE TITLE
Win32 race condition

### ISSUE THREAD

**Issue by mdre77** [nanomsg/nanomsg#226]
I propably found a race condition in nanomsg pipeline code. The always 
assertion happens, when i send data to a push socket, while the pull socket is 
shutting down. 

Assertion failed: 8 == NN_USOCK_STATE_ACTIVE (src/aio/usock_win.inc:326)
[Switching to Thread 2744.0xa44]

Breakpoint 1, 0x77748e76 in msvcrt!abort ()
   from /cygdrive/c/Windows/system32/msvcrt.dll
(gdb) bt
#0  0x77748e76 in msvcrt!abort () from /cygdrive/c/Windows/system32/msvcrt.dll
#1  0x6f68650f in nn_err_abort () at src/utils/err.c:33
#2  0x6f6824a5 in nn_usock_send (self=0x97f6e4, iov=0x1a1f5f4, iovcnt=3)
    at src/aio/usock_win.inc:326
#3  0x6f69a5a1 in nn_stcp_send (self=0x97f980, msg=0x1a1f724)
    at src/transports/tcp/stcp.c:146
#4  0x6f690611 in nn_pipe_send (self=0x97f980, msg=0x1a1f724)
    at src/core/pipe.c:185
#5  0x6f695e95 in nn_lb_send (self=0x97f208, msg=0x1a1f724, to=0x0)
    at src/protocols/utils/lb.c:79
#6  0x6f6966fe in nn_xpush_send (self=0x97f200, msg=0x1a1f724)
    at src/protocols/pipeline/xpush.c:163
#7  0x6f68b498 in nn_sock_send (self=0x97ee58, msg=0x1a1f724, flags=1)
    at src/core/sock.c:559
#8  0x6f68e805 in nn_send (s=5, buf=0x9c5ac8, len=77, flags=1)
    at src/core/global.c:644

**Comment by snikulov** [comment]
Looks like duplicate for #172.
@mdre77 could you please check this issue on latest release? 
Thank you.

**Comment by gdamore** [comment]
I believe this is long since fixed.  Closing.  Submitter, if it is still occurring (and I'm wrong), please reopen.   If you do that, please verify that its a problem with latest code in git.
