### ISSUE TITLE
Bad file descriptor [9] (src/aio/poller_epoll.inc:107)

### ISSUE THREAD

**Issue by sustrik** [nanomsg/nanomsg#230]
To reproduce run following two commands in different consoles on Linux:

while true; do nanocat --pub --bind-ipc "/tmp/testingZone"  --data "${s}" --delay 1; done;

while true; do nanocat --sub --connect-ipc "/tmp/testingZone"  --format msgpack ; done

**Comment by amosbird** [comment]
I've encountered this issue too. Is there any plan to amend this?

**Comment by gdamore** [comment]
I have a theory that this may be a race in nn_close().  Stay tuned.

**Comment by amosbird** [comment]
Great. Good to know this project is still active :)

**Comment by gdamore** [comment]
So testing this, it appears that my commit of PR #525 fixes this.

**Comment by amosbird** [comment]
This issue still exist in my Centos 6.7.
![f5ub68 dvg z5skg 1 4m](https://cloud.githubusercontent.com/assets/5085485/11205639/48129688-8d44-11e5-9335-4910cee63aed.png)

**Comment by gdamore** [comment]
Did you rebuild from head?

**Comment by amosbird** [comment]
Yes.
```
commit 8f9d80c73684caf3a08df41aaf8b91b96cfb06e3
Author: Garrett D'Amore <garrett@damore.org>
Date:   Mon Nov 16 16:43:15 2015 -0800

    fixes #212 Can't compile nanomsg with mingw on Windows
```

**Comment by gdamore** [comment]
Well that's unfortunate.  Especially since I cannot seem to reproduce it.

**Comment by gdamore** [comment]
Looking at the code, this is more bogus errno assertions. 

I think the problem is that we can indeed close the file descriptor out from underneath the polling thread.  That can of course cause EBADF to be returned.

That said, this condition looks like it would be benign were it not for that assertion.
