### ISSUE TITLE
Assertion on Windows/x86

### ISSUE THREAD

**Issue by horus42** [nanomsg/nanomsg#234]
Hi Guys,
I got the following assertion:
```
Unexpected source: state=3 source=27713 action=1 (src/transports/inproc/cinproc.c:223)
```
Does anybody know what went wrong and how I can fix it?
Thx for your help.

**Comment by gdamore** [comment]
So the first assertion is a bug in inproc.  The second is fixed.

**Comment by gdamore** [comment]
I'm going to close this as a dup of #429 -- although really the problem is that inproc is not MT-safe.
