### ISSUE TITLE
BUS tests hang on recv when using TCP

### ISSUE THREAD

**Issue by jahrain** [nanomsg/nanomsg#236]
I noticed a problem using the BUS sockets over TCP that the recv hangs.
I was able to reproduce this in the bus.c test by modifying the these lines:

    #define SOCKET_ADDRESS_A "tcp://127.0.0.1:5558"
    #define SOCKET_ADDRESS_B "tcp://127.0.0.1:5559"

Running the test will hang on the first nn_recv.
However, I found a work around by adding  nn_sleep (10) prior to each test_send.

**Comment by gdamore** [comment]
Yep.  This is TCP slow start.  This is a well understood problem, you need to wait a bit before doing recv or send on a connection, or you need to assume that the first message may/will be dropped.

Closing.
