### ISSUE TITLE
Application quit breaks content of a large packet being sent

### ISSUE THREAD

**Issue by Kosmokleaner** [nanomsg/nanomsg#239]
The packet arrives at the right size but the content is only partly right. 
packet size: ~10MB, missing content is after ~1-5 MB
I was sending over TCP (localhost) on win32.
I am calling nn_shutdown() and just exit the application
I am using nn_send(,,0)
receiver: tcp://*:5560
sender: tcp://127.0.0.1:5560
if I put a Sleep(1000) after the nn_send and before the nn_shutdown
it works fine.

BTW: Great library, compiling on windown was easy, API is simple and clean, this is my first test!!

**Comment by gdamore** [comment]
This is now ancient history.  Is this still a problem?

**Comment by gdamore** [comment]
This is a dup of #206 -- same issue - basically linger doesn't.
