### ISSUE TITLE
argument unused during compilation: '-pthread' (OS X 10.9)

### ISSUE THREAD

**Issue by djc** [nanomsg/nanomsg#258]
With this compiler:

Apple LLVM version 5.1 (clang-503.0.40) (based on LLVM 3.4svn)
Target: x86_64-apple-darwin13.2.0
Thread model: posix

**Comment by marchon** [comment]
Should we move this to a faq and close the issue?

**Comment by djc** [comment]
It seems like something we could fix at some point, so no.

**Comment by gdamore** [comment]
I see lots of complaints in the websockets code.  I'm disinclined to close just because gcc doesn't notice the problems.  I'm going to fix the websockets compilation problems that clang finds.

**Comment by gdamore** [comment]
I'm not seeing this on 10.10.x.

**Comment by marchon** [comment]
Is there a consistent test case we can use for cross platform validation?

On Monday, June 1, 2015, gdamore <notifications@github.com> wrote:

> I'm not seeing this on 10.10.x.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nanomsg/nanomsg/issues/258#issuecomment-107301844>.
>


-- 
P THINK BEFORE PRINTING: is it really necessary?

This e-mail and its attachments are confidential and solely for the
intended addressee(s). Do not share or use them without approval. If
received in error, contact the sender
and delete them.

**Comment by gdamore** [comment]
make check is mostly it.

	- Garrett

**Comment by gdamore** [comment]
I've been doing lots of work on Darwin lately.  If the complaint is in building on an older version of Darwin -- 10.8 is pretty old now -- I'm simply not going to worry about warnings there.  However, clang works beautifully on modern systems, and I have it in use here and on appveyor.

Closing this for now.
