### ISSUE TITLE
Unexpected source error

### ISSUE THREAD

**Issue by dangerousHobo** [nanomsg/nanomsg#272]
I'm running into the following error when my program attempts to connect to a pull server:
**Unexpected source: state=1 source=1 action=1 (src/aio/timer.c:141)**

Transport: IPC
Protocol: Push

I also get the same error with nanocat:
```
$ nanocat --pull --bind-ipc /var/log/supervisor/log.ipc &
  Unexpected source: state=1 source=1 action=1 (src/aio/timer.c:141)
$
```

I've seen the error mentioned before on the mailing list, but don't see an issue for it here on github:
http://www.freelists.org/post/nanomsg/Make-Check-failed

Make check passes for me.
```
PASS: tests/inproc
PASS: tests/inproc_shutdown
PASS: tests/ipc
PASS: tests/ipc_shutdown
PASS: tests/tcp
PASS: tests/tcp_shutdown
PASS: tests/pair
PASS: tests/pubsub
PASS: tests/reqrep
PASS: tests/pipeline
PASS: tests/survey
PASS: tests/bus
PASS: tests/block
PASS: tests/term
PASS: tests/timeo
PASS: tests/iovec
PASS: tests/msg
PASS: tests/prio
PASS: tests/poll
PASS: tests/device
PASS: tests/emfile
PASS: tests/domain
PASS: tests/trie
PASS: tests/list
PASS: tests/hash
PASS: tests/symbol
PASS: tests/separation
PASS: tests/zerocopy
PASS: tests/shutdown

============================================================================
Testsuite summary for nanomsg 0.4-beta-8-gaf167d2

============================================================================
# TOTAL: 29
# PASS:  29
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
```

My environment:
Busybox userspace
GNU glibc 2.17
GNU GCC 4.7.3
Freescale i.MX53 (ARM)

I can try and provide more information if needed.

**Comment by gdamore** [comment]
This is really old.  Can someone check if this is still a problem?

**Comment by walkr** [comment]
I've just tested on `OS X Yosemite` with `nanomsg 0.6-beta` and it looks like **it is not** a problem anymore.

Here are the tests I've used: [nanoservice-start-tests] (https://github.com/walkr/nanoservice-start-tests)

Cheers

**Comment by gdamore** [comment]
Based on reports believing this was an older bug fixed earlier, closing.
