### ISSUE TITLE
EL6 x86_64: make check: tests/ipc_shutdown fails Assertion at src/core/sock.c:818

### ISSUE THREAD

**Issue by jccleaver** [nanomsg/nanomsg#281]
On EL6 x86_64, building as unprivileged user, using configure options below:

+ ./configure --build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --target=x86_64-redhat-linux-gnu --program-prefix= --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --enable-doc --enable-debug

I receive this during a 'make check'

PASS: tests/ipc
./test-driver: line 107: 30953 Aborted                 "$@" > $log_file 2>&1
FAIL: tests/ipc_shutdown
PASS: tests/tcp

   nanomsg 0.4-beta: ./test-suite.log

TOTAL: 29
PASS:  28
SKIP:  0
XFAIL: 0
FAIL:  1
XPASS: 0
ERROR: 0

.. contents:: :depth: 2

FAIL: tests/ipc_shutdown

Assertion failed: src == NN_SOCK_SRC_EP && type == NN_EP_STOPPED (src/core/sock.c:818)

**Comment by jchedstrom** [comment]
Seeing this on ARMv7 (Zybo development board) running Ubuntu 12.04, Kernel 3.14. 

Nanomsg package version 0.5-beta-73-g2da0726

ipc_shutdown check only failed first time. Tried 5 times afterwards which passed.

```
src=0 type=33988
Assertion failed: src == NN_SOCK_SRC_EP && type == NN_EP_STOPPED (src/core/sock.c:830)
/bin/bash: line 5: 30712 Aborted                 ${dir}$tst
FAIL: tests/ipc_shutdown
```

**Comment by gdamore** [comment]
This is a dup of #469 and was fixed.
