### ISSUE TITLE
Windows IPC pub/sub: messages silently dropped if sent too fast

### ISSUE THREAD

**Issue by TTimo** [nanomsg/nanomsg#283]
I've built a test case in my repository for now:
https://github.com/TTimo/nanomsg/blob/0.4-beta/tests/ipc_flood.c

Sending 10 messages in quick succession, then trying to read them back.

I've put a wait before the last one, reading back will see the first message and the last one, but nothing in between.

Started tracing this a little bit. After the first message, nn_dist_send will early out in the "In the specific case when there are no outbound pipes. There's nowhere to send the message to. Deallocate it" part. No error is reported, message is silently dropped but API reports a good send.

I ran it on OSX as well, no messages are dropped and the test passes.

Any suggestions on what to investigate next?

**Comment by gdamore** [comment]
This is a non-issue, except perhaps a misunderstanding of PUB/SUB.  This is a best effort delivery protocol, and if you flood pub faster than sub can consume, you're going to drop messages.  Frankly, its not possible to "fix" this without creating a situation where one bad / slow subscriber could create stalls for everyone else in the network.

**Comment by gdamore** [comment]
CLosing this as its a misunderstanding/mis-expectation of PUB/SUB.  If you flood, you overrun queues, and messages get dropped.  Either don't flood, or use some other out of band protocol to cope with this.  PUB/SUB cannot, and will not.

**Comment by TTimo** [comment]
So that makes the protocol 'unreliable' then. It should at least return error codes when messages are getting dropped. I'm not sure how people hope to ever use this in production as is.

**Comment by gdamore** [comment]
Indeed, the protocol is *unreliable*.  Just like  UDP.  Its entirely best effort.  If you have a requirement for reliable delivery, you need to use REQ/REP, or you have to build another sideband protocol.

Most people use PUB/SUB as a broadcast delivery of updates, and at fairly moderate rates.  PUB/SUB is not for multicasting at high bandwidth, and indeed there is no such thing (really) as reliable multicast or broadcast either.
