### ISSUE TITLE
Assertion failed: citem->connects == 0

### ISSUE THREAD

**Issue by drewcrawford** [nanomsg/nanomsg#286]
I'm getting a lot of strange assertion failures / abort traps when using inproc.

here is one I've tracked down to a test case:

```python
#!python3
import nanomsg
from time import sleep
c = nanomsg.Socket(nanomsg.REQ)
c.connect("inproc://test")
s = nanomsg.Socket(nanomsg.REP)
s._set_recv_timeout(2)
s.bind("inproc://test")
try:
	s.recv()
except Exception as ex:
	print (ex)
s.close()
sleep(2)
s = nanomsg.Socket(nanomsg.REP)
s.bind("inproc://test")
s.close()
```

Using latest nanomsg-python and latest nanomsg on OSX 10.9 this always produces the output

```
Assertion failed: citem->connects == 0 (src/transports/inproc/ins.c:120)
Abort trap: 6
```

**Comment by gdamore** [comment]
Looking at the inproc code, nothing except the assertion check actually *uses* the connects value.

**Comment by gdamore** [comment]
That said, I believe the inproc code is fairly fragile.  Its clearly not thread safe.
