### ISSUE TITLE
Connecting to multiple surveyor sockets

### ISSUE THREAD

**Issue by tylertreat-wf** [nanomsg/nanomsg#289]
Is it possible for a respondent to connect to more than one surveyor socket? E.g.

```C
int sock = nn_socket (AF_SP, NN_RESPONDENT);
nn_connect (sock, url1)
nn_connect (sock, url2)
```

The current behavior seems to be undefined. With the above code, surveys are always and only received from either url1 or url2 but not both. If surveys can't be received from multiple sockets, I'd at least expect the behavior to be consistent when trying to connect to multiple sockets. Either:

1. Assert error when trying to connect when already connected to surveyor
2. Receive surveys from the first-made connection
3. Receive surveys from the last-made connection

**Comment by gdamore** [comment]
This was fixed with #387
