### ISSUE TITLE
Nanomsg an order of magnitude slower than zmq

### ISSUE THREAD

**Issue by wuz73** [nanomsg/nanomsg#300]
I thought nanomsg is supposed to be faster than zmq, but when I tested on my Thinkpad W520 running Centos6.4, I was very surprised to find out that it was an order of magnitude slower.

Here is my program:

<pre>
#include "../src/nn.h"
#include "../src/pair.h"
#include &lt;cstdio>
#include &lt;unistd.h>
#include &lt;cstring>
#include &lt;cassert>
#include &lt;pthread.h>
#include &lt;sys/time.h>

void* Send(void* context)
{
    int responder = nn_socket(AF_SP, NN_PAIR);
    assert(responder != -1);
    int rc = nn_connect(responder, "inproc://test");
    assert(rc >= 0);

    char buf[1024];
    unsigned long bytes = 0;
    int sz[] = { 16,32,64,96,128,160,192,224,256,384,512,768,1024};
    int p =0;
    for (unsigned count = 1048576; count--;)
    {
	unsigned len = sz[p];
        nn_send(responder, buf, len, 0);
	bytes += len;
	p = (p+1) % (sizeof(sz)/sizeof(sz[0]));
    }
    nn_send(responder, buf, 0, 0);
    printf("sent %lu bytes\n", bytes);
    nn_close(responder);
    return NULL;
}

void* Receive(void* arg)
{
    int receiver = (long)arg;
    char buf[1024];
    unsigned long bytes = 0;
    while (1)
    {
        int len = nn_recv(receiver, buf, sizeof(buf), 0);
	if (!len)
	    break;
	if (len &lt; 0)
	{
	    perror("zmq_recv");
	    break;
	}
	bytes += len;
    }
    printf("received %lu bytes\n", bytes);
    return NULL;
}

int main ()
{
    int receiver = nn_socket(AF_SP, NN_PAIR);
    assert(receiver != -1);
    int rc = nn_bind(receiver, "inproc://test");
    assert(rc >= 0);

    struct timeval tv;
    gettimeofday(&tv, NULL);
    unsigned long t0 = tv.tv_usec + tv.tv_sec * 1000000;

    pthread_t th;
    pthread_create(&th, NULL, Receive, (void*)receiver);
    Send(NULL);
    void* ret;
    pthread_join(th, &ret);

    gettimeofday(&tv, NULL);
    unsigned long t = tv.tv_usec + tv.tv_sec * 1000000 - t0;
    printf("elapsed=%.3f\n", t/1000000.);
    return 0;
}
</pre>

On my Thinkpad W520, it takes about 3.6-4.3s to run; whereas a similar version using zmq only took 0.4s.  Can someone please point out what I did wrong? Thanks!

**Comment by DamnnnSure** [comment]
still, by comparing zeromq4.0.5 and nanomsg0.5 using perf/local_thr or perf/local_thr with tcp://127.0.0.1, nanomsg is way slower than zeromq on OS X 10.10.

**Comment by gdamore** [comment]
Does anyone actually use inproc for anything real?  I had optimized my inproc implementation in mangos quite a bit, but I still wind up doing data copying -- I finally stopped caring about that when I realized how utterly pointless it is.  If you're passing data within the same process, there are dozens of better ways to do it than nanomgs/inproc.

**Comment by gdamore** [comment]
@DamnnnSure can you provide specific test arguments?

**Comment by earonesty** [comment]
@tailhook 

* _Any processing of the message is going to be order of magnitude slower_
 * therefore we should never benchmark a transport layer?
* _This is faster in zeromq only if your consumer is slower than producer_
 * this happens all the time, when the producer is, itself, a consumer
* _It's faster only for inproc, other transports should be same speed_
 * [but not really] (https://github.com/nanomsg/nanomsg/issues/319)
* _It's faster until you use any polling mechanism_
 * yuck, who polls anymore? so 1997

**Comment by tailhook** [comment]
@earonesty 
>    Any processing of the message is going to be order of magnitude slower
>        therefore we should never benchmark a transport layer?

We should. But it doesn't mean we should optimize 0.1% performance

>    This is faster in zeromq only if your consumer is slower than producer
>       this happens all the time, when the producer is, itself, a consumer

When producer itself a consumer there is no latency issue, it just puts message in it's own queue and it's already there when it reads queue. I'm not sure what you mean

>    It's faster only for inproc, other transports should be same speed
>        but not really

Yeah, the link to #319 says that TCP is faster than inproc. So it only supports my position

>    It's faster until you use any polling mechanism
>       yuck, who polls anymore? so 1997

Well we are from different worlds. Most my applications are multiplexing different things in single thread. May be you misunderstand what I mean by polling here?

@gdamore
>  If you're passing data within the same process, there are dozens of better ways to do it than nanomgs/inproc.

Two points here:
1. Inproc is useful for passing data between multiple languages (e.g. C and Python) inside single process
2. It's useful as a way to use nanomsg semantics (which is complex to emulate even using go channels), and to scale later (e.g. easily switch between inproc and network)

But none of them are very performance sensitive in my opinion. First one usually has big overhead because of "impedance mismatch" between languages. Second is because you will use non-inproc at production anyway.

**Comment by gdamore** [comment]
Exactly.  You're optimizing away a data copy with inproc may be useful, but I'm not going to be overly concerned about it, because if you're using inproc, you're not doing so for performance.

In fact, case 1 seems kind of a stretch IMO; if you have two languages in the same process, its probably because you have FFI and one of them is C, in which case you probably have a better way to move data between languages.

Indeed, in the case of mangos inproc, it is not possible to connect it to the C libnanomsg via inproc.  They don't speak to the same backend. I guess using libnanomsg only, it might work, although I'm really really skeptical.  Have you tried this?

We could make a socketpair() based inproc, that would be portable across all of these, I suppose, although figuring out how to handle registration of endpoints might be ... tricky.

**Comment by andrewstarks** [comment]
On Friday, February 13, 2015, Paul Colomiets <notifications@github.com>
wrote:

> @earonesty <https://github.com/earonesty>
>
> Any processing of the message is going to be order of magnitude slower
> therefore we should never benchmark a transport layer?
>
> We should. But it doesn't mean we should optimize 0.1% performance
>
> This is faster in zeromq only if your consumer is slower than producer
> this happens all the time, when the producer is, itself, a consumer
>
> When producer itself a consumer there is no latency issue, it just puts
> message in it's own queue and it's already there when it reads queue. I'm
> not sure what you mean
>
> It's faster only for inproc, other transports should be same speed
> but not really
>
> Yeah, the link to #319 <https://github.com/nanomsg/nanomsg/issues/319>
> says that TCP is faster than inproc. So it only supports my position
>
> It's faster until you use any polling mechanism
> yuck, who polls anymore? so 1997
>
> Well we are from different worlds. Most my applications are multiplexing
> different things in single thread. May be you misunderstand what I mean by
> polling here?
>
> @gdamore <https://github.com/gdamore>
>
> If you're passing data within the same process, there are dozens of better
> ways to do it than nanomgs/inproc.
>
> Two points here:
> 1. Inproc is useful for passing data between multiple languages (e.g. C
> and Python) inside single process
> 2. It's useful as a way to use nanomsg semantics (which is complex to
> emulate even using go channels), and to scale later (e.g. easily switch
> between inproc and network)
>
> But none of them are very performance sensitive in my opinion. First one
> usually has big overhead because of "impedance mismatch" between languages.
> Second is because you will use non-inproc at production anyway.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/nanomsg/nanomsg/issues/300#issuecomment-74265172>.
>

Our plan is to use improc between Lua states, serializing with msgpack.
Also, we pass pointer values (gasp) that way too, but for production we'll
switch to passing buffers with inproc.

**Comment by tailhook** [comment]
> In fact, case 1 seems kind of a stretch IMO; if you have two languages in the same process, its probably because you have FFI and one of them is C, in which case you probably have a better way to move data between languages.

I mean two languages in different threads communicating between each other. Useful in Python because of GIL.

I'm not sure that making inproc with socket pipe is good idea. We probably should ask @sustrik, as I think he had some good cases for fast inproc transport from the ancient zeromq times.

**Comment by andrewstarks** [comment]
On Friday, February 13, 2015, Paul Colomiets <notifications@github.com>
wrote:

> In fact, case 1 seems kind of a stretch IMO; if you have two languages in
> the same process, its probably because you have FFI and one of them is C,
> in which case you probably have a better way to move data between languages.
>
> I mean two languages in different threads communicating between each
> other. Useful in Python because of GIL.
>
> I'm not sure that making inproc with socket pipe is good idea. We probably
> should ask @sustrik <https://github.com/sustrik>, as I think he had some
> good cases for fast inproc transport from the ancient zeromq times.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/nanomsg/nanomsg/issues/300#issuecomment-74346982>.
>

This is useful for any language that wants to mimic a message passing
pattern that is network transparent.

For example, Lua is not multi-threaded, but does coroutines (not really
relevant).

Anyway, spolling up a second thread and passing messages inproc between
states is a very clean design.

With inproc / nanomsg, you have a familiar socket interface and message cue
plus the possibility to implement / ad hoc other super-fast architectures
using bus, pub/sub, etc.

We would use something else, if there was too much additional
overhead/latency.

-Andrew

**Comment by gdamore** [comment]
I've been spending a bit more time in the code of late.  I'm not surprised that things are kind of slow.  nanomsg uses separate system calls (several!) to provide notification of message readiness... the poll() logic is crafted to be compatible with UNIX file descriptors, but doing so means that "notifications" come by sending a single byte of data to a "pollable" descriptor. 

I'm not sure I can do much about this without breaking the file descriptor compatibility in nn_poll.

That said, performance if inproc remains a mostly uninteresting problem, IMO.

**Comment by Downchuck** [comment]
I think message size is the big issue in this benchmark; in most cases where there's a high volume of messages, there's an opportunity to batch beyond a few hundreds bytes.

**Comment by gdamore** [comment]
Batching comes at a cost in terms of latency.   There is a trade off.  Most systems choose throughout and the rest of us who need low latency spend our time undoing those optimizations.

**Comment by Downchuck** [comment]
And in the case of the person posting the bug report, there's more than a second of added latency, as there is no batching in place.

**Comment by gdamore** [comment]
So, the big issue here is that in order for nanomsg to provide select() / poll() compatible semantics, it has to fake up a pipe and actually do system calls with read/write.

This is not solvable.  The design constraint to be socket compatible creates this situation, and there is no solution without breaking that constraint.

Batching and the other issues like TCP_NODELAY having no effect (which is a separate bug filed already) don't help.  But at its heart, select() compatible API cannot be as performant as one that isn't.

(Its actually worse than that --because even for vanilla TCP we have to do this fake out thing, because we don't expose the underlying FD directly to the consuming application.)

TBH, the whole select() compatible API was IMO a big design mistake.

Anyway, closing this as "will-not-fix".  (I may "fix" this in an alternate implementation, that provides a simpler API that doesn't align with select().  That would lead to a vastly simpler implementation as well.)

**Comment by Moore123** [comment]
Conform transmission speed lower with nanomsg NN_REQ/NN_REP mode, extremely slowly than 0mq.

**Comment by AleXoundOS** [comment]
Any updates on this?

**Comment by gdamore** [comment]
So I closed this issue above.  I have been looking at another architecture which would move notification
to another mechanism, and allow us to get rid of the separate system calls.  That would be lots and lots faster if you don't need file descriptor notification.  However, this represents a large change to huge swathes of the core of nanomsg, so it's a nanomsg 2.0 thing.

**Comment by AleXoundOS** [comment]
Thank you.

**Comment by reqshark** [comment]
Cool! Looking forward to that and learning more!

**Comment by lygstate** [comment]
@gdamore What's the design of your new notification mechanism?
For inproc interproc & network. Do they using different notification mechanism?

**Comment by gdamore** [comment]
All these should use condition variables to notify.  This is light weight,
and can avoid the multiple system calls required to effect the notification
now.

Unfortunately, the current design is not directly conducive to this, so it
needs some surgery too.

 - Garrett

**Comment by lygstate** [comment]
@condition variable? Do you means semaphore ?

**Comment by lygstate** [comment]
I suggest to re-open this issue and put it on the table.

**Comment by gdamore** [comment]
No.  I mean condition variable.   See
https://en.wikipedia.org/wiki/Monitor_(synchronization)#Condition_variables_2

There are nice primitives for this in most operating systems .. see
pthread_condvar_wait() for some information.

**Comment by lygstate** [comment]
@gdamore That's looks not that hard. Can you provide a API list that need to be implemented?
by condition variables.

**Comment by lygstate** [comment]
Code update
```
#include "../src/nn.h"
#include "../src/pair.h"
#include <cstdio>
#include <cstring>
#include <cassert>
#include <thread>
#include <time.h>

#ifdef _WIN32
#include <Windows.h>
#else
#include <sys/time.h>
#endif

#ifdef _WIN32

#if defined(_MSC_VER) || defined(_MSC_EXTENSIONS)
#define DELTA_EPOCH_IN_MICROSECS  11644473600000000Ui64
#else
#define DELTA_EPOCH_IN_MICROSECS  11644473600000000ULL
#endif

struct timezone
{
    int  tz_minuteswest; /* minutes W of Greenwich */
    int  tz_dsttime;     /* type of dst correction */
};

int gettimeofday(struct timeval *tv, struct timezone *tz)
{
    FILETIME ft;
    unsigned __int64 tmpres = 0;
    static int tzflag = 0;

    if (NULL != tv)
    {
        GetSystemTimeAsFileTime(&ft);

        tmpres |= ft.dwHighDateTime;
        tmpres <<= 32;
        tmpres |= ft.dwLowDateTime;

        tmpres /= 10;  /*convert into microseconds*/
                       /*converting file time to unix epoch*/
        tmpres -= DELTA_EPOCH_IN_MICROSECS;
        tv->tv_sec = (long)(tmpres / 1000000UL);
        tv->tv_usec = (long)(tmpres % 1000000UL);
    }

    if (NULL != tz)
    {
        if (!tzflag)
        {
            _tzset();
            tzflag++;
        }
        tz->tz_minuteswest = _timezone / 60;
        tz->tz_dsttime = _daylight;
    }

    return 0;
}
#endif

void Send()
{
    int responder = nn_socket(AF_SP, NN_PAIR);
    assert(responder != -1);
    int rc = nn_connect(responder, "inproc://test");
    assert(rc >= 0);

    char buf[1024];
    unsigned long bytes = 0;
    int sz[] = { 16,32,64,96,128,160,192,224,256,384,512,768,1024 };
    int p = 0;
    for (unsigned count = 1048576; count--;)
    {
        unsigned len = sz[p];
        nn_send(responder, buf, len, 0);
        bytes += len;
        p = (p + 1) % (sizeof(sz) / sizeof(sz[0]));
    }
    nn_send(responder, buf, 0, 0);
    printf("sent %lu bytes\n", bytes);
    nn_close(responder);
}


void Receive(int receiver)
{
    char buf[1024];
    unsigned long bytes = 0;
    while (1)
    {
        int len = nn_recv(receiver, buf, sizeof(buf), 0);
        if (!len)
            break;
        if (len < 0)
        {
            perror("nano_recv");
            break;
        }
        bytes += len;
    }
    printf("received %lu bytes\n", bytes);
}

int main()
{
    int receiver = nn_socket(AF_SP, NN_PAIR);
    assert(receiver != -1);
    int rc = nn_bind(receiver, "inproc://test");
    assert(rc >= 0);

    struct timeval tv;
    gettimeofday(&tv, NULL);
    unsigned long t0 = tv.tv_usec + tv.tv_sec * 1000000;

    std::thread receiveThread(Receive, receiver);
    std::thread sendThread(Send);

    sendThread.join();
    receiveThread.join();

    gettimeofday(&tv, NULL);
    unsigned long t = tv.tv_usec + tv.tv_sec * 1000000 - t0;
    printf("elapsed=%.3f\n", t / 1000000.);
    return 0;
}
```
This can be running under both Windows/Unix.
and the time that running under windows are:
```
received 311022272 bytes
sent 311022272 bytes
elapsed=8.936
Press any key to continue . . .
```

Yes, it's horribly slow.

**Comment by gdamore** [comment]
I'll point out that you performed about 1M transactions.  That's about 100K per sec (a little more than that) for a single thread.  Yes, its slow, and it can be a lot better.  But it is more than adequate for most uses.  If you're expecting inproc to be blindly fast and using it as an in-process *bulk* transport, you're going to be disappointed.  As I've said, if you want to do that, just use a function call.  :-)

I will at some point have enough time to finish the rearchitecture to address these problems.  I cannot do it without changing core parts of nanomsg -- and its *not* simple.  If I could write up in a few sentences what needed to be done, I'd have already done it.

**Comment by lygstate** [comment]
@gdamore Sorry for pushing you about this issue. I know it's a very big changes to nanomsg, I am seeking for if there would be a small preview of the big picture. I'd like to disuses with you about this issue.

**Comment by MaroShim** [comment]
I think the original title is better. google search shows this issue for nanomsg, but current title is misleading...

wuz73 changed the title from Performance issues of inproc with NN_PAIR to Nanomsg an order of magnitude slower than zmq on 16 Aug 2014
