### ISSUE TITLE
Compiling nanomsg for Android

### ISSUE THREAD

**Issue by kristianlm** [nanomsg/nanomsg#316]
We've put together an [Android.mk](https://gist.github.com/kristianlm/27d12ca7e4b2ef8e89fc) file which seems to build nanomsg for Android without any problems with one exception:

```
bionic/libc/kernel/common/linux/un.h:18: error: expected specifier-qualifier-list before 'sa_family_t'
```

which was fixed with this patch:

``` diff
diff --git a/src/transports/ipc/ipc.c b/src/transports/ipc/ipc.c
index 26ffb07..39d7371 100644
--- a/src/transports/ipc/ipc.c
+++ b/src/transports/ipc/ipc.c
@@ -36,6 +36,7 @@
 #if defined NN_HAVE_WINDOWS
 #include "../../utils/win.h"
 #else
+#include <linux/socket.h>
 #include <sys/un.h>
 #include <unistd.h>
 #endif
```

It's probably just bionic that's suffering from this, but since it's a relatively unintrusive patch, I though I might suggest it upstream.

**Comment by mardistal** [comment]
How did you compile he mk file ?

**Comment by kristianlm** [comment]
@mardistal that depends on your Android setup, really. We're building Android from scratch (aka aosp) which builds all Android.mk files by itself.

If I remember correctly, it's the same with NDK apps: `Android.mk` files under `./jni/` will get built in.

**Comment by sweisgerber-dev** [comment]
Older example:

https://github.com/RPetrov/nanomsg-android/blob/master/app/jni/Android.mk
