### ISSUE TITLE
IOCP doesn't report disconnections sometimes

### ISSUE THREAD

**Issue by sustrik** [nanomsg/nanomsg#328]
This causes unexpected behavour in the cases like this one:

    sb = test_socket (AF_SP, NN_PAIR);
    test_bind (sb, SOCKET_ADDRESS);
    s1 = test_socket (AF_SP, NN_PAIR);
    test_bind (s1, SOCKET_ADDRESS);
    sc = test_socket (AF_SP, NN_PAIR);
    test_connect (sc, SOCKET_ADDRESS);
    nn_sleep (100);
    test_send (sb, "ABC");
    test_recv (sc, "ABC");
    test_close (sb);
    nn_sleep (300);
    // Following line block because re-connection haven't happened  because
    // failure of the original connection wasn't reported by IOCP.
    test_send (s1, "ABC");
    test_recv (sc, "ABC");
    test_close (sc);
    test_close (s1);

The possible solution is to have an outstanding request to read 0 bytes of OOB data at all times. It will get triggered only when disconneciton happens. See here:

http://stackoverflow.com/questions/11210995/how-to-detect-disconnection-rst-fin-using-windows-iocp

**Comment by gdamore** [comment]
This is true for POSIX systems too -- if you don't attempt to do I/O, you might never notice a disconnect or loss of a connection.  I found the read() (of any data) to be required on POSIX systems with mangos.  We should probably do this in the protocol handers -- even write-only protocol handlers should probably set up a reader on the underlying transport, just to catch this condition.

**Comment by gdamore** [comment]
I think I've found workarounds for this.  IOCP fails, but we can close the remote peer, which causes a POLLHUP condition to arise, which makes everyone happy.  So far this seems to work.

Martin, do you have a PR with the formal test case for this?

**Comment by gdamore** [comment]
So I made one, from your code, obviously. :-)

**Comment by gdamore** [comment]
So, actually, the test so far looks pretty good; I think PR #525 that I integrated actually solves this.  The test code is passing at least.

**Comment by gdamore** [comment]
(You'll note that the only thing I merged here was your test case.)
