### ISSUE TITLE
0.5 beta failed to build on openbsd

### ISSUE THREAD

**Issue by zshipko** [nanomsg/nanomsg#336]
Here's a diff of the change I made to get it to compile:

    --- src/aio/usock_posix.h	Fri Nov 14 13:33:29 2014
    +++ ../../nanomsg-0.5-beta/src/aio/usock_posix.h	Sun Nov 16 03:05:37 2014
    @@ -65,7 +65,7 @@
             struct msghdr hdr;
 
             /*  List of buffers being sent at the moment. Referenced from 'hdr'. */
    -        struct iovec iov [NN_USOCK_MAX_IOVCNT];
    +        struct nn_iovec iov [NN_USOCK_MAX_IOVCNT];
         } out;
 
         /*  Asynchronous tasks for the worker. */

**Comment by marchon** [comment]
It looks like this issue is dealt with should we close it?

**Comment by djc** [comment]
Yup!
