### ISSUE TITLE
hang on tcp pipeline

### ISSUE THREAD

**Issue by diffuse** [nanomsg/nanomsg#342]
Running the code below causes nanomsg to hang on poll in nn_recv.

#include "../src/nn.h"
#include "../src/pipeline.h"
#include "testutil.h"

#define SOCKET_ADDRESS "tcp://127.0.0.1:12234"

int main ()
{
    int push1;
    int pull1;
	int i;

    push1 = test_socket (AF_SP, NN_PUSH);
    test_bind (push1, SOCKET_ADDRESS);
    pull1 = test_socket (AF_SP, NN_PULL);
    test_connect (pull1, SOCKET_ADDRESS);

    nn_sleep (10);

	for (i = 0; i < 1000000; i++) 
	{
		test_send (push1, "ABC");
		test_recv (pull1, "ABC");
	}
	test_close (push1);
	test_close (pull1);

	return 0;
}

**Comment by marchon** [comment]
A change has been merged - is this issue still open?

**Comment by diffuse** [comment]
This issue was fixed by commit a52e25102f55ad72978c6a4691c3aeece7d18563

**Comment by marchon** [comment]
Can we please close PR #342

On Mon, Jan 26, 2015 at 2:39 PM, diffuse <notifications@github.com> wrote:

> This issue was fixed by commit a52e25102f55ad72978c6a4691c3aeece7d18563
>
> On Mon, Jan 26, 2015 at 2:31 PM, George Lambert <notifications@github.com>
>
> wrote:
>
> > A change has been merged - is this issue still open?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/nanomsg/nanomsg/issues/342#issuecomment-71522044>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nanomsg/nanomsg/issues/342#issuecomment-71523310>.
>



-- 
P THINK BEFORE PRINTING: is it really necessary?

This e-mail and its attachments are confidential and solely for the
intended addressee(s). Do not share or use them without approval. If
received in error, contact the sender
and delete them.

**Comment by djc** [comment]
Yup, thanks.
