### ISSUE TITLE
nanocat line-based mode?

### ISSUE THREAD

**Issue by eldondev** [nanomsg/nanomsg#354]
nanocat looks like an excellent minimal tool for some common use cases I have on the command line. Is there any interest in a PR to provide a mode making it line-oriented when it reads from a file (or stdin)? What I would like is to be able to do is something like `tail -f logfile | nanocat --pub --by-line ...` and receive that elsewhere. It looks like that the moment, all information is read from the data or file at once.

**Comment by gdamore** [comment]
The problem with the lost packets are almost certainly TCP slow start.  TCP takes a bit to connect, and you can't just immediately start publishing.  You need to sleep a bit before you can publish.  This is one of the drawbacks of the nanocat tool.

As far as the --by-line, feel free to submit a code change.  I'm less thrilled with it, but if someone offers up decent code for it I'll be happy to integrate.

**Comment by gdamore** [comment]
This is ancient, and I'm not going to do it for nanomsg.  I'd be open to some suggestions around NNG.  I think nngcat already has some capabilities that may be helpful here.
