### ISSUE TITLE
poll() returns immediately even when the socket cannot be written to yet

### ISSUE THREAD

**Issue by dv1** [nanomsg/nanomsg#357]
I am using poll() with the FD I get from nn_getsockopt() to watch a PUSH socket. The idea is to wait until I can write to the nanomsg socket without nn_send() blocking. Except, this doesn't work.

Instead, poll() returns immediately, even if the socket can't be written to yet (for example, because no receiver is connected). If I use nn_send() with no flags, it blocks. If I use it with the NN_DONTWAIT flag, it sets errno to EAGAIN.

Here is example code that demonstrates the error: http://pastie.org/private/itahcjahfzeyyqjizqblq
It is simply a modified version of the pipeline example from http://tim.dysinger.net/posts/2013-09-16-getting-started-with-nanomsg.html

**Comment by dsouzae** [comment]
Any reason why you do not want to use nn_poll?  

I was able to change your example code to use nn_poll and it "waits" till node0 is up before sending.

After reading the nanomsg code, the nn_getsockopt NN_SNDFD is actually returning the fd of an eventfd fd.  Which is probably not want you want.

**Comment by dv1** [comment]
nn_poll can be used with SP sockets only. I was using poll() with a pipe socket as well. I could create a dummy SP socket instead of the pipe, sure. But if you are right, then NN_SNDFD is useless! I mean, it is  supposed to be usable with select/poll/kqueue/epoll etc., isn't it? If it cannot be used for that purpose, then what is it good for?

**Comment by dsouzae** [comment]
I re-looked at the source code for nn_poll, and your code is almost right.  

Change all occurrences of POLLOUT to POLLIN and your code should work.

**Comment by dv1** [comment]
Hah, indeed, it works! EAGAIN no longer occurs.

But perhaps this should be mentioned in the documentation, since it is not intuitive. I  mean, if I am watching a send FD, I immediately think I need to use POLLOUT (or the equivalent in select/kqueue/etc.), since I'll write to the associated SP socket. But instead, you are *always* supposed to poll for reading on the send FD.

**Comment by marchon** [comment]
I think we should add this to a FAQ and close this issue.

**Comment by djc** [comment]
I think it should just be in the relevant documentation section.

**Comment by gdamore** [comment]
Either way, can we close this? Leaving these bugs interminably open doesn't "look good".

**Comment by cbandy** [comment]
It should close when the docs are done, I think.

**Comment by djc** [comment]
Yeah, it seems like a doc patch would be useful here.

**Comment by mguijarr** [comment]
My 2 cents: it is clearly stated in the documentation that file descriptors should be checked
for readable state, either for RCVFD or SNDFD.

**Comment by gdamore** [comment]
Yeah, its clear from docs.  I've also spent time reading the code to understand why this is so.  Its kind of crazy.  But that's the behavior.  Closing.
