### ISSUE TITLE
IPv6 disabled by default

### ISSUE THREAD

**Issue by vbmithr** [nanomsg/nanomsg#358]
Is there any rationale to have IPv6 disabled by default ? Or any advantage to disable it rather than enabling it by default ?

**Comment by gdamore** [comment]
This will depend on the operating system.  Some operating systems either lack IPv6 support, or have dodgy support for interoperability between IPv4 and IPv6.  Personally, the systems I use generally support IPv6 well.  But that may or may not be the case for you.

The other thing is handling of IPv6 URIs.  Your users, if they aren't expecting IPv6 URIs to show up in the addresses, may be surprised.  Applications doing getpeername() or similar things on underlying file descriptors may also be surprised.

All that said, I think that probably we ought to consider enabling v6 by default.

**Comment by vbmithr** [comment]
On 31/05/2015 20:43, gdamore wrote:
> All that said, I think that probably we ought to consider enabling v6 by
> default.

Thank for the explanations! :)

-- 
Vincent

**Comment by gdamore** [comment]
I'm not going to do this for v0.7, but maybe after?

**Comment by gdamore** [comment]
So I've had some very mixed results with dual stack sockets ... and I'm starting to think that a better solution would be to explicitly insist on the use of tcp6:// urls.

There are problems there too... Stay tuned.

**Comment by gdamore** [comment]
So with NNG we have tcp://, tcp6://, and tcp4:// URLs.

For nanomsg, I'm not going to change this, because I don't want to disrupt things for people who are already using it.

If you care about this, please consider trying out NNG.  github.com/nanomsg/nng
