### ISSUE TITLE
Windows VS2010. Intermittent test failure in emfile

### ISSUE THREAD

**Issue by nickva** [nanomsg/nanomsg#362]
Test fails intermittently. Maybe 1 in 10 times.

Stack trace with some local vars: 

emfile.c:
```
/*  First, just create as much SP sockets as possible. */
    for (i = 0; i != MAX_SOCKETS; ++i) {
        socks [i] = nn_socket (AF_SP, NN_PAIR); // <- FAILS HERE
```
Local vars:  i=34

Context of failure in nn_socket.c:
```
 /*  Make sure that global state is initialised. */
    nn_global_init ();
    rc = nn_global_create_socket (domain, protocol); // <- FAILS HERE
```
Local vars: domain=1, protocol=16

global.c
```
rc = nn_sock_init (sock, socktype, s);
```
Local vars: s=34

sock.c
```
else {
        rc = nn_efd_init (&self->sndfd); // <- FAILS HERE
        if (nn_slow (rc < 0))
            return rc;
    }
```

efd_win.inc:
```
wsafail2:
    brc = SetEvent (sync);
    win_assert (brc != 0);
    brc = CloseHandle (sync);
    win_assert (brc != 0);
    errnum_assert (0, rc); // <- FAILS HERE
    return -rc;
```
Local Vars:

		nodelay = 1
		brc = 1
		listener = 1112	
		addr	{sin_family=2 sin_port=4887 sin_addr={...} ...}
		addrlen =	-858993460
		reuseaddr = 1
		dwrc = 0
		sync = 0x00000444	
		i = 0
		nonblock = 3435973836
		rc = 119

Additional info:

Commit: git hash 6a333ae (Dec 17, 2014)

System: Windows 7, VS2010 SP1, x64

**Comment by nickva** [comment]
Possibly related:  zerocopy.c fails in line 51 (req=test_socket(AF_SP_RAW, NN_REQ)).

With stack trace leading down to same nn_socket_init() -> nn_efd_init()  and local vars as similar values like in emfile.c failure above (rc=119, i=0, etc)

**Comment by gdamore** [comment]
I've not seen this particular test fail in AppVeyor since I moved testing there.  I'm inclined to close this -- quite possibly other changes made since then have fixed this.

**Comment by wirebirdlabs** [comment]
@nickva -- I've likewise seen this error in the past compiling on MSVC, but as @gdamore reports, I have not seen it in quite some time since many other improvements have been made to the library.

This failure mode always seemed (anecdotally) to be a cascaded failure from something not working correctly upstream; most likely mutexing of a globally-shared resource.

Unless you report otherwise, I'd likewise be inclined to close this issue as "fixed".

**Comment by nickva** [comment]
Yap let's close it.

**Comment by wirebirdlabs** [comment]
Cool; thanks!
