### ISSUE TITLE
don't crash when tcpmuxd not started; tell the user what is missing

### ISSUE THREAD

**Issue by glycerine** [nanomsg/nanomsg#365]
arg. the pull request #364 is a start, but clearly not the whole story needed for tcpmuxd to become usable in library code. I can readily crash nanomsg by trying to bind to a tcpmux socket before starting the tcpmuxd.  Instead of freaking out and crashing, we need to calmly return an informative error to user. Something like "cannot locate tcpmuxd on port 5555. please start a daemon and/or confirm port number" would be very useful. "Unexpected state" errors are pretty useless for clients. Crashing the app is verboten.

For example, in R:
~~~
> library(nanomsgardvark)
> sb = nn.socket(nn.AF_SP, nn.PAIR)
> rc = nn.bind (sb, "tcpmux://*:5555/foo")
Unexpected state: state=5 source=1 action=7 (src/transports/tcpmux/btcpmux.c:466)
~~~

**Comment by javalama** [comment]
tcpmux is incredibly useful, but buggy.

Is there work being done in this area?

**Comment by glycerine** [comment]
Non-authoritative answer: not that I know of. But hey: it is open source. Jump in with a pull request and make it awesome!

**Comment by reqshark** [comment]
perhaps #503 will help

**Comment by gdamore** [comment]
Don't think so.   I'm really not a fan of tcpmuxd.  The code is probably a little fragile here; I'd welcome PRs to make it better here.

**Comment by gdamore** [comment]
tcpmux is about to be removed.  Recommend using websocket with a url redirector, or with mangos (which also gives you HTTPS for security) instead.

**Comment by gdamore** [comment]
tcpmux is gone.  Closing.
