### ISSUE TITLE
Assertion failed: !ipv6 (src/transports/utils/iface.c:88)

### ISSUE THREAD

**Issue by rzezeski** [nanomsg/nanomsg#371]
The interface lookup code assumes that each name-family pair has one unique interface, but that is not always the case. E.g. on my macbook the `lo0` interface listens on two ipv6 addresses: host local `::1`, and link local `fe80::1`. These are represented as two separate `struct ifaddrs` from `getifaddrs(3)`.

Here is a minimal reproducer:

```C
#include <assert.h>
#include <nanomsg/nn.h>
#include <nanomsg/reqrep.h>

void
main()
{
	int eid, optval = 0, rv, sock;

	sock = nn_socket(AF_SP, NN_REP);
	assert(sock != -1);
	rv = nn_setsockopt(sock, NN_SOL_SOCKET, NN_IPV4ONLY,
	    &optval, sizeof (optval));
	assert(rv != -1);
	eid = nn_bind(sock, "tcp://lo0:7777");
	assert(eid != -1);
}
```

```
$ ./multi-ipv6-fail
Assertion failed: !ipv6 (src/transports/utils/iface.c:88)
Abort trap: 6
```

**Comment by ricki** [comment]
Same issue here. In my case, `eth0` has three `AF_INET6` entries. A link local `fec0::/10`, a Teredo tunneling `2001::/32`, and the default unicast address, which should be preferred over the others acording to RFC 6724.

**Comment by gdamore** [comment]
So other systems (illumos) create a unique logical interface for each IP address.  Apparently mac does something different, allowing multiple IPs to be present.  I even see unicast 127.94.0.1 and 127.94.0.2 on my lo0 port on OSX 10.10.1!
