### ISSUE TITLE
Test 7 tcp_shutdown fails on Win7 64 (32bit build), MSVS 2012

### ISSUE THREAD

**Issue by ridler77** [nanomsg/nanomsg#373]
I downloaded latest master, ran the cmake commands to create the solution, and built Debug and Release versions.  Both Debug and Release crash when running the  Run Test project, test 7 tcp_shutdown.  Although, sometimes it just hangs.  Fails with call to nn_err_abort(), from usock_win.inc line 989.

**Comment by gdamore** [comment]
fixed in this:

commit ab699df74978645ebe5bb53f0b602ba4bf32ed4b
Author: Garrett D'Amore <garrett@damore.org>
Date:   Thu Oct 22 12:42:47 2015 -0700

    fixes #446 efd_win.inc global critical section should be mutex
    fixes #485 Windows efd_init should not assert on failure
    fixes #484 Make tcp_shutdown a little less likely to hang forever
    fixes #483 CMake tests hang forever
