### ISSUE TITLE
NN_RCVPRIO not being exported

### ISSUE THREAD

**Issue by nickdesaulniers** [nanomsg/nanomsg#374]
From https://github.com/nickdesaulniers/node-nanomsg/issues/50 we discovered that `NN_RCVPRIO` is not being exported in https://github.com/nanomsg/nanomsg/blob/master/src/core/symbol.c .

**Comment by nickdesaulniers** [comment]
I'm not sure if this symbol was left out on purpose or mistakenly?

**Comment by reqshark** [comment]
clarification: `NN_RCVPRIO` is definitely exported by the header file, just not retrieveable by `nn_symbol()` without merging #375
