### ISSUE TITLE
filtering on a pub/sub topic

### ISSUE THREAD

**Issue by nickdesaulniers** [nanomsg/nanomsg#381]
What am I doing wrong here?

test_case.c:
```c
// clang test_case.c -lnanomsg -o test_case && ./test_case
#include <pthread.h> // pthread_t, pthread_create, pthread_join
#include <stdio.h> // printf
#include <assert.h> // assert
#include <string.h> // strnlen, memset
#include <unistd.h> // usleep
#include "nanomsg/nn.h"
#include "nanomsg/pubsub.h"

// Shared memory
const char* addr = "tcp://127.0.0.1:7777";
//

void* publisher (void* data) {
  printf("hello from publisher thread\n");

  int sock = nn_socket(AF_SP, NN_PUB);
  assert(sock >= 0);

  assert(nn_bind(sock, addr) >= 0);

  const char* msg1 = "topic.A hello world";
  const char* msg2 = "topic.B goodbye world";

  while (1) {
    int bytes = nn_send(sock, msg1, strnlen(msg1, 200), 0);
    printf("sent: %s\n", msg1);
    bytes = nn_send(sock, msg2, strnlen(msg2, 200), 0);
    printf("sent: %s\n", msg2);
    /*usleep(10000); // 10ms*/
    sleep(1);
  }

  nn_shutdown(sock, 0);

  return NULL;
}

void* subscriber (void* data) {
  printf("hello from subscriber thread\n");

  int sock = nn_socket(AF_SP, NN_SUB);
  assert(sock >= 0);

  assert(nn_setsockopt(sock, NN_SUB, NN_SUB_SUBSCRIBE, "topic.A", 0) >= 0);
  assert(nn_connect(sock, addr) >= 0);

  char buf [200];
  while (1) {
    int bytes = nn_recv(sock, &buf, 200, 0);

    printf("received: %s\n", buf);
    /*nn_freemsg(&buf);*/
    memset(&buf, 0, 200);
  }

  nn_shutdown(sock, 0);

  return NULL;
}

int main () {
  pthread_t p, s;
  assert(pthread_create(&p, NULL, publisher, NULL) == 0);
  assert(pthread_create(&s, NULL, subscriber, NULL) == 0);
  assert(pthread_join(p, NULL) == 0);
  assert(pthread_join(s, NULL) == 0);
}

```

I would have expected the `topic.B` messages to get filtered out.  The [linked to getting started docs](http://tim.dysinger.net/posts/2013-09-16-getting-started-with-nanomsg.html) also seemed to be confused as to how this works.

```c
// TODO learn more about publishing/subscribe keys
assert (nn_setsockopt (sock, NN_SUB, NN_SUB_SUBSCRIBE, "", 0) >= 0);
```

https://github.com/nickdesaulniers/node-nanomsg/issues/51

**Comment by asafyish** [comment]
We also trying to use pub/sub and it seems to be inefficient - sending the message to all subscribers and doing the filtering on the *subscriber* side.
From http://nanomsg.org/v0.5/nn_pubsub.7.html
"Since the filtering is performed on the Subscriber side, all the messages from Publisher will be sent over the transport layer."
Obviously, this is not what we were expecting.

**Comment by reqshark** [comment]
this is unexpected because the subscription string is not being set correctly. instead go like this:

```c
assert(nn_setsockopt(sub, NN_SUB, NN_SUB_SUBSCRIBE, "topic.A", 7) >= 0);
```

**Comment by nickdesaulniers** [comment]
indeed, needs a `strlen(topic)`.  Thanks Bent!

**Comment by asafyish** [comment]
Does it mean that setsockopt in node-nanomsg is not working correctly ?
```js
Socket.prototype.setsockopt = function (level, option, value) {
    return this._protect(nn.Setsockopt(this.binding, level, option, value));
};
```

No length parameter...

**Comment by reqshark** [comment]
your length parameter is what `value` is. 

unfortunately it's a bit confusing in your code there because we're calling *the socket* `this.binding`, which corresponds with `sub` or `sock` in the code above

also lets move this discussion over to node-nanomsg, as it is no longer appropriate on libnanomsg.
