### ISSUE TITLE
Configure file not found

### ISSUE THREAD

**Issue by anshumang** [nanomsg/nanomsg#383]
I tried both the master branch and the last release (0.5-beta). In both, the configure file is missing. So the build and install steps from the README breaks !

**Comment by anshumang** [comment]
I added an autoreconf -i between 3 and 4.
.....
3. Go to the root directory of the package.
4. ./configure
......

**Comment by reqshark** [comment]
try `./autogen.sh` first before `./configure`

**Comment by anshumang** [comment]
Yes @reqshark I ran autoreconf to generate the configure script. I raised this issue because the README doesn't mention this.

**Comment by reqshark** [comment]
oh right, well i think maybe that's because it's different for windows, those system need `cmake`?

**Comment by anshumang** [comment]
There's a separate 'Build it on Windows' section..

**Comment by reqshark** [comment]
ok ya, you're definitely right. @anshumang, send a PR to fix it!

**Comment by anshumang** [comment]
@reqshark  PR submitted ! Closing the issue...
