### ISSUE TITLE
loop prevention code missing

### ISSUE THREAD

**Issue by gdamore** [nanomsg/nanomsg#386]
Apparently, although the RFC specifies that the maximum number of hops that should be permissible for REQ/REP is 8, I can find no evidence in the code of any actual enforcement of that.  There should be an NN_SOL_SOCKET option for this, default value set to 8, perhaps NN_SOL_TTL, and XREP sockets (and in the future XRESPONDENT) should discard messages that have more than this many 32-bit words in their header.

**Comment by wirebirdlabs** [comment]
@gdamore, can you provide a test case for this? Additionally, a straightforward fix? If no, perhaps this case should be closed as "nice to have", perhaps re-opened later based on public interest.

Personally, I'm willing to swallow this failure mode as an easily-detectable and debuggable application-layer failure that the library just does not yet protect against.

**Comment by gdamore** [comment]
Yes, I can. I've done this in mangos, I just haven't got around to it.  Other more critical bugs keep killing me.

That said, I consider fixing this pretty critical.  Its possible (too easy!) to build devices that can have infinite forwarding loops in them, causing crashes, etc.

The STAR protocol (not included in nanomsg, its a mangos protocol) actually *really* needs this, since otherwise you can accidentally have forwarding loops really far too easily.  Short of implementing a spanning tree type thing, this is needed.

So no, I won't be closing this until I fix it.  I do plan to fix it.

**Comment by reqshark** [comment]
NN_SOL_HOPS

But use case sounds like a TCP option, so please also consider naming like NN_TCP_HOPS option

**Comment by gdamore** [comment]
No.  It's not a TCP specific thing.  It's a protocol not transport option. Will probably go with NN_SOL_TTL or somesuch.

**Comment by reqshark** [comment]
right, it could impact any other wire transport

since it's hard for me to see the option being applied to `inproc` or `ipc`, how do you draw a clear line between protocol and transport?

**Comment by gdamore** [comment]
It could impact IPC or inproc just fine. 

I can build a device using two inprocs that forward to each other.  This change would prevent that.
