### ISSUE TITLE
surveyor protocol broken - no backtrace

### ISSUE THREAD

**Issue by gdamore** [nanomsg/nanomsg#387]
Due to the lack of a backtrace, it is impossible to connect multiple surveyors to a single respondent, because we would not know where to route responses.   This makes it impossible to set up devices using these sockets, and it also prevents perfectly reasonable topologies where a single responder may want to support multiple surveyors.   (Example use case for that: a printer that supports multiple print servers -- which may be acting in an HA capacity.)  In fact, I think it would be reasonable and possible to build up various voting / consensus algorithms using multiple respondents and multiple surveyors, if the protocol is fixed.

I've proposed using a backtrace just like REQ/REP, but since we're breaking the wire format, I'm bumping the protocol numbers up slightly.  I'm not going to bother doing this for the websocket transport since I think that transport is so brand-spanking new that I don't think there are conflicting cases in deployment yet.

**Comment by wirebirdlabs** [comment]
> "not going to bother doing this for the websocket transport since I think that transport is so brand-spanking new that I don't think there are conflicting cases in deployment yet"

Agree.
