### ISSUE TITLE
NN_POLLIN and NN_POLLOUT missed in nn_symbol

### ISSUE THREAD

**Issue by romanoved** [nanomsg/nanomsg#393]
but, maybe, there's a reason to skip this symbols?

**Comment by gdamore** [comment]
I'm not aware of any reason.  (Frankly I never use nn_symbol, not even sure what the use case for it really is.)

**Comment by romanoved** [comment]
Ok. But my question was not so clear, sorry. The point is that these constants are no suitable NN_NS_ * namespace (required for nn_symbol_info). Should I define something like NN_NS_POLL for this?

**Comment by djc** [comment]
@gdamore the use case for `nn_symbol()` is for language bindings, I think. Can't remember the exact way it helps right now, though...

**Comment by anbhole** [comment]
faced the same problem implementing nn_poll using JNI. would +1 for it.

**Comment by gdamore** [comment]
If someone would take a quick look at my proposed solution -- I hope it will work.

**Comment by romanoved** [comment]
Yes, it works as expected.

**Comment by gdamore** [comment]
Thanks.  I will merge soon then.
