### ISSUE TITLE
tcp_shutdown & ipc_shutdown failures (Solaris/illumos)

### ISSUE THREAD

**Issue by gdamore** [nanomsg/nanomsg#394]
I've seen both of these fail.  The problem, I've root caused, is that these things get SIGPIPE when we close the underlying socket while another thread is writing to it, but we've never appropriately handled SIGPIPE.  For systems with MSG_NOSIGNAL or SO_NOSIGPIPE, this is suppressed by the kernel.  But illumos / Solaris lack those, and so we have to have a signal handler.

Calling signal(SIGPIPE, SIG_IGN); early in main() for these programs solves it.

**Comment by wirebirdlabs** [comment]
Do you have ideas how to incorporate a fix into core? I have spent hours troubleshooting this issue, but without a good fix yet.

This is the most widespread outstanding bug in libnanomsg; many issues could be closed if this is resolved: #373, #368, #281, #269, #234, #75 -- that's just a handful of what I believe are all the same bug!

**Comment by gdamore** [comment]
I know how to fix the test suite.  Fixing the *framework*, not really easy.  I have a plan to fix the illumos kernel to add support for the missing functionality.  I just haven't got to it. 

But for systems that lack the ability to suppress or mask the SIGPIPE, the only real option is to have application programs set up a handler for it.

**Comment by gdamore** [comment]
Note that I think the current code is also buggy in that it fails on SMP systems because it changes things without holding a lock.

**Comment by reqshark** [comment]
are you serious?

> fix the illumos kernel 

that's awesome, just patch kernels when they doesn't work with our user-space software

**Comment by reqshark** [comment]
excuse me, nevermind you probably are going to patch that kernel, just checking out the who's who section on the illumos wiki: 

http://wiki.illumos.org/display/illumos/Garrett+D%27Amore

**Comment by gdamore** [comment]
The assertion failures are unrelated to the SIGPIPE errors, except that they both involve shutdown.  There are *two* problems here.  First is the SIGPIPE error.  The second is a race (I believe) that is exposed by some assertion failures.
