### ISSUE TITLE
support a generic non-peer socket type

### ISSUE THREAD

**Issue by reqshark** [nanomsg/nanomsg#397]
OK at this point, `ws://` is apparently toy-like, and [HTTP/2 is considered too new](https://github.com/nanomsg/nanomsg/issues/395) for consideration. 

Instead of implementing these specs on top of NN's SP Protocols, what about a blank TCP channel?

It'd be awesome to have a generic non-peer socket in libnanomsg!

This way you put that decision to meet higher level browser specs in the hands of the user.

Reasons (if you need them):
• A generic non-peer [has been supported by ZeroMQ for quite some time now](http://api.zeromq.org/4-2:zmq-socket#toc19)
• I think it's sort of unixy to put power of direct browser support in the hands of the library's end-user.

**Comment by gdamore** [comment]
To be honest, I see ~0 value in that.  If you want TCP... *just use TCP*.   If you can't, you most likely are in the browser, so you're stuck with websocket.

Furthermore, the complexity in libnanomsg itself is sufficiently high that I'd be loathe to try to pound it into a different use case.  The various state machines inside are already hard enough to follow...

**Comment by reqshark** [comment]
I think it'd be way easier than implementing the full `ws` type

**Comment by gdamore** [comment]
Yes, but *why?*

If you want vanilla TCP without any nanomsg semantics, just *use TCP*.  Creating a layer of syntactic sugar (lets be clear -- that's *all* it would be, at least from the client's perspect) seems to add ~0 value, and a bunch of extra headache.  That said, from the *implementation's* perspective, it would be a rather large amount of effort, since our internals aren't suited to this.

**Comment by wirebirdlabs** [comment]
This was explicitly considered and rejected during the ws:// transport design -- see https://github.com/nanomsg/nanomsg/commit/9d01de46251ad696f84414395832a28f5914056c (there is probably additional chatter and design decisions from this era on the list and/or GitHub comments/history)

Initially, I wanted libnanomsg to have the ability to communicate with an arbitrary, nanomsg-agnostic WebSocket peer (and for completeness, I guess this would also require a similar ability of the PAIR TCP socket to interoperate with an arbitrary TCP connection, and IPC, and...), but after hearing the reasoning from @sustrik and @gdamore et al. I now would agree it's best to not have this ability in core.

It's not a bad idea, just not in the spirit of core, and for this reason I'd recommend closing this case as `won't implement`. It might make a good auxiliary or extension library, but it's just not best suited for core.

**Comment by reqshark** [comment]
@wirebirdlabs makes sense to me too, especially after my conversation with @gdamore yesterday

**Comment by wirebirdlabs** [comment]
:-)
