### ISSUE TITLE
Would a pub-sub model work when part of nanomsg nodes cluster are behind different NAT/firewall?

### ISSUE THREAD

**Issue by FindNemo** [nanomsg/nanomsg#398]
"A" pub a msg "test_msg" using topic "test_topic", B sub a topic "test_topic" already. If A is behind NAT but B is not, or A is not but B is, then, will B reveive msg "test_msg"?

Thank you!

**Comment by zerotacg** [comment]
Nanomsg doesn't do techniques to hammer through NAT it's "just" to create a topology.
But you can decide the connecting side so if A is able to connect to B you can have B do the bind and A do the connect.

**Comment by gdamore** [comment]
Generally NAT rules depend on the NAT router.  nanomsg doesn't know or care about NAT.

That said, most NAT devices translate TCP properly, except that unless you set up a forwarding rule, you cannot initiate a connection (nn_connect) from outside the NAT to an address inside the NAT, although you can initiate from inside to the outside.

Be aware that which side does the nn_connect is orthogonal to the question of which side is publisher and subscriber.  (Although normally the subscriber does the connect, it can go the reverse.)

If you set up a forwarding rule in your NAT to expose the ports through, then this is all moot.

Anyway, this isn't a bug so I'm closing the issue.

**Comment by FindNemo** [comment]
I don't know how to usr irc, so i caome here.thanks a lot.
