### ISSUE TITLE
REQREP: multiple rep workers over IPC

### ISSUE THREAD

**Issue by kaixianghu** [nanomsg/nanomsg#399]
Hi

Does nanomsg support REQREP over IPC, where one uses multiple REP workers?

I have tried using multiple REP workers, and only one of those workers get receive any message.

Looking at issue:
https://github.com/nanomsg/nanomsg/issues/271

It looks like others also had similar issues with multiple REP workers over IPC, and it only worked over TCP.

Is this a known limitation?

**Comment by gdamore** [comment]
It should be possible to have multiple workers, but only one socket and only one endpoint can be bound to a specific address.  This is due to how IPC works (which is analogous to TCP in this sense.)

To further address, can you supply a sample code snippet exhibiting the problematic behavior?

**Comment by kaixianghu** [comment]
sorry, can you elaborate more on the requirement of one socket/ep bounding to a specific address?

if i want to use req/rep pattern to distribute workloads among multiple rep workers, should i not have each worker to bind and connect to the same address where req ep will send message to?

**Comment by gdamore** [comment]
Connect yes.  Bind no.

**Comment by kaixianghu** [comment]
maybe i am missing something, isn't rep endpoints workers? and they need to bind to the socket, whereas req endpoints are clients that connect to it?

**Comment by gdamore** [comment]
> On May 4, 2015, at 12:40 PM, Kai.H <notifications@github.com> wrote:
> 
> maybe i am missing something, isn't rep endpoints workers? and they need to bind to the socket, whereas req endpoints are clients that connect to it?
> 
> 

Each rep must have its own address or URL, if you are using bind.  (You can use connect() with rep, but that’s not common usage, counter-intuitive, and probably not what you want.)

So, the way you have multiple workers is that you have a client dial each worker.  You can dial multiple workers with a client, but each worker will have its own URL.  Something like this (pseudo-code):

Servers:

	nn_bind(s, myURL)

Clients:

	for (i = 0; i < nservers; i++) {
		nn_connect(s, serverUrl[i]);
	}

To be clear, each *server* (in bind context) cannot share the endpoint address with any other.  But clients may connect to many endpoints (provided this makes sense — which it does for REQ/REP, but not for some others — e.g. PAIR.)

The load balancing here is done by the client, not the server.

	- Garrett
