### ISSUE TITLE
Build fails under MSYS2, but libnanonmsg is compiled

### ISSUE THREAD

**Issue by killkrt** [nanomsg/nanomsg#400]
Hi,

I've a clean setup (under a VM) of Windows Home 64bit with MSYS2.
I've installed gcc 4.9.2 and libtool 2.4.6 (both using pacman).

Then I ran `autogen.sh` (without any error) and `configure --enable-nanocat=no --enable-symlinks=no --enable-tcpmuxd=no` (without any error), and then `make`.

Make gave me these errors:

```
  CC       perf/inproc_lat.o
  CCLD     perf/inproc_lat.exe
perf/.libs/lt-inproc_lat.c: In function 'main':
perf/.libs/lt-inproc_lat.c:319:3: warning: implicit declaration of function '_spawnv' [-Wimplicit-function-declaration]
   rval = (int) _spawnv (_P_WAIT, lt_argv_zero, (const char * const *) newargz);
   ^
/tmp/ccoZVc50.o: In function `main':
/home/KillKRT/nanomsg/perf/.libs/lt-inproc_lat.c:319: undefined reference to `_spawnv'
/home/KillKRT/nanomsg/perf/.libs/lt-inproc_lat.c:319:(.text.startup+0x4b9): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `_spawnv'
collect2: error: ld returned 1 exit status
strip: 'perf/inproc_lat.exe': No such file
...
```

End also similar errors for other _*lat.exe_ stuff.

But anyway at the end I was able to find in the folder ./libs/ the file `libnanomsg.a` and link it to my application (and it seems to work pretty well).

I guess the things that cannot compiled are tools/utilities maybe used for testing so it was good to have a `--enable` option to exclude from building or get the issue above fixed for MSYS.

Thank you.

**Comment by gdamore** [comment]
Is there a reason you're using autogen instead of cmake?

**Comment by killkrt** [comment]
Hi @gdamore ,

I'm creating a cross-platform project (that depends also on nanomsg) and I would like to keep my build process as simple as possibile, so in order to avoid putting *switches* in my CMakeLists.txt to manage OS X, Linux and Win in different way I would prefer to use the same approach for all the platforms. Since I've seen that nanomsg supports CMake build only for Windows, I've opt for using autogen for all the platforms.

Thanks.

**Comment by gdamore** [comment]
autogen is not supported on Windows for nanomsg.  For nanomsg, you need to build using CMake on Windows, or autogen & co on POSIX systems.

In particular, there are settings that are only applied (#defines) when using CMake, but which are absolutely mandatory for Windows.

Closing this... I'm not going to fix it.  (RTFM).
