### ISSUE TITLE
almost none of the connect failure modes are handled

### ISSUE THREAD

**Issue by krafczyk** [nanomsg/nanomsg#402]
Related to Issue #401, at line 407 of src/transports/ipc/bipc.c. (https://github.com/nanomsg/nanomsg/blob/master/src/transports/ipc/bipc.c#L407-408),

we can see that only a single failure mode of connect is handled.

**Comment by gdamore** [comment]
Agreed.  That code is needlessly fragile only handling ECONNREFUSED and ENOENT.

We should fix it.

**Comment by gdamore** [comment]
libnng is far more robust here.  Probably I should fix this in libnanomsg as well, I just am not terrifically motivated to at the moment.  I think its better to focus on stabilizing libnng so that we can retire libnanomsg.
