### ISSUE TITLE
nn_bind does not fail when port is already in use

### ISSUE THREAD

**Issue by lekv** [nanomsg/nanomsg#404]
I noticed that nn_bind seems to succeed even when the tcp port is already in use by another program/instance of my program. For my own code it happens with REQ/REP sockets, however it also seems to work with the local_thr/remote_thr test programs. You can start local_thr "tcp://*:5000" 256 256 twice. If you run remote_thr, it will first connect to the first instance, on the second run it will connect to the second instance.

For my own code I added explicit checks to nn_bind()'s return value to ensure it's not caused by disabled assertions in release builds.

Is this behavior expected?

This is the relevant code from my own program:
```cpp
    int network_socket = nn_socket( AF_SP_RAW, NN_REP );
    int ret = nn_bind( network_socket, "tcp://*:5000" );
    if ( ret < 0 )
    {
        std::cout << "Could not bind: " << nn_strerror( errno ) << std::endl;
    }
    else
    {
        std::cout << "Bind successful" << std::endl;
    }
    assert( ret >= 0 );
    (void)ret;
```

**Comment by vseryakov** [comment]
yes, this is expected, bind is done in the background and it will keep trying forever, no way right now to know if it failed or not, there was a proposal to export errno function for an endpoint but it never got through

**Comment by gdamore** [comment]
The errno proposal is outstanding, and is likely to be integrated with a few minor changes.

**Comment by gdamore** [comment]
I'm closing this for now; there are no code changes needed for this.
