### ISSUE TITLE
Customizing FIFO permissions

### ISSUE THREAD

**Issue by amosbird** [nanomsg/nanomsg#412]
Does nn_ipc support customizing FIFO permissions? It would be helpful to exchange data between different users.

**Comment by amosbird** [comment]
Ops. I misunderstood the ipc implementation. They seems to be Unix domain sockets. So is it possible to customize these sockets' permissions?

**Comment by gdamore** [comment]
You can do that by creating the node or using chmod on the file name after the fact.  There may be other ways too.

Right now there isn't a good way in libnanomsg to pass transport specific parameters.  We could add an option for it I guess?
