### ISSUE TITLE
Race condition?

### ISSUE THREAD

**Issue by mguijarr** [nanomsg/nanomsg#414]
Hi,

I am facing a kind of race condition with the surveyor scalability protocol, here is some code
(in Python) to demonstrate the problem:

#### File: test_respondent.py

    import nanomsg
    import select
    resp = nanomsg.Socket(nanomsg.RESPONDENT)
    resp.bind("tcp://*:6542")
    print 'waiting for respondent to be readable'
    select.select([resp.recv_fd],[],[])
    print 'receiving survey'
    print resp.recv(flags=nanomsg.DONTWAIT)
    print 'sending reply to surveyor'
    resp.send("reply")

#### File: test_surveyor.py

    import select
    import nanomsg
    s = nanomsg.Socket(nanomsg.SURVEYOR)
    s.connect("tcp://127.0.0.1:6542")
    print 'waiting for surveyor to be connected'
    select.select([s.send_fd],[],[])
    s.send("hello", nanomsg.DONTWAIT)
    print "waiting for surveyor to be readable"
    select.select([s.recv_fd],[],[])
    print 'receiving reply from respondent'
    print s.recv(flags=nanomsg.DONTWAIT)    

I run the test like this:

#### File: test.sh

    python test_respondent.py &
    python test_surveyor.py

Most of the time, it works perfectly. But sometimes, here is the error message I get:

    waiting for surveyor to be connected
    waiting for surveyor to be readable
    waiting for respondent to be readable
    receiving reply from respondent
    Traceback (most recent call last):
      File "test_surveyor.py", line 12, in <module>
        print s.recv(flags=nanomsg.DONTWAIT)
      File "/usr/local/lib/python2.7/dist-packages/nanomsg/__init__.py", line 329, in recv
    _nn_check_positive_rtn(rtn)
      File "/usr/local/lib/python2.7/dist-packages/nanomsg/__init__.py", line 63, in _nn_check_positive_rtn
        raise NanoMsgAPIError()
    nanomsg.NanoMsgAPIError: Operation cannot be performed in this state

It seems like a kind of race condition - or maybe I am doing something wrong ?
Any help would be appreciated.

**Comment by mguijarr** [comment]
Is it linked with PR #417 ?

**Comment by rodbzro** [comment]
Hi there, mguijarr.

This issue could be related to the same problem, yes.

**Comment by gdamore** [comment]
Yeah, looking at this code, it seems like the same problem.  Did you try the proposed PR to see if it solves your problem?  I'm thinking to merge that PR today if possible.

**Comment by gdamore** [comment]
That PR was merged.  I'm going to go ahead and close this - -the EFSM error was indeed valid as an indication of a survey timeout.  Now you'll get ETIMEDOUT the first time this occurs.  (If you call again subsequently, you'll get EFSM still.)
