### ISSUE TITLE
The survey.c of Tests can not use TCP.

### ISSUE THREAD

**Issue by bsanlang** [nanomsg/nanomsg#419]
I have modified the survey.c of Tests.
#define SOCKET_ADDRESS "inproc://test" to #define SOCKET_ADDRESS "tcp://127.0.0.1:8555"
I compiled the survey.c and run it. But test_recv (respondent1, "ABC") can not receive anything.
windows 8.1 win64 and vs2013.
How can I do?

**Comment by gdamore** [comment]
> On May 27, 2015, at 10:08 PM, bsanlang <notifications@github.com> wrote:
> 
> I have modified the survey.c 
> #define SOCKET_ADDRESS "inproc://test" to #define SOCKET_ADDRESS "127.0.0.1:8555"
> I compiled the survey.c of Tests and run it. But test_recv (respondent1, "ABC") can not receive anything.
> How can I do?
> 
> 
tcp://127.0.0.1:8555 <tcp://127.0.0.1:8555>

(note the leading “tcp://“)

	- Garrett

**Comment by bsanlang** [comment]
I have define SOCKET_ADDRESS "tcp://127.0.0.1:8555". But it can not receive anything.

**Comment by baxtersa** [comment]
TCP takes time for the connection to finish.  If you're not waiting long enough, you can start sending messages before anyone is fully connected, leading to dropped messages and the appearance that nanomsg is broken.  If you look at the tcp tests, they're littered with nn_sleep() calls after binds and connects before any send/receive calls.  Try sleeping for a couple hundred milliseconds after respondent3 connects and see if that fixes your issue, it did for me locally.

**Comment by bsanlang** [comment]
That's ok! Thank you baxtersa.

**Comment by gdamore** [comment]
This is TCP slow start.  I'm going to go ahead and close this issue -- the test works as defined with inproc, and probably inproc was chosen just to avoid this slow start problem.   If you're going to change this part of the code (the SOCKET_ADDRESS define) then you need to change *that* part too. :-)
