### ISSUE TITLE
thread.join() hangs forever if I use nanomsg in multithread program

### ISSUE THREAD

**Issue by henrywoo** [nanomsg/nanomsg#428]
I use nanomsg in my multithread program and it can send&receive msg without any issue. But at the end of my code, when I try to join my threads, the join function never returns. If I don't join them, I will get a segment fault core dump.

Can you give me an idea how to fix this? Is this a bug in nanomsg or I didn't use it correctly?

**Comment by henrywoo** [comment]
I am using c++11's thread.

**Comment by gdamore** [comment]
Most likely the problem is that worker code in libnanomsg does indeed fire up a thread, and that thread runs forever by default.  You can, I think, arrange to shut this all down by shutting down libnanomsg with nn_global_term().

**Comment by henrywoo** [comment]
Sorry I could not find this function

**Comment by henrywoo** [comment]
Problem solved. Thanks.
