### ISSUE TITLE
epoll compilation fails on SmartOS

### ISSUE THREAD

**Issue by dang0ld** [nanomsg/nanomsg#431]

**Comment by gdamore** [comment]
I'm not sure about on Linux, but epoll was recently added to SmartOS by Joyent.  Unfortunately, at least on illumos, you need to have sys/types.h included to avoid undefined types.  Including on Linux should be harmless given that sys/types.h is there, and is also mandated by POSIX.

I don't know of any platforms other than Linux and SmartOS, where epoll() is present.  (The SmartOS version emulates the Linux version - frankly using port events on Solaris systems would be far better.)
