### ISSUE TITLE
Get source address from tcp message

### ISSUE THREAD

**Issue by jaybny** [nanomsg/nanomsg#432]
Is there any way to get the source IP address, the one contained in the IP header? for tcp transports. ty

**Comment by gdamore** [comment]
Not yet.  Mangos (an alternative implementation in Go) can do this, but we lack the necessary tracking in libnanomsg.  Adding it is something I'd like to do at some point.

**Comment by jaybny** [comment]
damn.. sad to say, i need to move on from nanomsg... i need to launch in 40 days... have 1000s of line of code. cant believe mangos is leaving us behind.. maybe someone should write an alternate implementation of Mangos in C?

**Comment by gdamore** [comment]
That is actually what I have planned to do.  I just have to find time to get it done.

**Comment by gdamore** [comment]
(I figure such a project would take something on the order of 1-2 man weeks, for me (Garrett weeks?).  It may take another developer considerably longer if they don't come with my background in mangos and C.

**Comment by jaybny** [comment]
If you get it started, I can help..

**Comment by gdamore** [comment]
The cmsg API would help here.  What do you want to use the source IP address for?  Note that you cannot use it for outbound messaging because nanomsg doesn't let you select the IP address on a per message basis (neither does mangos, btw)

**Comment by kangjoni76** [comment]
very very +1

**Comment by kangjoni76** [comment]
@gdamore, I want to use it in the req/rep pattern, how it possible to implemented in cmsg API, I'm new to nanomsg but still need some hints here, to get source client ip?

**Comment by gdamore** [comment]
This is supported in the nng API now -- if this is functionality you need you should give that a shot.  (You have to use the native nng API, the compatibility API is insufficient to the task.)

**Comment by skyformat99** [comment]
very very +n

**Comment by gdamore** [comment]
Already this exists in nng in a much much easier to use API. It is really
unlikely that I will backport this to nanomsg. nng is wire compatible. I
need to focus on stabilizing that so it can used in production.

**Comment by gdamore** [comment]
I intend to close this will-not-fix for nanomsg.

**Comment by gdamore** [comment]
Closing this will-not-fix.  Please consider using nng if you need this functionality.
