### ISSUE TITLE
exposing nn_sleep() was a mistake

### ISSUE THREAD

**Issue by gdamore** [nanomsg/nanomsg#439]
For good reason, the nn_sleep function was not exported.  libnanomsg is not a general purpose utility library, and there are a bunch of other portability routines (nn_random, nn_stopwatch, etc.) that are also not exposed globally.

Furthermore, exposing this function was done incompletely, as it generated lots of linkage errors, which I tried to fix with #437  and #438  -- but which I failed at.  (I found the root cause, which is that the sleep.c was included directly into the test executables.)

Rather than have another go at fixng this (which I'm now sure I can do properly), I'm just going to back all this out.  Exposing this one function seems harmless enough, but its a very slipper slope as there are a lot of little portability utilities.

**Comment by wirebirdlabs** [comment]
I agree. The desire to use `nn_sleep()` at the application layer probably has a better solution elsewhere anyway.

One example of a potential use for `nn_sleep()` at the app layer is demonstrated in a few of the tests (e.g., https://github.com/nanomsg/nanomsg/blob/master/tests/tcp.c#L126-L127) to allow "enough time" to elapse for `nn_connect()` to connect ....

... however, this would better be suited by a new function such as `nn_connect_synchronous()`, which would block until it first successfully established a connection. Its interface would be identical to `nn_connect()`, except with an additional timeout parameter.

Users of this function would need to understand that when this function returns on success, downstream usage of the socket would not necessarily be "still connected" (e.g., same async semantics as currently would still apply).

Likewise, depending on how `nn_connect_synchronous()` returning ETIMEDOUT might properly establish connection the moment after returning, or this function could be designed such that it would cease trying to connect/reconnect on initial failure.

_tl;dr_ I support not exporting `nn_sleep()`, but instead perhaps considering API improvements where its use at the app layer might have been desirable
