### ISSUE TITLE
efd_win.inc global critical section should be mutex

### ISSUE THREAD

**Issue by pijyoi** [nanomsg/nanomsg#446]
Although the code creating the socketpair takes care to release the Event upon failure, it is still possible for the process to crash outside of the control of the library. 

This could cause the Event to be permanently held until all software using nanomsg blocking on the Event have been killed. A more robust way would be to use a Mutex which gets abandoned if the process crashes.

**Comment by zhaozg** [comment]
releate with https://github.com/nanomsg/nanomsg/issues/450 ?
