### ISSUE TITLE
tcp shutdown and close unstable

### ISSUE THREAD

**Issue by woodstock23** [nanomsg/nanomsg#463]
Recently I wrote a simple file transfer client and server for Windows and Linux, and experienced a lot of failed assertions within nanomsg, typically when closing sockets. The client and server communicate over separate threads, which also uses nanomsg. This communication keeps a connection (NN_PAIR) open and is very stable. Both client and server open another thread and socket for each file transfer request, and this has been very unstable, especially when transferring many small files.

I have experienced that it helped if I shutdown the endpoint before I close the socket. And it also helped if the sender waits for receiving a small message as acknowledgment that the receiver got the whole file. This made sure that the outgoing buffer was empty before closing the socket.

I tried to write a small reproducer, but this turned out to be very difficult. It became now some kind of tcp stress test, see below. Maybe you want to include it as tcp_stress.c in the test suite.

This stress test often fails on Windows and also sometimes on Linux. Mostly it fails with:
`Resource unavailable, try again [11] (nanomsg\tests\tcp_stress.c:111)`
and
`No buffer space available [119] (nanomsg\src\utils\efd_win.inc:191)`

But also sometimes with:
`Assertion failed: nn_fsm_isidle (self) (nanomsg\src\aio\fsm.c:112)`

For the test suite you may want to reduce TEST_LOOPS to 200, otherwise it takes very long.
Using PRINT_PORTS helps to see when the tests slows down or hangs.

```
#include "../src/nn.h"
#include "../src/pair.h"
#include "../src/tcp.h"

#include "testutil.h"
#include "../src/utils/attr.h"
#include "../src/utils/thread.c"

#include <time.h>

/*  Stress test the TCP transport. */

#define BUFFER_SIZE 1024
#define MESSAGES_PER_THREAD 1
#define TEST_LOOPS 2000
#define SOCKET_ADDRESS "tcp://127.0.0.1:12345"    /* port number offset needs to be in PORT_OFFSET  */
#define PORT_OFFSET 16

#undef PRINT_PORTS
#undef USE_SHUTDOWN
#define OVERLAPPING_THREADS

int bind_to_random_port (int s, char *addr, char *port)
{
    unsigned short p = 0u;
    int rc, i;

    i = 0;
    do {
        p = (unsigned short)(49152 + (rand() % 16384));
        port[0] = (char)('0' + p / 10000u);
        port[1] = (char)('0' + (p / 1000u) % 10u);
        port[2] = (char)('0' + (p / 100u) % 10u);
        port[3] = (char)('0' + (p / 10u) % 10u);
        port[4] = (char)('0' + p % 10u);

        rc = nn_bind (s, addr);
        nn_assert (rc >= 0 || nn_errno () == EADDRINUSE);
        nn_assert (++i < 20);
    } while (rc < 0);

#ifdef PRINT_PORTS
    if (i == 1)
      fprintf (stderr, "port %s\n", port);
    else
      fprintf (stderr, "port %s, %d tries\n", port, i);
#endif

    return rc;
}

static void routine (NN_UNUSED void *arg)
{
    int s, e;
    int i;
    void *msg;
    char *addr = (char*)arg;
    int timeout = 2000;

    s = test_socket (AF_SP, NN_PAIR);
    errno_assert(nn_setsockopt(s, NN_SOL_SOCKET, NN_SNDTIMEO, &timeout, sizeof(timeout)) == 0);
    e = test_connect (s, addr);

    for (i = 0; i < MESSAGES_PER_THREAD; ++i) {
        msg = nn_allocmsg(BUFFER_SIZE, 0);
        errno_assert (nn_send (s, &msg, NN_MSG, 0) == BUFFER_SIZE);
    }

    errno_assert (nn_send (s, "END", 3, 0) == 3);

#ifdef USE_SHUTDOWN
    errno_assert (nn_shutdown (s, e) == 0);
#endif
    test_close (s);
}

int main ()
{
    int s, e;
    void *buf;
    int rc;
    int i;
    int timeout = 2000;
    char addr1[] = SOCKET_ADDRESS;
    struct nn_thread thread1;
#ifdef OVERLAPPING_THREADS
    char addr2[] = SOCKET_ADDRESS;
    struct nn_thread thread2;
#endif

#if defined(SIGPIPE) && defined(SIG_IGN)
    signal (SIGPIPE, SIG_IGN);
#endif

    srand((unsigned int)time(NULL));

    for (i = 0; i < TEST_LOOPS; ++i) {

        s = test_socket (AF_SP, NN_PAIR);
        errno_assert (nn_setsockopt (s, NN_SOL_SOCKET, NN_RCVTIMEO, &timeout, sizeof(timeout)) == 0);
        e = bind_to_random_port (s, addr1, addr1 + PORT_OFFSET);

        nn_thread_init (&thread1, routine, addr1);

        do {
            rc = nn_recv (s, &buf, NN_MSG, 0);
            errno_assert (rc == BUFFER_SIZE || rc == 3);
            errno_assert (nn_freemsg (buf) == 0);
        } while (rc == BUFFER_SIZE);
        errno_assert (rc == 3);

#ifdef USE_SHUTDOWN
        errno_assert(nn_shutdown(s, e) == 0);
#endif
        test_close (s);

#ifdef OVERLAPPING_THREADS
        if (i != 0)
            nn_thread_term (&thread2);

        s = test_socket (AF_SP, NN_PAIR);
        errno_assert (nn_setsockopt (s, NN_SOL_SOCKET, NN_RCVTIMEO, &timeout, sizeof(timeout)) == 0);
        e = bind_to_random_port (s, addr2, addr2 + PORT_OFFSET);

        nn_thread_init (&thread2, routine, addr2);

        do {
            rc = nn_recv (s, &buf, NN_MSG, 0);
            errno_assert (rc == BUFFER_SIZE || rc == 3);
            errno_assert (nn_freemsg (buf) == 0);
        } while (rc == BUFFER_SIZE);
        errno_assert (rc == 3);

#ifdef USE_SHUTDOWN
        errno_assert (nn_shutdown (s, e) == 0);
#endif
        test_close (s);
#endif

        nn_thread_term (&thread1);
    }

#ifdef OVERLAPPING_THREADS
    nn_thread_term (&thread2);
#endif

    return 0;
}
```

**Comment by bnewbold** [comment]
I don't think this would address the core of your problem (`nn_fsm_isidle`), but did you try tuning the NN_*BUF and NN_LINGER parameters?

http://nanomsg.org/v0.6/nn_setsockopt.3.html

In particular, a longer LINGER might help with your socket shutdown and needing to send a confirmation. Your inclusion of a "finished' marker sounds more robust though.

**Comment by woodstock23** [comment]
Yes, thanks, I already tried up to 4MB NN_*BUF and up to 6 seconds NN_LINGER, but it is difficult to tell anything due to the intermittent crashes. My current workaround is stable enough, so I will wait with further tests for a version which survives the tcp_stress.

**Comment by baxtersa** [comment]
Would it be possible to get a backtrace on the `nn_fsm_isidle` assertion failure?  Is that the fsm of the tcp socket's retry timer?

**Comment by woodstock23** [comment]
I tried a bit, but was not able to reproduce this assertion failure today. Maybe it depends on the release build.

**Comment by rolandyoung** [comment]
I can reliably trigger an abort in nn_shutdown by running two instances of a server program, where one instance binds to a port and waits and the other instance tries to bind to the same port and then disconnects.

```c
#include <stdio.h>
#include <unistd.h>
#include "nn.h"
#include "pubsub.h"

int portclash(const char *url, int delay)
{
	int sock = nn_socket(AF_SP, NN_PUB);
	if (sock < 0)
	{
	    fprintf (stderr, "Failed to create nanomsg socket. Errno: %d\n", errno);
    	return 1;
	}
	int eid = nn_bind(sock, url);
	if (eid < 0)
	{
	    fprintf (stderr, "Failed to bind nanomsg socket to %s. Errno: %d\n", url, errno);
    	return 1;
	}
    printf ("Bound to %s, eid = %d\n", url, eid);

	usleep(delay * 1000);

	if (sock >= 0 && eid >= 0 && nn_shutdown(sock, eid) < 0)
	{
	    fprintf (stderr, "Failed to shut down nanomsg socket. Errno: %d\n", errno);
    	return 1;
	}	
    printf ("Finished OK\n");
    return 0;
}

int main(const int argc, const char **argv)
{
  if (argc == 2)
    return portclash(argv[1], 5000);
  else if (argc > 2)
    return portclash(argv[1], atoi(argv[2]));
  else
  {
    fprintf (stderr, "Usage: portclash url [delay_millis]\n");
    return 1;
  }
}
```
The program is run like this `portclash  tcp://*:7070 250`
If I start one copy of this program with the default delay of 5 sec and then start another on the same url with a delay of 250ms (say), the second will crash with the following traceback:
```
Program terminated with signal 6, Aborted.
#0  0x000000353f230265 in raise () from /lib64/libc.so.6
(gdb) where
#0  0x000000353f230265 in raise () from /lib64/libc.so.6
#1  0x000000353f231d10 in abort () from /lib64/libc.so.6
#2  0x00000000004073a9 in nn_err_abort () at src/utils/err.c:33
#3  0x0000000000405f54 in nn_timer_term (self=0x1b942ba8) at src/aio/timer.c:62
#4  0x0000000000413b91 in nn_btcp_destroy (self=<value optimized out>) at src/transports/tcp/btcp.c:205
#5  0x000000000040dde6 in nn_ep_term (self=0x1b9427a0) at src/core/ep.c:88
#6  0x0000000000405775 in nn_sock_handler (self=<value optimized out>, src=<value optimized out>, type=<value optimized out>,
    srcptr=<value optimized out>) at src/core/sock.c:927
#7  0x0000000000405976 in nn_ctx_leave (self=0x1b9425b8) at src/aio/ctx.c:63
#8  0x00000000004046e7 in nn_sock_rm_ep (self=0x1b942540, eid=1) at src/core/sock.c:533
#9  0x00000000004025e6 in nn_shutdown (s=<value optimized out>, how=<value optimized out>) at src/core/global.c:685
#10 0x0000000000401c8b in portclash (url=0x7fff1d0b6845 "tcp://*:7070", delay=250) at portclash.c:24
#11 0x0000000000401d33 in main (argc=3, argv=0x7fff1d0b5038) at portclash.c:38
```
My impression is that the retry timer associated with a btcp object is used for two purposes, only one of which is consistent with the assumption in nn_btcp_destroy that if the btcp state is IDLE then it is safe to call nn_backoff_term

**Comment by baxtersa** [comment]
You may want to cherry-pick the commits from open pull-request #410
<https://github.com/nanomsg/nanomsg/pull/410/commits>.  For whatever
reason, it is yet to be merged, but should address this crash.  We have it
cherry-picked into our fork and it is the correct fix for the issue.  Maybe
it got missed in the 0.6 beta release?

- Sam

**Comment by wirebirdlabs** [comment]
> For whatever reason, it is yet to be merged

Perhaps since the PR contains both a bugfix and a new feature? Both seem solid, quality work, but since coupled together makes it a bit harder for maintainers to evaluate/merge individually.

**Comment by baxtersa** [comment]
Yea, that could be it. It would be worth splitting up so that the bugfix
and feature can get merged if that's all it takes, this seems like a pretty
bad crash to have hanging around when we have a fix just sitting there. Is
that something I can take care of (even though they aren't my commits) or
something a maintainer (@gdamore?) needs to do?

On Mon, Sep 21, 2015 at 1:09 PM, Wirebird Labs LLC <notifications@github.com

**Comment by gdamore** [comment]
The discussion in the PR made me think that the problem wasn't completely
resolved.

That said, if there is just one bug fix, and that address the problem, then
please submit a separate minimal PR.  I don't like PRs with multiple bug
fixes in them because I can't tell what is fixed by what easily.

**Comment by rolandyoung** [comment]
Thanks @baxtersa for pointing out [#410](https://github.com/nanomsg/nanomsg/pull/410). As far as I can see, the [second](https://github.com/vseryakov/nanomsg/commit/713d1e645f88943eb9c31a64f2762f193883c734) and [third](https://github.com/vseryakov/nanomsg/commit/4ce2b9ea4bd2a71eb48d74f2211fc0903888cf2c) commits in that PR address the issue I encountered. I will try to confirm this and submit a minimal PR shortly.

This will not address any remaining problems with TCP support on Windows, but I agree that, as far as possible, a bug fix PR should address a single bug.

**Comment by rolandyoung** [comment]
See pull request #468

**Comment by gdamore** [comment]
PR# 468 was integrated; that doesn't necessarily completely solve all the TCP issues, but it helps with this one.  I'll open another issue for the other problem I'm seeing.
