### ISSUE TITLE
Is this compare operation atomic ?

### ISSUE THREAD

**Issue by cl20vv** [nanomsg/nanomsg#466]
src/utils/chunk.c:154
```c
146 void nn_chunk_free (void *p)
147 {   
148     struct nn_chunk *self;
149 
150     self = nn_chunk_getptr (p);
151 
152     /*  Decrement the reference count. Actual deallocation happens only if
153         it drops to zero. */
154     if (nn_atomic_dec (&self->refcount, 1) <= 1) {
155 
156         /*  Mark chunk as deallocated. */
157         nn_putl ((uint8_t*) (((uint32_t*) p) - 1), NN_CHUNK_TAG_DEALLOCATED);
158 
159         /*  Deallocate the resources held by the chunk. */
160         nn_atomic_term (&self->refcount);
161     
162         /*  Deallocate the memory block according to the allocation
163             mechanism specified. */
164         self->ffn (self);
165     }
166 }   
```

just assume when nn_atomic_dec() finished, and the return value is 1, before compareing to 1, some where else then calling nn_atomic_inc(), so now the value of self->refcount is 2, buf the if condition still comparing the 1 <= 1, so is here a bug, or I misunderstand it?

**Comment by zakharov** [comment]
Should be compare-and-swap operation instead.

**Comment by sustrik** [comment]
I don't think it needs to be atomic. If the reference count have already dropped to 1, there's nobody else out there who could increase it.

**Comment by gdamore** [comment]
Exactly -- if you are the only owner, then nobody else can get it.

**Comment by cl20vv** [comment]
Thanks, I'll read the code again for getting more info about who and when could increase it.
