### ISSUE TITLE
test inproc_thr not work.

### ISSUE THREAD

**Issue by zhaozg** [nanomsg/nanomsg#486]
On win10 pro 64bits, build with VS2015 RelWithDebInfo 32 bits configure.
inproc_thr.exe 100 100 will hang and no any output.

```
    [外部代码]  
    [下面的框架可能不正确和/或缺失，没有为 ntdll.dll 加载符号]    
>   nanomsg.dll!nn_efd_wait(nn_efd * self, int timeout) 行 69  C
    nanomsg.dll!nn_sock_recv(nn_sock * self, nn_msg * msg, int flags) 行 680   C
    nanomsg.dll!nn_recvmsg(int s, nn_msghdr * msghdr, int flags) 行 878    C
    nanomsg.dll!nn_recv(int s, void * buf, unsigned int len, int flags) 行 724 C
    inproc_thr.exe!main(int argc, char * * argv) 行 103    C
    [外部代码]  
```

https://github.com/nanomsg/nanomsg/issues/450

**Comment by gdamore** [comment]
I think this may be another case of #418 style inproc not being thread safe.

The test does run ok on my platform though.

**Comment by gdamore** [comment]
This is a dup #429  -- basically inproc isn't thread safe.

**Comment by gdamore** [comment]
This is a bug in the test program not in inproc.
