### ISSUE TITLE
incorrect includedir in generated libnanomsg.pc

### ISSUE THREAD

**Issue by sirudog** [nanomsg/nanomsg#487]
Hi,

I am using node-nanomsg (https://github.com/nickdesaulniers/node-nanomsg), and during installing it I try to dynamically link to libnanomsg (which I have already installed previously),
but I get an error telling me that the header files of libnanomsg cannot be found. I have checked what pkg-config tells about the include dir:
```
pkg-config libnanomsg --cflags-only-I | sed s/-I//g
```
OUTPUT:
```
/home/dev/Projects/nanomsg/nanomsg0.6-beta-gcc4.8/include
```
Which is incorrect, as the header files are copied into a subfolder named nanomsg during installing libnanomsg, so the correct path should be:
```
/home/dev/Projects/nanomsg/nanomsg0.6-beta-gcc4.8/include/nanomsg
```
I also verified this: when I change the includedir in libnanomsg.pc.in from 
```
includedir=@includedir@
```
to this
```
includedir=@includedir@/nanomsg
```
and I reinstall libnanomsg, I can install node-nanomsg module without errors.
Please verify this and if it looks OK, I can make a PR with this small change.
Thanks

**Comment by gdamore** [comment]
Yes, that looks correct.

**Comment by gdamore** [comment]
I'm not sure this was the right choice in retrospect, but I think its too late to fix it.  (I really think -I/usr/local/include -- or whatever -- is better, with applications including <nanomsg/nn.h> or whatever.)  Too late now though.

**Comment by gdamore** [comment]
Well, #561 reiterates what I just said.  Seems like the node package is *wrong* here, and we made a bad change to accommodate.  I'm going to research/inquire further, but I think we want to straighten this out prior to 1.0.
