### ISSUE TITLE
Websocket failure handling is incorrect

### ISSUE THREAD

**Issue by gdamore** [nanomsg/nanomsg#489]
The current code base is pretty careful to check and handle the various RFC 6455 requirements, which is a good thing.

However, what it does when it detects a failure is incorrect.

First off, it attempts to send a bogus frame to the peer, using a non-standard opcode of 0x7F.  This is in direct contravention to the RFC, which insists (rightfully so!) that in these Failed Websocket connection cases we should just drop the connection on the floor. 

Second, it *also* attempts to send a close handshake.  That's also wrong.  Same reason.

Finally, it also breaks the API contract with the nanomsg API consumer, by returning a zero length frame back to the user when the user calls recv().  This is wrong -- a zero length (no payload) frame is perfectly legal and meaningful, and we must not use this to indicate an error to the user.

In fact, nanomsg (quite intentionally) hides transport errors from the API user.  This helps make simpler consumers, because they don't have to do quite the same level of validation of the results from recv.  It also means that bad actors can't formulate garbage frames to trigger behavior in the application; their bad data just gets dropped on the floor.

The thing to do here is to just drop the connection with no notification back to the API consumer.

(Note that this is what mangos does.  It might be nice to have an event notification mechanism so that API consumers could see when connections or arrive, for any reason, not just for errors, but such an enhancement is another issue -- and I'm probably pretty unlikely to try to add one to the current libnanomsg library; adding this kind of functionality would best be done in a new implementation.)

**Comment by gdamore** [comment]
@wirebirdlabs please see this.  I am intending to fix this.  I discovered it while adding richer testing to the self tests for websocket compliance.

**Comment by reqshark** [comment]
so maybe it's not a bug in gecko? https://bugzilla.mozilla.org/show_bug.cgi?id=1216237

strange that we got it working w/ webkit..

btw are there any examples of how to implement this stuff a browser? here's what we did to get it to work on the node binding: https://github.com/nickdesaulniers/node-nanomsg/blob/master/examples/ws/index.html

**Comment by gdamore** [comment]
Well, I don't have enough context to see what the problem is there in gecko.  It is quite possible that if you're injecting bad protocol messages, the response from libnanomsg is going to be even less standards compliant.  And your application is probably going to be confused by a zero length frame.

I'll be adding more handling here shortly.

**Comment by gdamore** [comment]
More details of the work that led me to discover this (along with some other planned changes for websocket transport) in this PR: https://github.com/nanomsg/nanomsg/pull/490

**Comment by gdamore** [comment]
Note that PR#490 does *not* address *this* problem though.  Stay tuned for that.

**Comment by gdamore** [comment]
Well, going back and reading section 7.1.7 again, it does seem like we are supposed to make a reasonable effort at sending the CLOSE frame.  But the other frame is complete crap, and the zero length recv frame is even worse.

**Comment by wirebirdlabs** [comment]
Thank you for putting effort into this -- after the original contribution, we began a brief design review, which quickly fell to the back-burner as the library sat for a while. I am 100% open to criticism and improvement here :-)

> using a non-standard opcode of 0x7F

This concept idea probably ought to be blown away. We've talked here and there about this "close handshake" business, and I can concede that you're right that nanomsg should not implement it.

**Comment by wirebirdlabs** [comment]
> Well, going back and reading section 7.1.7 again, it does seem like we are supposed to make a reasonable effort at sending the CLOSE frame. But the other frame is complete crap, and the zero length recv frame is even worse.

This sounds right; more correct than the original post; based on memory.

**Comment by gdamore** [comment]
So, reading through the thing-- I was a little confused, and the code here was kind of badly wrong.

The 0x7F is never transmitted over the wire.  It only went to the user as the cmsg data.  Attached to that zero length frame!

Also the entire deferred state for STATE_FAILING appears to have been intended to facilitate delivery of that frame to the user.  Its actually more correct, and simpler, to send the CLOSE frame immediately, and stop the pipebase altogether, without waiting for the user to call recv().

I've implemented these changes, and tested them, as well as adding test cases (richer) to the ws.c test code.  PR coming momentarily.

**Comment by gdamore** [comment]
So this is PR#492.  https://github.com/nanomsg/nanomsg/pull/492

It is build on top #490 which addresses the other issues we discussed about the public API surrounding websockets.

(#490 adds a new socket option, NN_WS_MSG_TYPE, and uses that in either the cmsg data, or in the global socket options.  It eliminates the other public APIs exposing websocket specific send/recv methods, and the differently named but same valued NN_WS_HDR_OPCODE constant -- use NN_WS_MSG_TYPE instead.)

**Comment by wirebirdlabs** [comment]
> The 0x7F is never transmitted over the wire. It only went to the user as the cmsg data. Attached to that zero length frame!

OK, this is actually jiving better with my memory, but wasn't going to argue. I hope to have time soon to review your changes. :-)

**Comment by gdamore** [comment]
Well, I appear to have botched something in the handshake.  Actually, it looks like it might have also busted something in the previous #490, as we're setting timeouts in AppVeyor.
