### ISSUE TITLE
How to close a device without closing everything.

### ISSUE THREAD

**Issue by keshav105** [nanomsg/nanomsg#510]
We just want to close a device from main thread without closing everything. We have done some workaround for this behaviour, but just want to know if any other method is there to stop it.

**Comment by gdamore** [comment]
You have to close one of the sides of the device with nn_close().  That will cause nn_device() to return.

**Comment by keshav105** [comment]
What you have suggested  have tried already but it didnt work.
Please find the code below what i have used.


class NNHTest : public ::testing::Test
{
public:
    nn_helper_t proxy_st ;

};

struct info_my_param_t
{
    int       sock1;
    int	  sock2;
};

static void * loop_device_test( void* args )
{
	int rc;
	struct info_my_param_t * imp = (struct info_my_param_t *) args ;
	rc = nn_device ( imp->sock1, imp->sock2 );
      printf("value of nn_device rc = %d\n", rc);

	return NULL;
}

TEST_F(NNHTest, StopDeviceTest )
{
	int rc ,nnbd, con;
//device

    int sock1 = nn_socket ( AF_SP_RAW , NN_REP );
	printf("value of sock1 = %d\n", sock1);

	nnbd = nn_bind ( sock1 , "tcp://127.0.0.1:6699" );
	printf("value of nnbd = %d\n", nnbd);

	int sock2 = nn_socket ( AF_SP_RAW , NN_REQ );
	printf("value of sock2 = %d\n", sock2);

	con = nn_connect ( sock2 , "tcp://127.0.0.1:6799" );
	printf("value of con = %d\n", con);

//device loop start

	struct info_my_param_t imp ;
	imp.sock1 = sock1 ;
	imp.sock2 = sock2 ;
	struct info_my_param_t *ptr = (struct info_my_param_t *)memdup( (char*)&imp, sizeof(struct info_my_param_t) )  ;

	rc = pthread_create( &proxy_st.threadid, NULL, loop_device_test, ptr  );
	printf("value of pthread_create rc = %d\n", rc);
	sleep(1);

//closing sock1
	rc = nn_close(imp.sock1);
	printf("value of nn_close(imp.sock1) rc = %d\n", rc);

//closing sock2
	rc = nn_close(imp.sock2);
	printf("value of nn_close(imp.sock2) rc = %d\n", rc);

//joining main thread
	pthread_join( proxy_st.threadid, NULL);

}


OUTPUT:

keshav@keshav-Latitude-E6540:~/clone/BD/Test/Shared/Core$ ./ubuntuRelease64/test-static 
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from NNHTest
[ RUN      ] NNHTest.DeviceTestReqResp
value of sock1 = 0
value of nnbd = 1
value of sock2 = 1
value of con = 1
value of pthread_create rc = 0
value of nn_close(imp.sock1) rc = 0
value of nn_close(imp.sock2) rc = 0

Note : its hanging here
