### ISSUE TITLE
NN_QUEUE_NOTINQUEUE fix incomplete

### ISSUE THREAD

**Issue by gdamore** [nanomsg/nanomsg#528]
Just saw this on Travis:

Assertion failed: self->next == NN_QUEUE_NOTINQUEUE (../src/utils/queue.c:102)
/bin/bash: line 5: 13356 Aborted                 (core dumped) ${dir}$tst

Arrgh.  This was the ipc_shutdown test.

**Comment by gdamore** [comment]
Well, this seems hard to hit.  I'm several thousand invocations into this, and I can't seem to reproduce.  Aargh.

**Comment by wirebirdlabs** [comment]
Link to failure: https://travis-ci.org/nanomsg/nanomsg/jobs/91501857#L667

It's a stretch, but to help brainstorm: is it possible that https://github.com/nanomsg/nanomsg/blob/master/tests/ipc_shutdown.c#L82-L84 ignoring of the SIGPIPE error is now hurting us?

**Comment by gdamore** [comment]
I don't think so.  That signal shouldn't have been delivered on Linux ever because we are MSG_NOSIGNAL

**Comment by gdamore** [comment]
Wow.  I've been running this test in a while loop for *hours*, and haven't been able to reproduce it.

**Comment by wirebirdlabs** [comment]
> in a VM

Idea: drastically throttle the VM; 1 core, 1GB memory ... try to repro what are probably relatively "low resource" conditions on Travis.

**Comment by gdamore** [comment]
I think my vm is kind of constrained.

**Comment by gdamore** [comment]
I'm starting to think this might be related to #554 -- that is I think nn_term() races against the REQ/REP state machine for example.

**Comment by gdamore** [comment]
That said, ipc_stress uses PUB/SUB.

**Comment by JackDunaway** [comment]
Bump. This is continually failing in Travis CI -- here's the latest failure: https://travis-ci.org/nanomsg/nanomsg/jobs/123991735#L642

This bug should be bumped to one of the highest priorities, especially since it's still not well-understood what causes the issue.

**Comment by gdamore** [comment]
Yes, I need to spend time working on it again.  :-)  Trying to get the
other stuff stabilized first.

**Comment by gdamore** [comment]
I have a hope/theory that the changes I made today to make nn_close() and nn_term() more resilient may have fixed this.  Investigation pending -- lets keep an eye out for this failure since I've not seen it in quite a while now.

**Comment by gdamore** [comment]
This is at least a release stopper -- we need to find out if it still happens.

**Comment by gdamore** [comment]
Note that ipc_shutdown spins hard on the CPU in send.

**Comment by JackDunaway** [comment]
Just to keep a history, here's one recent such failure: https://travis-ci.org/nanomsg/nanomsg/jobs/129835988#L741

**Comment by gdamore** [comment]
Ok, time to figure this one out then.

**Comment by gdamore** [comment]
A brief note -- the queue data structure is totally unlocked.  We need to verify that these functions are only ever called with some higher level lock or exclusion in place.

**Comment by gdamore** [comment]
I think I might see the problem -- but question -- have we ever seen this on Windows?

**Comment by gdamore** [comment]
Basically, my theory is that we are calling either nn_worker_term() twice, or nn_fsm_stop() twice.  I don't think there are guards to ensure that these are idempotent.

**Comment by rbx** [comment]
We are observing `Assertion failed: self->next == NN_QUEUE_NOTINQUEUE (../src/utils/queue.c:102)` in some of our use cases when sending messages larger than 1MB (exactly => 1048577 bytes).

Using the supplied remote_thr/local_thr benchmarks, or our own benchmarks (pub/sub or push/pull) leads to either this assertion or hangs indefinitely or significantly decreased throughput (from tens of Gb/s to Kbs/s, followed by the assertion).

It does not seem to be related to shut down, because in the supplied benchmarks we inserted a longer sleep before starting any shutdown calls, due to #206.

**Comment by gdamore** [comment]
That's useful information.  Thanks.

**Comment by gdamore** [comment]
I saw a different error with local_perf/remote_perf when using ipc:

garrett@Triton{104}% ./local_thr ipc:///tmp/nperf 1048577 1000
Assertion failed: (nbytes == (int)sz), function main, file /Users/garrett/Projects/nanomsg/perf/local_thr.c, line 69.
Abort

**Comment by gdamore** [comment]
Can you tell me which transport you used, @rbx ?

**Comment by gdamore** [comment]
I understand what is happening.  And it is close related, but not for the reason you think.

The problem is that we have established a maximum receive size, and the performance tests don't set this.  The default is 1MB maximum message size.  This can be overridden by setting the NN_RCVMAXSIZE option -- and the performance utilities ought to do that.

What we may be seeing here though, is an interesting edge case where attempts to fail (disconnect) the receiving socket when attempting to read such a huge chunk trigger other problems. 

It could be fun to add a test that sets the rcvmaxsize to something small ... and then try to send modest messages.  The data should be dropped, but this would allow us to exercise/stress that code path in the library.

**Comment by rbx** [comment]
I was using TCP for these tests.

**Comment by gdamore** [comment]
I'm pretty sure this is happening when shutting down FSM state machines.

We cleanup "event" structures, and out of paranoia we make sure that the events are not actually enqueued anywhere.  This can happen at numerous places, and locating the precise race where it occurs is going to be difficult to know which state machine is getting shut down.  Fortunately the new backtrace code I've added should help with that.

Now as I think about this in more detail, probably what is happening is that some thread is sending fsm notifications to a state machine that is being shut down.  These may be arriving late.

I think the FSMs themselves are missing certain protections - in particular the fsm event publishers for nn_fsm_raise() and nn_fsm_raiseto() are run outside of the locks, and blithely enqueue events, with no regard as to checking whether the FSM is active or not.  Probably we need to insert just a little intelligence to detect a stopped event and in the case that it is stopped, decline to queue the event to the FSM.

**Comment by rbx** [comment]
After setting NN_RCVMAXSIZE to -1 I don't see any more hangs/assertions or (significant) throughput decrease.

Yes, it would make sense if the perf utilities set this option to the value of the provided msg size argument.
Thanks for quick response!

Just for my understanding, is it bad to have the value of this option at -1 by default?

**Comment by gdamore** [comment]
Yes. From a security perspective if the value is large or unlimited then it's trivial to perform a denial of service attack.

**Comment by gdamore** [comment]
Having spent a bunch of time in this; I'm convinced that the problem is more or less intractable to solve in the current architecture -- that is, events can get queued in messy ways, and adding "tests" to ensure that we don't queue an event "after" the appropriate time is difficult to say the least.

The reason for this is that the act of shutting down a state machine involves sending events, which is itself conflated with the individual "shutdown" actions of the various state machine users.

Having said that, looking very very carefully at the structure of all this, I believe that we can safely stop worrying about these.   The events themselves may get "abandoned" on a queue where they cannot be used, but these are generally all statically allocated, or allocated within larger contexts, such that the fact they are orphaned is ultimately quite harmless.

The simplest solution here is to simply remove the assertion check.  Admittedly that's not a very satisfying answer, since other queue consumers should be more careful.  But until we can fix or replace the FSM machinery, I cannot come up with a better solution.

Another, possibly better, solution is to conditionally remove the event item from any list it may be on, as part of the event termination process.

In fact, that's what I'm going to do.

**Comment by gdamore** [comment]
Well, scratch that.  It turns out that removing the item from the list its on is ... non-trivial.  This is because the FSM and CTX implementation don't share well.  Furthermore, attempts to replace the queue with a saner doubly linked list uncovered further problems, as data structures are copied blithely.  (You can't copy a list that uses a sentinel, since the sentinel address will change.)

So for now, nn_fsm_event_term() simply will not bother to do nn_queue_item_term().  This allows other queue consumers to get the benefit of the check, while eliminating the main problematic case here.
