### ISSUE TITLE
nn_reallocmsg(p, -1000) causes an access violation on Windows

### ISSUE THREAD

**Issue by zedalaye** [nanomsg/nanomsg#533]
Hello,

I finally managed how to build nanomsg with CMake and VisualStudio. I'm writing a Delphi (yes) wrapper for NanoMSG. To test it i'm also porting as much samples as I can. All went like a charm until I reached the project zerocopy line 101:

```c
    /*  Create message, make sure we handle overflow. */
    p = nn_allocmsg (100, 0);
    nn_assert (p);
    p2 = nn_reallocmsg (p, -1000);
    errno_assert (nn_errno () == ENOMEM);
    nn_assert (p2 == NULL);
```

The line p2 = nn_reallocmsg(p, -1000) causes an access violation, both in my Delphi test applicaton and in th zerocopy test application from nanomsg source tree.

Not sure if it can help but this is in the error log : 
```HEAP[zerocopy.exe]: Invalid allocation size - fffffc50 (exceeded 7ffdefff)```

**Comment by gdamore** [comment]
Wow.  That test code looks -- bogus.  -1 gets cast to an unsigned size_t, and yes, the result is an attempt to allocate a message that is far far too large.  I cannot imagine what this code was trying to do (I am no the original author).  Probably we should just reject attempts to realloc to values that are too big -- I'd argue arbitrarily that if the high order bit is set then its *too* big for sure.  (I.e. it started as a negative value.)

That said, I do see some effort to check for this in nn_chunk_realloc().  Unfortunately I think those checks may be busted.

**Comment by gdamore** [comment]
What version of windows are you using, as we don't see this fail in AppVeyor.

**Comment by zedalaye** [comment]
Windows 7 Professional (French, up to date but running in VirtualBox). nanomsg is built using Visual Studio 2013 Update 5 (and CMake 3.4.0)

**Comment by gdamore** [comment]
Weird.  I guess I don't see this on Windows Server 2012 R2, but I don't know why.

That said, both the test, and the guards for it in chunk.c, look kind of fishy.  I wouldn't worry *too* much about this; unless you do something stupid in your application to ask for negative sizes (or giant sizes > 2GB) you shouldn't see a problem.
