### ISSUE TITLE
Don't link nanocat, tcpmuxd against libanl

### ISSUE THREAD

**Issue by hlieberman** [nanomsg/nanomsg#545]
Neither nanocat nor tcpmuxd appear to actually use anything from libanl, but it is dynamically linked in anyway.

Is this because of some future need, or is this just a side-effect of the build system as its currently configured?

**Comment by gdamore** [comment]
I think it's a side effect.   I don't even know what that library is for.  (Linux isn't my preferred platform.)

**Comment by sustrik** [comment]
IIRC is it used for asynchronous DNS queries (getaddrinfo_a).

**Comment by gdamore** [comment]
Ah.   Ok.  Yeah doing name resolution is another thing that IMO was best left outside of the library. But whatever.

**Comment by gdamore** [comment]
This was a question, not really a bug.  I'm not going to worry about it -- if you don't like libanl, I think you need to configure nanomsg not to use async DNS lookups.
