### ISSUE TITLE
weird hang/crash & race against nn_term

### ISSUE THREAD

**Issue by gdamore** [nanomsg/nanomsg#554]
I think there is a problem with the req/rep state machines racing with nn_term.

https://ci.appveyor.com/project/gdamore/nanomsg/build/1.0.193/job/haswhuvgk3tv2lgr

I can't explain this crash, or hang, any other way; something doesn't add quite up.  The problem is seriously complicated to debug, due to the gazillion state machines involved. 

Interestingly enough, increasing the timeout for the connection request, which allows the TCP connections to be established properly, seems to clear this problem up.  (Its also relevant that this problem only was seen on Windows, which seems to require quite a bit longer for TCP to establish.)

**Comment by gdamore** [comment]
Increasing the timeout is not a complete fix apparently, as we've seen at least one failure (out of four builds). 

Its interesting that this seems worse when inproc is implicated.  Thread safety there?

**Comment by wirebirdlabs** [comment]
I'll mention again here on this thread (https://github.com/nanomsg/nanomsg/pull/520#issuecomment-156309833), I think that **implementing NN_LINGER and combining the concepts of "lingering" and "zombified" as the final state NN_LINGERING will appropriately resolve this issue**.

One of the keys is to keep send/recv operations as if the socket were still active while in this NN_LINGERING state, along the lines of: https://github.com/wirebirdlabs/featherweight-nanomsg/commit/79e41f6f9909849b33733873be0a4b102022d4d2

**Comment by gdamore** [comment]
LINGER probably shouldn't be used with nn_term().  Probably.  But definitely should be used with nn_close().  (I'd like to see nn_term() shut everything down hard & fast.  Frankly, I think most applications should never use nn_term().  If I were redesigning the API, I would not even have offered it as an API; there's not much need for it, and apart from dealing with a couple of global arrays (modest memory size), there is nothing it really needs to do.

Conversely, nn_close() should be called by applications properly.

Actually, if I were designing this from the get go, nn_socket() would return a pointer, and we wouldn't need nn_term() at all, as there simply wouldn't *be* any global resources to free.

Now, having said all that, implementing NN_LINGER is a *non-trivial* task in the current code base.  The problem is that you now add some new states to pretty much *every* state machine in the entire code base, and you have to give time for each of those state machines to properly linger / drain.

Yet another case where the FSM centric design is lethal to maintainability.

I'll welcome someone to submit a PR that goes towards this, but at the moment I'm likely not to make such efforts in that direction myself.  Frankly, the effort of implementing NN_LINGER is probably roughly similar to the effort to a complete rewrite using a saner architecture, with some different API design goals.

**Comment by wirebirdlabs** [comment]
Fair enough about NN_LINGER.

That said ... I've been continually working in and around such shutdown problems, and I keep coming back to these lines: https://github.com/nanomsg/nanomsg/blob/master/src/core/global.c#L581-L586

The fact that the two `nn_sock_rele (sock); ` are called **outside** of the global lock rather than **inside**. It feels ... fishy. Especially without the hold counter being a true atomic counter.

Anecdotally, I'm having better results with those calls inside than out, but it's hard to say for sure, while also tracking down separate failure modes in the WebSocket transport.

Thoughts on this?

**Comment by gdamore** [comment]
I will take look at this.  I thought I was careful about the locks here.

**Comment by wirebirdlabs** [comment]
If a PR to kick off tests would help, lemme know; I'm at the keyboard, if you're not.

**Comment by gdamore** [comment]
Looking at the code, it looks like yeah, I probably screwed that up.  Go ahead and fire off a PR.

**Comment by gdamore** [comment]
I think I meant to have these be nn_global_sock_rele(), but in retrospect just moving the release of the global lock ought to be adequate.

**Comment by wirebirdlabs** [comment]
It might be a winner ... all CI environments passed this iteration ... time will tell after more runs. At least it feels a step in the right direction.

I hope to be submitting a few more PR's today with WebSocket shutdown and testing improvements, and these should kick off even more tests.

**Comment by wirebirdlabs** [comment]
> I hope to be submitting a few more PR's today

Will not hit this before holiday; picking back up next week.

**Comment by gdamore** [comment]
It is now confirmed that this is *not* resolved by fixing #560.  This looks like some other problem.

**Comment by gdamore** [comment]
This problem does not seem to show up on Travis, but its very reproducible on AppVeyor.  Wonder if the number of underlying threads is part of the issue, or is it a difference in the notification behaviors we use for Windows vs. other platforms?

**Comment by gdamore** [comment]
So cautiously hopeful, but PR #562 looks quite promising.  Basically the problem is that in nn_term we didn't really shut things down properly, which caused bad stuff to happen.   I really don't like the nn_term() API at all, but if we're going to have it, we need to do a better job of making it work properly.

The solution was to enhance the state machines to properly handled the ZOMBIE state a bit better, and to clean up our end points in nn_term.  Stay tuned.

**Comment by gdamore** [comment]
Uhg.  There is an inherent race in the efd logic, and I cannot think of any clean way to solve it that doesn't involve changing the code utterly and completely.

Basically the problem is that poll() can hang indefinitely if you attempt to poll on a descriptor that is either closed, or has a far end closed.  So closing the descriptor can race against the call to poll in another thread, with the result that the logic can hang if the poll() calls arrives after the close().

We have no way to wake the thread blocked in poll.  We can't lock, because the lock is across the poll.

Sending a single message doesn't solve it either, because the that's edge triggered.  And I cannot think of any way to make a level-triggered mechanism on top of poll() that doesn't suffer from this inherent race.

What we really want is semantics sort of like condition variables, where a lock is atomically dropped while we wait.   I have no idea how to get those semantics across the user/kernel boundary, at least in anything resembling portable code.

What might work well here is to fire up a blocking thread that just sits in read().  Closing the far end descriptor (without closing the read side) results in a situation where read() always returns 0.  In other words, I think this would be race free.  Unfortunately I'm not sure how to make this work with timeouts; that is I'm not sure how to socket operations timeout when the eventfd has no data on it.

To be honest, *all* of these evils come from making the socket descriptors poll() and select() usable.  If not for that requirement, I could simply use ordinary synchronization primitives and be done with it.

It may be worth looking at separating the file descriptor used, so that I create the eventfd only when the user requests it with the options.  Alternatively, getting the eventfd logic *out* of the hot code path, so that we use condition variables and mutexes for our internal signaling instead, may be a substantial improvement.

Hmm... maybe if we didn't unsignal the socket...

**Comment by wirebirdlabs** [comment]
> To be honest, all of these evils come from making the socket descriptors poll() and select() usable. If not for that requirement, I could simply use ordinary synchronization primitives and be done with it.

Remove the feature.

Nobody spoke up when you asked who's using it on the mailing list.

The opportunity cost of keeping it in has become far too expensive. Once the library is solid, let's consider re-inclusion.

**Comment by gdamore** [comment]
The problem is that ~all the various language runtimes use it under the covers.  I can't remove without breaking pretty much ~everything.

**Comment by gdamore** [comment]
I *could* remove it on Windows, maybe.  But *only* on windows.

**Comment by wirebirdlabs** [comment]
OK, I may be on to something.

The tests that appear to continually fail are `ipc_shutdown`, `tcp_shutdown`, and `device7`: https://ci.appveyor.com/project/gdamore/nanomsg/build/0.8.251/job/ujpbvrpnno02a7xs#L1537

The red herring is when we say "fails only on Windows".

For instance, within my local dev environment in a Windows VM, these tests pass just fine.

The hot lead is this -- **the AppVeyor environment is likely the only build environment where we have a single core**.

On a hunch, I rebooted my local dev VM as a single core environment, and was able to repro the same test failures.

I don't think these failures are **only on Windows**, but rather, **only in single test environments**.

@gdamore, thoughts on this?

This *might* explain why we periodically see failures in Travis CI. The `STANDARD ` environment has "~2, bursted": https://docs.travis-ci.com/user/ci-environment/  (that said ... I think we've been in the `CONTAINER-BASED` environment, which has "2 cores" ... not "~2 cores")

Whereas AppVeyor explicitly has 1 core with the `Open-Source (Free)` environment: http://www.appveyor.com/docs/build-configuration

**Comment by wirebirdlabs** [comment]
> I don't think these failures are only on Windows, but rather, only in single test environments.

Missed a key word: "only in **single core** test environments"

**Comment by wirebirdlabs** [comment]
Aha! Not precisely true, that single-core environments are the culprit for explicit failure modes.

They just take a **stupidly** long time to produce correct behavior.

See: https://ci.appveyor.com/project/gdamore/nanomsg/build/0.8.254/job/u0anhr7wrpbre8jg#L1543

Associated with this "exorbitantly-generous" commit: https://github.com/wirebirdlabs/featherweight-nanomsg/commit/bbd46545327fa32adf10e47dd5d693b6813bd1db

**Comment by wirebirdlabs** [comment]
And that said... the one remaining failure is: https://ci.appveyor.com/project/gdamore/nanomsg/build/0.8.254/job/u0anhr7wrpbre8jg#L1585

@gdamore -- I'm still bent on the solution to this failure looking something like this: https://github.com/wirebirdlabs/featherweight-nanomsg/commit/79e41f6f9909849b33733873be0a4b102022d4d2

Where, it looks like you're ooching toward the same conclusion: https://github.com/nanomsg/nanomsg/pull/562/files#diff-213d12c67883313942a42887da10c6c2R1041

**Comment by gdamore** [comment]
Yep.  I hit other problems though.  I probably have to step away from this for a few days.  It's really too bad it's so difficult to regain context on this code after even a short time away...

**Comment by wirebirdlabs** [comment]
Legit.

re: https://github.com/nanomsg/nanomsg/issues/445
