### ISSUE TITLE
Support security attributes for Windows IPC

### ISSUE THREAD

**Issue by kostyay** [nanomsg/nanomsg#556]
In the following scenario:
- Service process runs as windows service or (as an elevated process), binds to a channel such as `ipc://test`
- Client process that runs as a weak user tries to connect to `ipc://test`, it will fail.

This is because when the named pipe is created by the parent process in `usock_win.inc:510` `NULL` is passed at the last parameter for lpSecurityAttributes. This causes the pipe to be created with the parent process permissions.

I can see that there are some TODOs there that mention this.
Any plans to fix that?

**Comment by gdamore** [comment]
There was a PR submitted for this #348.  I closed it as the author of it has stopped working on libnanomsg, and the code doesn't merge cleanly, and I am not enough of a Windows guy to take it on myself.  If you want to pick this work up, clean it up, and submit a new PR, I'd be happy to accept it.

In the meantime, I recommend you use TCP instead, if you can.

**Comment by kostyay** [comment]
Thanks, I will look at it.

And yeah, we switched to TCP for now.

**Comment by kostyay** [comment]
@gdamore here, take a look https://github.com/nanomsg/nanomsg/pull/557
