### ISSUE TITLE
includedir goes too deep

### ISSUE THREAD

**Issue by donpdonp** [nanomsg/nanomsg#561]
the includedir pkgconfig has /nanomsg in the path so #include <nanomsg/bus.h> is not found in include/nanomsg/nanomsg/bus.h

```
pkg-config --cflags libnanomsg
-I/opt/nanomsg/0.8-beta/include/nanomsg 
```

```
 go get github.com/op/go-nanomsg
# github.com/op/go-nanomsg
src/github.com/op/go-nanomsg/bus.go:5:26: fatal error: nanomsg/bus.h: No such file or directory
 // #include <nanomsg/bus.h>
                          ^
```

editing libnanomsg.pc.in to be
```
includedir=@includedir@
```
fixes the problem.

**Comment by gdamore** [comment]
This looks like the change issued with #487   Sadly I'm not sure what is correct right now... it seems like we have some disagreements about pkgconfig.  I don't actually use that tool.

**Comment by gdamore** [comment]
So it looks like your pkg-config flags for -I are wrong.  Don't say "include/nanomsg", but just "include".  Did you supply the -I option to pkg-config by hand?

**Comment by gdamore** [comment]
I'm closing this for now.  Feel free to reopen when you're prepared to provide more info.

**Comment by gdamore** [comment]
Huh.  In retrospect I think we got this wrong.  Applications should indeed include <nanomsg/nn.h> or whatever.
