### ISSUE TITLE
Advanced Survey Pattern / Graph UI

### ISSUE THREAD

**Issue by lucmichalski** [nanomsg/nanomsg#567]
Hi guys,

Hope you are all well !

I was wondering one thing with nanomsg. I would like to implement surveyor patterns by using an interface like that: https://github.com/marmelab/ArchitectureTree

The idea would be potentially using Etcd in order to get real time reconfiguration of the survey pattern.
(Like Vulcand the golang proxy for the backends and the frontends settings update)

Is it something that is possible ? Potential non intrusive or unstable for nanomsg ?

Cheers,
Luc Michalski

Cheers,
Luc Michalski

**Comment by gdamore** [comment]
So you'd have to implement various topology management bits in your application code.  So, this would represent the bulk of the effort.  This falls outside of the normal scope of nanomsg, which itself is just a framework.  I don't think its likely that anyone will be adding that to libnanomsg itself anytime soon, but someone could build an unbundled add-on that sits on top of libnanomsg.  Again, you'll need to figure out how to manage topologies dynamically, and you may need to actually hand code various router/dealer algorithms.
