### ISSUE TITLE
Cross-platform support for CMake builds

### ISSUE THREAD

**Issue by JackDunaway** [nanomsg/nanomsg#574]
This is a new open case for the continuation of #210, which was originally closed due to lack of contributions.

Here's a snapshot of work done toward fully supporting this feature request, nearly ready for a pull request: https://github.com/wirebirdlabs/featherweight-nanomsg/compare/pr-ws-mega-squash...wirebirdlabs:ftw-kernel

One blocker before creating this PR is merging #569; especially the CMakeLists.txt upgrade in https://github.com/wirebirdlabs/featherweight-nanomsg/commit/03f4dc2f29c8b1947f10f22898e3630221924fd1

The CMake script is currently passing on Windows environments in AppVeyor, and also the default Linux environment in Travis CI.

This patch aims to provide for CMake users the full capabilities of the current autotools toolchain. Those opting to switch from autotools to CMake are kindly requested to help suss out details or missing features.

Some high-level changes in this patch:

- platform-specific source files (e.g., `usock_win.h` versus `usock_posix.h`) are now conditionally included. This should provide a better developer experience within the IDE, when say, searching for a symbol
- ability to build static library with the configure option `NN_STATIC_LIB=ON`
- abitility to enable/disable nanocat build with `ENABLE_NANOCAT=ON`
- standardization of the `NN_HAVE` versus `NN_USE` nomenclature, both in source and in the configure script
- grouping of source files into a hierarchical folder structure in the IDE using CMake's `source_group` feature

The inclusion of this patch should not affect current autotools users, except I plan to makes minor upgrades to those script also to better conform to the `NN_HAVE` vs `NN_USE` definitions.

**Comment by gdamore** [comment]
I wonder if we could take this in *ahead* of the autobahn test work.  I think PR #596 still has some issues, and I hate to have other stuff get "stuck" behind that.

**Comment by gdamore** [comment]
I've not looked at the code you've changed yet,but I'm agreeable to ditching support for autotools.  

I'm gonna take in some of the changes in PR 596, the ones that aren't causing problems yet, just so we can make forward progress.

**Comment by ruipacheco** [comment]
While I can't contribute to the code I'd like to express my support for this change.

**Comment by gdamore** [comment]
I generally support the idea. But a switch to cmake will require an additional release before we can release 1.0.  That said I've been on a little break from coding for the holidays. 

I do want us to fix the functional bugs asap. There are some nasty issues outstanding to be fixed before 1.0.

**Comment by shiva** [comment]
I'd be glad to help out here. Is there a branch or repo that I can contribute to?

**Comment by Snaipe** [comment]
@shiva I'd say check out [wirebirdlabs' work on his CMake configuration](https://github.com/wirebirdlabs/featherweight-nanomsg/compare/pr-ws-mega-squash...wirebirdlabs:ftw-kernel#files_bucket) for a start. I based my own cmake work on it, it's a good start.

**Comment by shiva** [comment]
@Snaipe Thanks. Will do

**Comment by xor-gate** [comment]
Hi guys, i started working yesterday to already support linux for the CMake build system at PR #616 
With some effort this could easily be extended for *BSD (Free/Net/Dragonfly etcetera).

**Comment by gdamore** [comment]
@JackDunaway can you update this -- perhaps you have a PR ready?  Even if it's just a start, that is something we can work with.  (I think I've started CMake cross-platform as well -- so there are probably ~4 separate started efforts -- lets consolidate and get it integrated asap -- we can start by adding and once everything passes well everywhere, then gut the autotools crap.)

**Comment by JackDunaway** [comment]
Preparing this PR is my first priority.

**Comment by shiva** [comment]
@gdamore @JackDunaway Cool. I will drop my effort around this. This is going to make it much easier to convince folks within my company to use nanomsg in the future. Will to help get the PR done if I can help.

**Comment by gdamore** [comment]
Great.  Want to get this resolved soon.

**Comment by JackDunaway** [comment]
> make it much easier to convince folks within my company to use nanomsg in the future

Excellent!

> get this resolved soon

Same here ... overcoming the bit of inertia mentally spooling up on this topic again, but looking good ...

**Comment by xor-gate** [comment]
I will fully support your work 👍

**Comment by shiva** [comment]
@JackDunaway I was playing with ftw-kernel on featherweight-nanomsg, (https://github.com/JackDunaway/featherweight-nanomsg/commit/4bf526d863fac563a71522845a94e526ae8d9cce) and attempting to build using cmake. 

Is this the one we are trying to make the PR from? It has a couple of issues. (small issues with cmake_check_include, and undefined vars NN_PACKAGE_VERSION and NN_ABI_VERSION)

How do we want to get going on this? I can fork off your branch, and provide commits if that works.

**Comment by JackDunaway** [comment]
Hi @shiva -- I'm actually working on getting this into a PR for nanomsg as early as tomorrow (Saturday) -- in the meantime, feel free to make line-item comments either in that repository or here that might help. It's been private work to this point, but you'll see stuff start to show up publicly soon.

**Comment by shiva** [comment]
@JackDunaway sweet! will do so.

**Comment by shiva** [comment]
@JackDunaway  Found and fixed a few minor issues. See https://github.com/JackDunaway/featherweight-nanomsg/pull/1

**Comment by JackDunaway** [comment]
> Found and fixed a few minor issues

Discussion continued here: https://github.com/JackDunaway/featherweight-nanomsg/pull/1#issuecomment-210697309

We'll loop back to this issue once that wraps up.

**Comment by gdamore** [comment]
This was fixed here:

commit 5b34eb6467975ff4c444e2f8e1267bf01aba4b36
Author: Jack R. Dunaway <jack@wirebirdlabs.com>
Date:   Sat Apr 16 15:41:44 2016 -0500

    fixes #647 Initial cmake support for non-Windows platforms
    
    This change is the first step towards a unified CMake based build for
    all nanomsg platforms.  With this it is possible to build nanomsg
    using cmake on at least Linux, MacOS X, illumos, and Windows systems.
    However, there remains work to be done, particularly with respect to
    delivery of documentation and the nanocat binary.
    
    The eventual goal will be to remove support for the autotools, and
    settle on a single cmake based toolchain.
    
    This work is the result of a collaborative effort by several authors:
    Jack R. Dunaway (@JackDunaway), Garrett D'Amore (@gdamore),
    Franklin Mathieu (@Snaipe) and Shiva (@shiva).

**Comment by xor-gate** [comment]
Good work all 👍
