### ISSUE TITLE
recv returned due to timeout returns ETIMEDOUT, not EAGAIN

### ISSUE THREAD

**Issue by edw** [nanomsg/nanomsg#576]
The `nn_getsockopt` man page says:

> `NN_RCVTIMEO`
> The timeout for recv operation on the socket, in milliseconds. If message cannot be received within the specified timeout, `EAGAIN` error is returned. Negative value means infinite timeout. The type of the option is `int`. Default value is -1.

However, my code sees `errno()` returning 60 i.e. `ETIMEDOUT`. I haven't checked trying `send` with a timeout, but I would guess the same happens there. Is this a documentation issue or a behavior issue? I would suggest the former.

N.B. This is on OS X 10.11.2.

**Comment by gdamore** [comment]
There were changes here recently.  I'll look.  What version are you using ?

**Comment by edw** [comment]
My man pages say `0.7-beta`.

**Comment by gdamore** [comment]
Please try 0.8 if you can.

**Comment by edw** [comment]
That shouldn't be a problem.

**Comment by edw** [comment]
Hahaha! I'm updating the Homebrew formula and the build is hanging on `make -j1 check`.

**Comment by edw** [comment]
OK, that was an adventure. Anyway, the man page for `nn_recv` now lists `ETIMEDOUT`, and `nn_errno` returns `ETIMEDOUT`, but I would argue that the man page is misleading in that it says that types of sockets are free to define their own timeout mechanism, whereas the `nn_getsockopt` man page says that setting `NN_SNDTIMEO` or `NN_RCVTIMEO` to a non-negative setting will cause an `EAGAIN` error.

Also, according to the `nn_getsockopt ` man page,`NN_SNDTIMEO` and `NN_RCVTIMEO` seem to be defined for _all_ socket types, which is different than the `nn_recv` man page's position that timeouts are (exclusively) a socket-type specific concern.

**Comment by gdamore** [comment]
Sounds like nn_recv page needs updating.

**Comment by edw** [comment]
Also the `nn_getsockopt` man page, which erroneously says `EAGAIN` when it should say `ETIMEDOUT`.

**Comment by gdamore** [comment]
But you get ETIMEDOUT back right ?  I recall that is what it is supposed to do.  The difference here is subtle.   EAGAIN is returned when a non blocking operation fails because there is no data yet. (That is it would block.) n ETIMEDOUT is returned when a blocking operation times out.

**Comment by edw** [comment]
I'm using a blocking socket with a timeout. I get ETIMEDOUT as you say. The getsockopt man page says I should get AGAIN:

> NN_SNDTIMEO The timeout for send operation on the socket, in milliseconds. If message cannot be sent within the specified timeout, EAGAIN error is returned. Negative value means infinite timeout. The type of the option is int. Default value is -1.
