### ISSUE TITLE
ipc_shutdown test failure on Travis CI (src/aio/usock_posix.inc:461)

### ISSUE THREAD

**Issue by JackDunaway** [nanomsg/nanomsg#577]
Link to failure: https://travis-ci.org/nanomsg/nanomsg/jobs/96353847#L666

Message copied here for convenience:
```
Assertion failed: 8 == NN_USOCK_STATE_ACTIVE (../src/aio/usock_posix.inc:461)
/bin/bash: line 5: 13056 Aborted                 (core dumped) ${dir}$tst
FAIL: tests/ipc_shutdown
```

This is likely a "whack a mole" situation surfaced by: https://github.com/nanomsg/nanomsg/pull/564

*As a side note -- can we turn on `make check` option to output a call stack on core dump? That failure message is not very helpful.*

**Comment by gdamore** [comment]
This feels like another instance of the bug in #603

**Comment by gdamore** [comment]
Yes, this is #603.  Again, if this comes bac, in Travis at any point after today, please reopen.  Otherwise closing it.
