### ISSUE TITLE
WebSocket transport lagging features of TCP Transport

### ISSUE THREAD

**Issue by JackDunaway** [nanomsg/nanomsg#581]
The WebSocket transport is currently lagging features of the TCP transport, including reconnect backoff timers for both bind and connect, and also a socket receive maximum bytes option.

**Comment by reqshark** [comment]
on the browser-side of the connection, is there a way to configure nanomsg features?

**Comment by wirebirdlabs** [comment]
Would you explain?

**Comment by reqshark** [comment]
sure, let's say i set up an NN_PAIR or some other socket type. 

On the *browser-side*, setting no options, I'm actually able to get msgs into a web browser's JavaScript like this:

```js
      var ws = new WebSocket('ws://127.0.0.1:7789', [
      // see the rfc on sp websocket mapping:
      // raw.githubusercontent.com/nanomsg/nanomsg/master/rfc/sp-websocket-mapping-01.txt
        'pair.sp.nanomsg.org'
      ]);
      ws.onopen = function open() { ws.send('Ping'); }
      ws.onerror = function error(err) { console.log(err); }
      ws.onmessage = function message(e) {
        var reader = new FileReader();
        reader.addEventListener('loadend', function() {
          document.querySelector('span').textContent = reader.result;
        });
        reader.readAsText(e.data);
      }

```

Would any socket options I set on the other end *pass-through* or is there any plan to be able to set options from the browser-side? Does that make sense?

**Comment by reqshark** [comment]
btw, when i say "get msgs into a web browser's JavaScript " I also mean send msgs back! :+1:

**Comment by wirebirdlabs** [comment]
What kinds of options are you wanting to set?

**Comment by reqshark** [comment]
Really just `NN_RCVMAXSIZE`, for larger data sets or images bigger than 1024kB..

But at some point if `NN_SNDBUF` or `NN_RCVBUF` could improve perf I would want to set those

**Comment by wirebirdlabs** [comment]
That'd be a security hole for any transport type (not just WebSocket) -- enabling a socket peer to change behavior like this.

If you want to be able to tune those parameters remotely, you can introduce your own application-level protocol (but it doesn't seem like a good idea)

**Comment by reqshark** [comment]
Ok I could see that, thanks!
