### ISSUE TITLE
Buffer loss with nn_send using NN_REQ

### ISSUE THREAD

**Issue by raghavendrabond** [nanomsg/nanomsg#593]
When I used nn_send with NN_REQ, I am getting lesser buffer on nn_recv. There is no issue when NN_PAIR is used on both client and server.

Here is the code snippet 

    for (unsigned count = 1048576; count--;)
    {
        unsigned len = sz[p];
        nn_send(responder, buf, len, 0);
        bytes += len;
        p = (p+1) % (sizeof(sz)/sizeof(sz[0]));
    }
    nn_send(responder, buf, 0, 0);

Here is the result

sent 311022272 bytes
received 3856 bytes
elapsed=0.465

Whereas a similar code works using 0MQ (zmq_send) with ZMQ_SNDMORE. Is there something missing in the nanomsg interface or is this a bug with nanomsg for a multipart message?

**Comment by gdamore** [comment]
Unless this is a raw socket you can't do that with req.  each new message cancels the outstanding ones unless you first receive the reply.

**Comment by gdamore** [comment]
So this is an API usage error on the part of the submitter -- do nn_recv between the messages.  You simply cannot keep sending messages ad infinitum without acks for REQ/REP -- the framework drops them (as you've seen).

In other words, this is the behavior as designed and documented.  Closing.
