### ISSUE TITLE
nn_device() errors when dealing with messages larger than NN_RCVMAXSIZE

### ISSUE THREAD

**Issue by stepelu** [nanomsg/nanomsg#594]
Network scenario: 
- broker: nn_device() with 1 REP AF_SP_RAW (bind) and 1 REQ AF_SP_RAW (bind).
- worker: REP AF_SP connected to broker REQ
- client: REQ AF_SP connected to broker REP

The worker send a reply which is longer than NN_RCVMAXSIZE, the send succeds (ok) and the client never gets the reply (ok). The worker keeps getting the same task to perform (ok), but the second time it tries to send the too long reply, broker errors out with:

```
Resource unavailable, try again [11] (XXX\nanomsg-0.8-beta\src\devices\device.c:387)
```

Sometimes I get the same error in other occasions as well but it's a bit random, while the scenario above replicates the error consistently.

**Comment by stepelu** [comment]
This on Windows7/64, with nanomsg 0.8beta compiled for x86.

**Comment by gdamore** [comment]
This situation causes the transport to error out -- the device() code can be more resilient here, but we need to make sure that when the transport / pipe closes that it is restarted.  I think this is already properly handled but testing is required.

**Comment by gdamore** [comment]
We should write a test for this.  Submitter, can you retest with git head?

**Comment by gdamore** [comment]
Closing this due to lack of response from submitter.  It is now over a year since the last reply by the submitter.
