### ISSUE TITLE
tcp_disconnect results in nn_err_abort and frozen laptop

### ISSUE THREAD

**Issue by gwicksted** [nanomsg/nanomsg#598]
Fresh copy of repo w/ Latest commit f06749d  on Dec 2, 2015

1. Lenovo W520 Windows 7 x64 i7-2820QM 16GB w/ 2 SSDs via RDP
2. Ran `cmake .` - no errors
3. Opened the .sln in VS2015
4. Compiled the ALL_BUILD project - no errors
5. Compiled the RUN_TESTS project - ran into problem with tcp_shutdown (assertion)

Causes laptop to freeze to the point it needs to be power cycled.

1. Power cycled
2. Opened the .sln again
3. Ran just tcp_shutdown project in debug mode
4. Runs into the same assertion - this time I could break into the code long enough to view some variables and the stack

(restarted again, opened sln, placed a breakpoint on the printf above the assertion)

Now I can freely poke around but as soon as I stop the debugger it freezes again.

Function triggering the assertion:

```C
static void NN_UNUSED test_recv_impl (char *file, int line, int sock, char *data)

//...

    if (rc < 0) {
        fprintf (stderr, "Failed to recv: ........    "  // cut for brevity
        nn_err_abort ();  // here
    }
```

VS is showing the following values:
```
buf = 0x008973c8 (garbage string)
data = 0x0096b3a4 "hello"
data_len = 5
file = 0x0096b3ac (path to file on disk)
line 76
rc = -1
sock = 10
```

Some other tests passed:

```txt
  Test project D:/.../nanomsg
        Start  1: inproc
   1/40 Test  #1: inproc ...........................   Passed    0.58 sec
        Start  2: inproc_shutdown
   2/40 Test  #2: inproc_shutdown ..................   Passed    0.35 sec
        Start  3: ipc
   3/40 Test  #3: ipc ..............................   Passed    0.76 sec
        Start  4: ipc_shutdown
   4/40 Test  #4: ipc_shutdown .....................   Passed    0.46 sec
        Start  5: ipc_stress
   5/40 Test  #5: ipc_stress .......................   Passed    1.55 sec
        Start  6: tcp
   6/40 Test  #6: tcp ..............................   Passed    1.59 sec
        Start  7: tcp_shutdown
```

The freezing and abort happen reliably and this Laptop is not known to be flaky and lock up like this.

Please help!

**Comment by gwicksted** [comment]
Stack screenshot:

![image](https://cloud.githubusercontent.com/assets/2241626/12698650/6ce2c10c-c770-11e5-855e-c1ab47e720b3.png)

**Comment by gdamore** [comment]
Nanomsg is user space code.  If your kernel is freezing up then it is absolutely a fault in the hardware or operating system.  A user application or library should never ever be able to cause the system to completely hang.

**Comment by gwicksted** [comment]
Yes. I agree completely - just cloned ZMQ and it failed 2 tests before hanging the same way.

Odd that this has never happened before - I suppose the tests are stressing something just the right way.

Closing ticket.
