### ISSUE TITLE
crash if REP closes connection after sending protocol header

### ISSUE THREAD

**Issue by pts** [nanomsg/nanomsg#603]
Observed behavior: `nanocat --req` crashes if the REP endpoint closes the socket right after sending the 8-byte protocol header.

Expected behavior: `nanocat --req` should open a new connection and send the request again.

Environment: Ubuntu Trusty, Linux 3.13, nanomsg 0.8-beta. Happens to both `tcp://` and `ipc://` addresses.

How to reproduce:

```
$ rm -f faulty.sock && python -c 'if 1:
    import socket
    ssock = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM, 0)
    ssock.bind("faulty.sock")
    ssock.listen(16)
    while 1:
      sock, addr = ssock.accept()
      hdr = sock.recv(64)
      assert hdr == "\0SP\0\0000\0\0", repr(hdr)
      sock.sendall("\0SP\0\0001\0\0")
      sock.close()' &
$ while sleep .1; do nanocat --req --data d --connect ipc://faulty.sock; done
```

This makes `nanocat --req` abort with either of these error messages:
```
Unexpected source: state=5 source=1 action=5 (src/transports/utils/streamhdr.c:306)
Aborted (core dumped)
```
or:
```
Assertion failed: 7 == NN_USOCK_STATE_ACTIVE (src/aio/usock_posix.inc:420)
Aborted (core dumped)
```

The Python code above implements a custom REP server which closes the connection immediately after sending the correct 8-byte protocol header.

I can also reproduce the 2nd (NN_USOCK_STATE_ACTIVE) error message with `tcp://127.0.0.1:33221` (and a corresponding update to the REP server Python code).

**Comment by gdamore** [comment]
So looking at this, there are actually two errors.  I think the first error is really #568, and should not occur.

The second error is a separate issue, and trivially reproducible.  I'm working on it right now.
