### ISSUE TITLE
in-band message type incorrect in sp-ipc-mapping-01.txt 

### ISSUE THREAD

**Issue by pts** [nanomsg/nanomsg#604]
https://github.com/nanomsg/nanomsg/blob/master/rfc/sp-ipc-mapping-01.txt says that the in-band message type is 0, but for ipc:// sockets on Linux, with nanomsg 0.8-beta, actually the type 1 is sent over the wire.

**Comment by gdamore** [comment]
Yep, I ran into this a while ago when I was building mangos.  Thanks for the reminder.
