### ISSUE TITLE
timeout unit is wrong in tools/nanocat.c

### ISSUE THREAD

**Issue by pts** [nanomsg/nanomsg#605]
`tools/nanocat.c` says (incorrectly):
```
     "Socket Options", "SEC", "Set timeout for receiving a message"},
     "Socket Options", "SEC", "Set timeout for sending a message"},
```
But setting `--send-timeout 2000` actually sets to timeout to 2000 milliseconds rather than 2000 seconds.

Suggested fix: `SEC` -->  `MILLISEC` in `tools/nanocat.c`.

**Comment by gdamore** [comment]
Actually, some places it uses milliseconds, and others seconds.  We should use seconds to be consistent .. for the command line app we don't need sub-second timeouts.
