### ISSUE TITLE
Error "cannot find -lMswsock" when cross-compiling with mingw

### ISSUE THREAD

**Issue by chrisheller** [nanomsg/nanomsg#610]
configure.ac has a reference to the LIBS environment variable as LIBS="$LIBS -lws2_32 -lMswsock",  but that fails with a "cannot find -lMswsock" error message when cross-compiling. 

Changing that to a lower case m addresses the problem and then compiling works.  

I don't have a mingw on Windows environment handy at the moment to test if that change has any repercussions for building there though.  I can submit a pull request if someone can confirm that.

**Comment by gdamore** [comment]
I believe that in the past I had stated that nanomsg did not support mingw
compilation — there are problems with mingw as it lacks certain symbols
that are present on modern Windows but not in old Windows XP and earlier.
As a result, the mingw team has declined to add support for linking against
those symbols.

My answer to this is to require the use of Visual Studio to build on
Windows.  Since Visual Studio is free (as in beer) and using it does not
create any licensing restrictions on the resultant program, this doesn’t
seem a particularly onerous requirement.

As a result, I believe this bug should just be closed Will Not Fix.

**Comment by gdamore** [comment]
And yes, this also all means that cross compilation to Windows is not
supportable.

**Comment by Snaipe** [comment]
@gdamore from my tests nanomsg can be compiled with mingw-w64, which has better overall support for new windows functionalities. mingw can imho be dropped, but mingw-w64 should be supported.

**Comment by chrisheller** [comment]
Yes, mingw-w64 is what was being used.  That works for building both 32 bit and 64 bit versions of nanomsg. 

There was one error about nn_sleep not being defined when linking tcpmuxd though.  I think that it is some libtool related issue in our environment,  but hadn't spent much time in tracking that down. We just disabled building tcpmuxd since we aren't using it. 

@Snaipe did tcpmuxd build OK for you?

**Comment by Snaipe** [comment]
@chrisheller I'm using my own fork where I'm explicitely deactivating tests and utilities, but on the top on my head I don't remember having issues. What version are you compiling?

**Comment by gdamore** [comment]
I'll be removing the configure.ac nonsense and moving to cmake in the future.  For now I'm going to just close this, because until that time, mingw (even mingw-w64) is unsupported.  Microsoft compilers Just Work.

**Comment by reqshark** [comment]
Moving to CMAKE exclusively won't break compiling for iOS, will it?

**Comment by gdamore** [comment]
I don't think so.  See this for example, https://github.com/cristeab/ios-cmake

That said, if cmake is going to create an unsurmountable hurdle for iOS or Android (or any other platform really), I need to know ASAP.

**Comment by JackDunaway** [comment]
> Moving to CMAKE exclusively won't break compiling for iOS, will it?

I will be helping upgrade to the CMake build system, but I'm not tooled up to test iOS. Would you help validate it does go smoothly once we get it into mainline?

**Comment by gdamore** [comment]
In fact, I'm almost certain that CMake knows about iOS natively these days, see this for example:

https://blog.kitware.com/cmake-3-5-0-rc2-is-now-ready/

**Comment by reqshark** [comment]
> I will be helping upgrade to the CMake build system, but I'm not tooled up to test iOS. Would you help validate it does go smoothly once we get it into mainline?

Yes definitely, I'll be closely tracking that.

FWIW here's the current working shell script i use: https://gist.github.com/reqshark/20c38286d332f1bdf7605908f05c0b86 

> I'm almost certain that CMake knows about iOS natively these days

OK thanks guys, good to hear :)
