### ISSUE TITLE
Can nanomsg work with libevent?

### ISSUE THREAD

**Issue by Michael-Tieying-Zhang** [nanomsg/nanomsg#611]
I want to use libevent to do callback. I am not sure whether nanomsg's socket can work with libevent. Or Could you give me some suggestions how can I do callback. 

For example， after sending a message to the server， the client doesn't block to wait the response. On the contrary, the client returned and when the response comes back, the corresponding function should be invoked and process the response. 

This a typical callback scenario. How can I implement that using nanomsg?

**Comment by gdamore** [comment]
Probably you can use libevent.  libnanomsg uses a notification file descriptor which you can retrieve with either NN_SNDFD or NN_RCVFD socket options.  See nn_getsockopt.
