### ISSUE TITLE
Recommeded scalability protocols

### ISSUE THREAD

**Issue by lukepg** [nanomsg/nanomsg#613]
Hello,

  This is more of a question that an issue.

  I have looked at the scalability protocol descriptions but am uncertain which one implements my requirements. 

  Basically I am looking for a typical client/server situation with one server and multiple clients but with bi-directional communication. The PUBSUB looks like the closest protocol but I need the client to be able to send messages to the server (heartbeats, etc). Is this possible in the PUBSUB? If not what is the recommended solution?

Thanks,
Luke

**Comment by zerotacg** [comment]
PUBSUB is only unidirectional if you want to have a back channel you would need to add another socket. You could add another PUBSUB (client PUB, server SUB) and have the clients connect their PUB to the servers SUB.
Lots of cases you want to use TCP directly instead of scalability protocols.

**Comment by lukepg** [comment]
Ok, thank you very much for the response. By TCP do you mean without NanoMsg or TCP provided by a NanoMsg through a wrapper (if such thing exists)?

**Comment by zerotacg** [comment]
TCP without nanomsg as it does not expose the tcp socket for usage.

**Comment by gdamore** [comment]
Use multiple sockets. One pub sub for server broadcasts and a req/rep for client commands sent to server.

**Comment by lukepg** [comment]
Ok, thank you very much for the helpful responses.
