### ISSUE TITLE
nn_device() terminates process after a call to nn_term()

### ISSUE THREAD

**Issue by fertesta** [nanomsg/nanomsg#618]
NanoMSG Version: 0.8

The documentation of nn_device() states that “To break the loop and make nn_device function exit use nn_term(3) function.”. My presumed expected behaviour was that nn_device() would return an error code with nn_errno ETERM, to give a chance the program exit gracefully. So my signal handler calls `nn_term`, but the following message appears at stderr and the process terminates: 
``` 
^CSIGINT detected. Program quit...
Interrupted system call [4] (src/devices/device.c:303)
```
Looking at the code in `device.c:303`, an `errno_assert` is called after `poll`, which forces the library to terminate.

**Comment by gdamore** [comment]
Yep, that errno_assert needs to be removed.  The code immediately thereafter is *almost* correct.  Instead, we need to just bail out if rc < 0.  I'll have a fix for this shortly.

**Comment by gdamore** [comment]
I'm somewhat astonished that the tests never have tripped on this.  nn_poll in the device is supposed to stall and return ETERM.
