### ISSUE TITLE
Remove statistics socket

### ISSUE THREAD

**Issue by gdamore** [nanomsg/nanomsg#622]
The statistics socket support is experimental, and TBH, it adds complexity that is pointless.  Publishing this data over nanomsg itself, and the frequency of publishing, needs to be done by the app, not by the framework.  We just an API to retrieve statistics.

Furthermore, formatting this data in text form is incredibly inefficient, particularly the gmtime_r timestamping.   Far better to have this all in binary form and format the time at display time.

**Comment by JackDunaway** [comment]
This is a legitimate reason to remove a legitimate feature. It's not that the feature is useless or unused; it's that it's relative value, compared to the relative complexity/dependency it adds, combined with the fact that it would need more work to be more generally useful (e.g., tunable publishing period), makes it better to remove for now.

**Comment by gdamore** [comment]
Furthermore, I'm creating a much nicer API for retrieving statistics data programmatically. PR and bug for that coming *momentarily*.
