### ISSUE TITLE
Programmatic access to statistics desired

### ISSUE THREAD

**Issue by gdamore** [nanomsg/nanomsg#623]
We should expose statistics programmatically.

This means exposing all the NN_STAT_xxx defines (including the nn_symbol machinery, where we should declare NN_UNIT_COUNTER and NN_UNIT_MESSAGES to help.  (The COUNTER type indicates a stat that only increases, where as we can use UNIT_NONE for stats that represent a current level, such as NN_STAT_CURRENT_CONNECTIONS

One wrinkle in all this is that we need to expose a 64-bit integer type to applications.  I'm choosing to create NN_UINT64 for this purpose.  For now.  I'd really really rather use standard uint64_t -- but that might not exist everywhere. 

While here I've also cleaned up the symbol declarations to make them easier to read and maintain.

**Comment by xor-gate** [comment]
Looking good, I think people are in deep trouble when `uint64_t` is not defined nowadays...
