### ISSUE TITLE
Can nanomsg be intergrated with existing epoll server?

### ISSUE THREAD

**Issue by netxray** [nanomsg/nanomsg#630]
the problem i meet that was when epoll code existing, nanomsg nn_recv cannot receive any datas , 
if disable these epoll codes then nn_recv can normally receive data. 
Is there some compatibility issues? how to fix it? Thanks in advance!

**Comment by gdamore** [comment]
You can't epoll the nanomsg socket.  Instead you have to get either a send or receive notification file descriptor with nn_getsockopt() for the NN_SENDFD or NN_RECVFD.  See the nn_getsockopt man page for more details.

**Comment by netxray** [comment]
thanks! The problem has been resolved.
