### ISSUE TITLE
NN_EXPORT simplification

### ISSUE THREAD

**Issue by gdamore** [nanomsg/nanomsg#638]
For pretty much all systems except Windows (which of course is a special snowflake), NN_EXPORT can default to just "extern".  There is little value in hacks for  SunPro C  or GCC or CLANG, as the default visibility for extern symbols is external/global.  Furthermore, these defaults are specified by the C language standard, so lets be sane.

We cannot eliminate the __declspec() nonsense that Windows does, because Windows needs these to see symbols in the DLLs.  Sadly.

**Comment by JackDunaway** [comment]
Before working on a fix for this ... hang tight for #636, since it deals in part with this "special snowflake"

**Comment by JackDunaway** [comment]
Relevant commit: https://github.com/nanomsg/nanomsg/pull/636/commits/a15356b79e47e0c6ff48ba08e4dff538c7750844#diff-2051e1a7c073348e8ba0043ac9b5c77cL47

**Comment by Snaipe** [comment]
It might be worth noting that CMake can generate a header file appropriately defining NN_EXPORT for this: https://cmake.org/cmake/help/v2.8.7/cmake.html#module:GenerateExportHeader

**Comment by JackDunaway** [comment]
> CMake can generate a header file

I'm somewhat opposed to this, having looked into that feature myself in the past.

It's kinda neat, but it's also a little too "magical". This may simply be a personal view, but I prefer to draw the line of build generation system and source code at symbols -- where automatically generated new source code raises more questions than it provides answers.

Thoughts? Open for new suggestions, but I'd tend to lean against header file generation.

**Comment by gdamore** [comment]
I agree with you in this particular regard -- not that I have an objection to having generated headers -- but one good thing we'd give up is that right now there is only a single header that API consumers have to include -- nn.h.  Having multiple headers increases the ways that compilation of client programs can fail, since you might have to arrange for the correct include path to be set up.  If there were multiple things here to justify it I'd agree, but since its just this one item, the benefits don't seem to be worth the possible pains.

**Comment by gdamore** [comment]
Here's my proposal for simplifying this, which solves it for Windows, but uses extern for everything else.  It does leave open the opportunity to redefined it if a project needs to though:

```
+#if !defined(NN_EXPORT)
+#    if defined(_WIN32) && !defined(NN_STATIC_LIB)
+#        if defined NN_SHARED_LIB
+#            define NN_EXPORT __declspec(dllexport)
+#        else
+#            define NN_EXPORT __declspec(dllimport)
+#        endif
+#    else
+#        define NN_EXPORT extern
+#    endif
```
