### ISSUE TITLE
Warnings seen in AppVeyor build

### ISSUE THREAD

**Issue by gdamore** [nanomsg/nanomsg#639]
We should fix these... there are a number of warnings exposed in appveyr:

<pre>
"C:\projects\nanomsg\build\src\nanomsg.vcxproj" (default target) (4) ->
(ClCompile target) -> 
  C:\projects\nanomsg\src\core\global.c(176): warning C4101: 'addr': unreferenced local variable [C:\projects\nanomsg\build\src\nanomsg.vcxproj]
  c:\projects\nanomsg\src\aio\usock_win.inc(353): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data [C:\projects\nanomsg\build\src\nanomsg.vcxproj]
  c:\projects\nanomsg\src\aio\usock_win.inc(412): warning C4267: 'function': conversion from 'size_t' to 'DWORD', possible loss of data [C:\projects\nanomsg\build\src\nanomsg.vcxproj]
  c:\projects\nanomsg\src\aio\usock_win.inc(462): warning C4267: 'function': conversion from 'size_t' to 'DWORD', possible loss of data [C:\projects\nanomsg\build\src\nanomsg.vcxproj]
  C:\projects\nanomsg\src\utils\efd.c(67): warning C4244: 'initializing': conversion from 'SOCKET' to 'int', possible loss of data [C:\projects\nanomsg\build\src\nanomsg.vcxproj]
  C:\projects\nanomsg\src\transports\ws\cws.c(173): warning C4244: '=': conversion from '__int64' to 'int', possible loss of data [C:\projects\nanomsg\build\src\nanomsg.vcxproj]
  C:\projects\nanomsg\src\transports\ws\sws.c(580): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data [C:\projects\nanomsg\build\src\nanomsg.vcxproj]
  C:\projects\nanomsg\src\transports\ws\ws_handshake.c(489): warning C4267: '=': conversion from 'size_t' to 'unsigned int', possible loss of data [C:\projects\nanomsg\build\src\nanomsg.vcxproj]
  C:\projects\nanomsg\src\transports\ws\ws_handshake.c(668): warning C4267: '=': conversion from 'size_t' to 'unsigned int', possible loss of data [C:\projects\nanomsg\build\src\nanomsg.vcxproj]
 
 
"C:\projects\nanomsg\build\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\projects\nanomsg\build\ipc_stress.vcxproj" (default target) (24) ->
  C:\projects\nanomsg\tests\ipc_stress.c(83): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data [C:\projects\nanomsg\build\ipc_stress.vcxproj]
 
 
"C:\projects\nanomsg\build\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\projects\nanomsg\build\stats.vcxproj" (default target) (39) ->
  C:\projects\nanomsg\tests\stats.c(32): warning C4101: 'rc': unreferenced local variable [C:\projects\nanomsg\build\stats.vcxproj]
 
    11 Warning(s)
    0 Error(s)
</pre>

**Comment by JackDunaway** [comment]
I'll take a look at the four in WS and have a PR shortly ...

**Comment by JackDunaway** [comment]
OK, it'll take a bit longer to fix this properly and understand the ramifications of the fix.

Not because any of these particular fixes is difficult -- but because when I compile with Warning Level 3 `/W3` (the default warning level) it returns 0 warnings and 0 errors, and with `/W4` we get 225 warnings, and with `/Wall` that number shoots to 8930 warnings.

I'm not exactly sure yet how/why this AppVeyor environment is configured to return 11 warnings, but issues such as this are a little lower priority for the time being.

**Comment by gdamore** [comment]
Yeah sure.  I’ll fix some of these too, and we can gradually increase the
warning level. :-)

**Comment by gdamore** [comment]
This is all cleaned up now.  Closing.
