### ISSUE TITLE
nn_close should abort blocking calls on socket

### ISSUE THREAD

**Issue by op** [nanomsg/nanomsg#65]
If there is no timeout defined on a socket, and the socket is closed while another thread is waiting in nn_recv(), it would be very helpful for me to get an error back directly. Similar to how nn_term() works.

This reproduces the problem for me:
https://gist.github.com/op/5641440

**Comment by gdamore** [comment]
The semantic we want here is return EBADF for operations on a socket when nn_close() is called.

**Comment by gdamore** [comment]
Ok, I think I've got this nailed, stay tuned.  This solves other issues too!
