### ISSUE TITLE
Migrate AppVeyor to nanomsg organization

### ISSUE THREAD

**Issue by JackDunaway** [nanomsg/nanomsg#651]
Currently, the AppVeyor CI instance is hosted at: https://ci.appveyor.com/project/gdamore/nanomsg

This needs to be moved to: https://ci.appveyor.com/project/nanomsg/nanomsg

**Comment by gdamore** [comment]
Aside from editing the README, what else needs to be done here?

**Comment by JackDunaway** [comment]
Perhaps nothing further, to be honest.

Though, there's another issue we should consider that's related to this, and that's figuring a strategy for partitioning each of the CI builds based on environment.

For instance, Travis CI runs Ubuntu builds and OS X builds, yet has one badge on readme called "Linux". AppVeyor runs Win32 and x64, yet it's arguable even these should be separated into two badges.
