### ISSUE TITLE
Repeated connection resets

### ISSUE THREAD

**Issue by fertesta** [nanomsg/nanomsg#653]
My application consist of a server (A) that receives REQ from client (C) on 8880 and spawns a subrocess (S) to serve this request. Client C and server S work in a PUSH/PULL socket (port 11001 in the example below). Server A responds back with an "tcp://10.45.1.190:11001" indicating the address where the client should connect to receive the data. The REQ/REP between `C<->A` works smooth. However, both client C and subprocess S give up after a configured 60s with 'Connection timed out' when trying to `nn_recv()` and `nn_send()` respectively. 

An inspection with tcpdump on client side shows repeated attempts of SYN being sent from client and RST, ACK being sent back from server S (see below), until the timeout: 
```
81	3.489818	74	10.45.0.70	10.45.1.190	TCP	49416 → 11001 [SYN] Seq=0 Win=17922 Len=0 MSS=8961 SACK_PERM=1 TSval=2943705941 TSecr=0 WS=128	14059
82	3.490587	54	10.45.1.190	10.45.0.70	TCP	11001 → 49416 [RST, ACK] Seq=1 Ack=1 Win=0 Len=0	14113
```
Nanomsg Rev: 5b34eb6467975ff4c444e2f8e1267bf01aba4b36

**Comment by fertesta** [comment]
I forgot to mention that this happens sporadically.

**Comment by gdamore** [comment]
Libnanomsg is not fork-safe.  Work is in progress to address that.

**Comment by fertesta** [comment]
Thanks!

**Comment by gdamore** [comment]
However, if your subprocess calls *exec*, and you reinitialize the library, it should work.

**Comment by fertesta** [comment]
What do you mean my _reinitialize_ the library? A call to `nn_term()` in the child and create new sockets?

**Comment by Snaipe** [comment]
@fertesta No, you can't use any function from nanomsg before a call to exec() yet. You can use it normally after the call though.

**Comment by gdamore** [comment]
Exactly  .. after exec() you must do nn_init().

Don’t do *anything* in the fork()’d child prior to exec().

On Thu, Apr 21, 2016 at 10:10 AM, Franklin Mathieu <notifications@github.com

**Comment by gdamore** [comment]
I'm closing this as a dup of #582  - which is that we need to make this library fork-safe.
