### ISSUE TITLE
add performance testing to automated builds

### ISSUE THREAD

**Issue by JackDunaway** [nanomsg/nanomsg#664]
As @Snaipe [demonstrates here, long-running tests don't necessarily need to block or delay either the overall test result](https://github.com/nanomsg/nanomsg/pull/654#discussion_r60753252), or the quick feedback ASAP desirable for PR's.

I suggest we integrate all of the performance tests as part of at least a few CI environments. Even if the results are ignored in calculating overall test outcome, having a history of those statistics should be helpful.

Since performance is a stated feature, visibility into these statistics is important to track.

The only potential downside here -- assuming run-time performance of these CI environments is variable, dependent upon what resources have been provisioned to the environment by the service provider -- even assuming that from test to test in a single build, a shared CPU may be arbitrarily throttled -- the results themselves may be misinterpreted or meaningless. That said, the cost to begin performing this experiment is very low, so it's worth considering.

**Comment by gdamore** [comment]
At this point, I'm punting on this.  We don't have a baseline, and our CI providers don't really give us a meaningful way to create a baseline; watching the runtimes and test times manually (I do this alot with both AppVeyor and Travis) makes it clear that there is *immense* variability in the performance of the underlying VMs, to the point that we cannot possibly make any meaningful determinations about performance.
