### ISSUE TITLE
Better use of TCP options could improve performance

### ISSUE THREAD

**Issue by gdamore** [nanomsg/nanomsg#674]
If we want to achieve the best possible performance, there are a few things to consider.
1. We should disable Nagle by default (TCP_NODELAY)
2. We should probably use TCP_CORK for the cases where multiple send()s are required to complete the message (larger than MSS)
3. We should also look at disabling delayed ack (TCP_QUICKACK) -- TCP_QUICKACK is devastating to performance with smaller messages.

The handling of all these should be tunable, but I think the best defaults for a messaging system are to prefer latency over throughput -- so nagle and delayed ack both disabled, with select use of corking in the cases where we know there are multiple messages involved.

**Comment by JackDunaway** [comment]
> I think the best defaults for a messaging system are to prefer latency over throughput

Agree.

**Comment by gdamore** [comment]
Delayed ack is ok, just not with Nagle.

libnng disables Nagle by default.  I'll probably offer a method to turn it on.

We don't need to use TCP_CORK for those cases though, as we use writev to scatter gather (or WSASend which also has gather ability), so that's a non-issue.

Closing this as WILL-NOT-FIX for nanomsg.  For nng its *ALREADY* fixed.
