### ISSUE TITLE
Consider switching to FreeBSD coding style

### ISSUE THREAD

**Issue by gdamore** [nanomsg/nanomsg#680]
The nanomsg coding style is unique to nanomsg.  Its also fairly annoying in that those of us who work on other OSS code bases may struggle switching.  4 *space* indents are particularly annoying in the absence of good tooling.

So I'm hereby proposing to adopt the relevant parts of the FreeBSD coding style (the KNF parts).  The reason for this style is multifold.  Its one that I'm familiar with, it's very widely known, and there is excellent tool support for it.  I actually use the illumos style which is almost the same KNF.

The parts we wouldn't adopt are the parts relating to copyright blocks, pragma idents, and other intrinsically FreeBSD specific parts. The parts we would adopt are indention, line wrap, and other white space related issues.

This may seem like a small detail, but for someone who spends large amounts of time in the code, having a different coding style for this project is definitely an impediment.  And its an easy one to fix -- it can largely be done automatically via something like the indent program or emacs style plugin.

**Comment by shiva** [comment]
I use uncrustify to automate and fix formatting. 
http://uncrustify.sourceforge.net/

Whatever formatting you choose, there is going to be someone who doesn't like one thing or another. I'd recommend, automating it and making it part of the commit process. 

For example: https://github.com/shiva/fun/blob/d025d7a0455b493b310a8c023cabd3d8192b8e1b/git-commit-hooks/pre-commit-uncrustify

This way, the delta in the commit history doesn't have whitespace changes mixed with actual functional changes.

**Comment by gdamore** [comment]
Conceptually the idea of enforcement is sound.  I don't know if pre-commit-hooks are the right answer, but pre-push ones definitely are.  (The later we control everywhere, the former we do not.)

The first step is choosing a style.  One that can be applied mechanically is desirable.

**Comment by gdamore** [comment]
I'm closing this issue for now -- the current coding style has problems with it that make it "challenging" to apply a BSD style (especially 8 character tab stops) without refactoring to shorten variable and symbol names, and reducing indentation generally.
