### ISSUE TITLE
`stats` test fails sometimes under heavy load

### ISSUE THREAD

**Issue by JackDunaway** [nanomsg/nanomsg#691]
```
Test #33: stats ............................***Exception: Other  1.57 sec
Assertion failed: nn_get_statistic(rep1, NN_STAT_CURRENT_CONNECTIONS) == 0 (/Users/jack/repo/featherweight-nanomsg/tests/stats.c:91)
```

This is relatively repeatable with `ctest --output-on-failure --repeat-until-fail 25 . -j64`

**Comment by gdamore** [comment]
Is it always the same stat that fails ?  I wonder if we aren't waiting long enough for connections to establish.

**Comment by gdamore** [comment]
Hmm... we attempt to reconnect after 100 ms.  But we sleep only 200 ms, and we don't sleep between the bind and the connect.  Maybe inserting a short sleep there (as usual) would help -- at least until we get bind to be properly synchronous.

**Comment by JackDunaway** [comment]
> Is it always the same stat that fails

No -- I've seen it fail at least at https://github.com/nanomsg/nanomsg/blob/master/tests/stats.c#L45 also, which might need to be a separate issue, since they don't appear to be exactly the same root cause (unconfirmed)

**Comment by gdamore** [comment]
What platform are you testing on?  I've not seen it fail on MacOS X.  I suspect that both failures are related to load on the system and not waiting for the asynchronous bind to complete before trying the connect.

**Comment by JackDunaway** [comment]
Importantly, are you using the `-j64` flag from the original comment? This is most oftentimes what it takes to repro. `--repeat-until-fail 25` is also important

**Comment by gdamore** [comment]
Yes.  I used both on MacOS.  What platform are you testing on?

**Comment by gdamore** [comment]
Ok, this seems to be due to AppVeyor running under severe load (see #698).  Without -j4 this passes.  However, I think we should try to make the test a little more robust.  One way to do that is to ensure that we inject a sleep after the bind before the connect.  100 ms ought to be sufficient (on a reasonable system -- not AppVeyor with -j4 or higher).

**Comment by gdamore** [comment]
I'm pretty sure also that on AppVeyor we have problems where the TCP sockets are limited -- I suspect that this is a "non-issue" in terms of actual quality, and that we can close it.

In particular, we've not seen any more instances of this since we made other changes.
