### ISSUE TITLE
Consider removing nn_poll()

### ISSUE THREAD

**Issue by gdamore** [nanomsg/nanomsg#693]
nn_poll is a convenience function for creating apps that deal with multiple nanomsg sockets.  However, it doesn't integrate at all with operating system file descriptors or objects, and doesn't offer functionality that can't be obtained directly via NN_SNDFD and NN_RCVFD socket options.

Frankly, absent any known consumers, it may be something we can remove to reduce the footprint and maintenance burden.

**Comment by gdamore** [comment]
Marked this a release stopper -- we need to make a decision on this before 1.0.  Ideally before 0.9.

**Comment by keshav105** [comment]
Hello Garrett D'Amore,
we are using nn_poll API in our project so could you please guide how to use NN_SNDFD and NN_RCVFD socket options in place of nn_poll ??

**Comment by Snaipe** [comment]
@keshav105 both options return a pollable file descriptor. Just use it as you would with a normal socket (poll, epoll, ...)

**Comment by gdamore** [comment]
Actually, I've decided to leave this in place for now.  It turns out that people are using this, and we can pretty easily replace with better logic with a narrow wrapper later, when we have condvar based signaling and whole threads.

**Comment by keshav105** [comment]
Thank you. please let us know when you introduce the new wrapper for nn_poll , we are dependent on it.
