### ISSUE TITLE
Need expanded AppVeyor build environment matrix

### ISSUE THREAD

**Issue by JackDunaway** [nanomsg/nanomsg#719]
In order to demonstrate support of earliest officially supported Visual Studio environment:

`Visual Studio 10 2010`
and
`Visual Studio 10 2010 Win64`

In order to test MinGW-64 support, potentially with `allow_failures` set on this one:

`MSYS Makefiles`

In order to test building static libraries, we need at least one environment with the following:

`cmake -DNN_STATIC_LIB=ON ..`

**Comment by gdamore** [comment]
I'd like to avoid allow_failures for MinGW 64.  It either works, or it doesn't.

**Comment by gdamore** [comment]
I am considering deprecating VS 2010... We are at VS 2017 now, and 2012 and newer are "free".  (Modulo you have to pay for them if you are an "Enterprise".  Most developers can use it for free, and if an Enterprise isn't willing to buy a license... well, I'm not really interested in that.)

**Comment by gdamore** [comment]
So I spent a little time on this, and I've pretty much given up (for now) getting MinGW-W64 to build properly in AppVeyor.  I think I see the way forward, but it just isn't that important -- frankly with Visual Studio being free (as in beer) for almost everyone (except Enterprise users), there is little reason to worry about it.  (Libre toolsets is kinda not really important when the user is already running on and building for an inherently closed/proprietary platform like Windows.)

Having said that, I've updated to validate 2017 in both debug and release builds -- including getting the various cmake flags right (I finally understand why Visual Studio is a PITA on that platform -- everyone should just use NMakefiles and life would be better lol).

**Comment by gdamore** [comment]
After spending the better part of a day to resolve this, what I've learned is that the AppVeyor 2017 infrastructure doesn't support running our tests consistently.  I think they are probably using a different infrastructure, with different constraints.

At this point, I'm going to just punt on this.   If we are still supporting this library (and making changes to it) in a year or two, we might want to revisit -- but I fully expect to have moved all resources into nng by then.
