### ISSUE TITLE
Remove debian packaging metadata

### ISSUE THREAD

**Issue by gdamore** [nanomsg/nanomsg#721]
The debian packaging metadata is stale, and I'm not prepared to maintain it.  Furthermore, we don't know if it even builds properly.   We should just yank this out of the package; all the various packaging systems (and there are numerous ones) should not keep data there.  Instead we should use cpack for packaging these days.

**Comment by xor-gate** [comment]
CPack works great, it is very easy and reliable to build debian packages with it I use it in production.

**Comment by gdamore** [comment]
Yeah, I think I'm going to go ahead and remove the debian packaging then.
