### ISSUE TITLE
Rename COPYING to LICENSE

### ISSUE THREAD

**Issue by gdamore** [nanomsg/nanomsg#722]
The COPYING file needs to be renamed to LICENSE.  Also, it makes reference to "copyright notices", we should change that to reflect the membership list in the AUTHORS file.

We might want to consider having those folks who have specific copyright notices agree to a more generic blanket statement about "nanomsg authors", similar to what Go does.  This way we don't have to keep updating the source file, and we can just have a definitive list in the AUTHORS file of actual copyright holders.

**Comment by JackDunaway** [comment]
I agree (speaking for myself and business) to past/future contributions consolidated under a blanket copyright holder 'nanomsg authors' in the source files.

Would the license itself remain in all source files? Or would it be removed as the top block comment, replaced by a reference to this new `LICENSE`?

**Comment by gdamore** [comment]
It is short enough to leave the license text in place only changing the copyright statement.

**Comment by gdamore** [comment]
I'm declining to do this for now.  Github seems happy enough with COPYING.  We can rethink in nanomsg-next.  :-)
