### ISSUE TITLE
docs silently fail if asciidoctor is not present

### ISSUE THREAD

**Issue by JackDunaway** [nanomsg/nanomsg#725]
Currently, if `asciidoctor` is not present, the default behavior is to throw a warning. `NN_ENABLE_DOC` is a boolean option with two valid values: `ON` or `OFF`

I propose to add a third option, `DEFAULT`, which would inherit the current semantics of the current default `ON` -- a warning on failure.

The new `ON` would throw a fatal error if `asciidoctor` is not present.

The considerations here are:
- provide the same default behavior as current -- a best-effort try to build the docs ...
- ... yet provide a new option that will abort on error

The main reason is to alert CI to any such problems building the documentation, such as if/when something about `asciidoctor` is changed.

**Comment by gdamore** [comment]
I wonder if instead there is a way to turn CMake warnings into failures?

**Comment by gdamore** [comment]
The other thing we can do is put some extra validation in the CI script(s) for this.  TBH I don't want to needlessly complicate the CMake code if we can avoid it.  That stuff is brittle enough as it is.

**Comment by gdamore** [comment]
Right now, using Travis, I control fairly tightly the installation of asciidoctor.

I'm going to punt on this for now; changes here buy little value, and I'm more focused on the libnng project.
