### ISSUE TITLE
Explore using CPack to delivery binary packages

### ISSUE THREAD

**Issue by gdamore** [nanomsg/nanomsg#729]
We could deliver binary packages for:
- Debian
- MacOS X
- Windows

pretty easily using CPack.  Its not exactly clear to me how useful binary packages of a library like nanomsg are.   But if they are useful, we can do it.

**Comment by gdamore** [comment]
I'm pretty sure we should do this for Linux.  The problem is that Linux requires ldconfig to be run, and the CMake build doesn't do this automatically.  (Its not necessarily appropriate that it do so!)

**Comment by xor-gate** [comment]
It is nice to have deliverables for common used versions (E.g Debian 8), I use this in production to generate debian packages with CPack and works like a charm. If there is any help needed for debian I could assist but probably we would need some infrastructure (if we want this automaticly).

**Comment by gdamore** [comment]
Thanks.  Did you have to do anything specific or make any changes to the
CMakeLists to make packaging work for you?  I would appreciate any
information about how you do this that you can share, including e.g. cpack
arguments, etc.

**Comment by xor-gate** [comment]
You must first configure cpack with setting `CPACK_*` variables and *after* that load cpack with `include(CPack)`.

As example where I create a PHP module debian package:
https://github.com/xor-gate/cmake-by-example/blob/master/find-php/example/CMakeLists.txt#L23-L35

**Comment by gdamore** [comment]
I'm having mixed feelings about this.  Really as a library it would probably be best if developers just linked statically.

At any rate, I won't be changing this for nanomsg.  I'm open to thinking about it for libnng.

CLosing this one against nanomsg for now.
