### ISSUE TITLE
Looks like the 0mq

### ISSUE THREAD

**Issue by farell** [nanomsg/nanomsg#744]
What is the difference between nanomsg and 0mq?Their pattern seems alike,thanks

**Comment by gdamore** [comment]
They are similar having been created by the same author. The main differences are that nanomsg is written in pure C with a BSD socket-like API and is licensed under a liberal MIT license.  0MQ is C++ with its own incompatible API and GPL license. 

Nanomsg strives to be small and light weight. 0MQ tries to solve a lot more problems (eg security etc.) 

More detail is linked to from the documentation link on the main site.

**Comment by farell** [comment]
thanks a lot!
