### ISSUE TITLE
CMake may not find InitializeConditionVariable

### ISSUE THREAD

**Issue by Snaipe** [nanomsg/nanomsg#754]
It seems that on some environments, CMake with MinGW-w64 fails to find InitializeConditionVariable, even though the host supports it.

This seems to happen because the CMake distributed with MSYS2 lies when providing the WINNT version, which makes MinGW-w64 believe it's running on windows XP.

**Comment by gdamore** [comment]
If the symbol is not available then is this going to build anyway?  What happens if you remove the check?  Normal MinGW-w64 works fine in appveyor.

**Comment by Snaipe** [comment]
@gdamore The symbol is available, it's just ifdef'ed out because `_WIN32_WINNT` is defined to something lower than `0x600` by MSYS2's cmake.

It can be visible on appveyor itself when calling `C:\msys2\usr\bin\cmake` instead of `C:\Program Files (x86)\CMake\cmake.exe`.

**Comment by gdamore** [comment]
it sounds to me like the problem is cmake. it is lying about the environment and claiming to be XP.  a platform we dont support.
