### ISSUE TITLE
./configure syntax error with dash

### ISSUE THREAD

**Issue by etosan** [nanomsg/nanomsg#761]
With 1.0.0 rc #2 I am getting ./configure error on system where system sh binary is provided by dash.

```
mkdir build
cd build
../configure 
../configure: 76: ../configure: Syntax error: "(" unexpected
```

doing this with bash works fine:

```
mkdir build
cd build
bash ../configure 
-- The C compiler identification is GNU *.*.*
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
...
...
...
```

Is this error in dash?

**Comment by gdamore** [comment]
It looks like dash does not support array variables.  I will investigate.

**Comment by Snaipe** [comment]
iirc array variables are nonstandard, and dash was made to strictly comply to the POSIX shell specification without any extension

**Comment by gdamore** [comment]
Yes, I see that.  I’ll have this fixed shortly.

**Comment by etosan** [comment]
Just confirming, it now works on my dash based, and FreeBSD  systems. Great job. Thanks!
