### ISSUE TITLE
Used for IPC?

### ISSUE THREAD

**Issue by Dillybob92** [nanomsg/nanomsg#766]
Hey guys,

Just curious... I have 3 node processes and was curious if nanomsg would be good for IPC. I am using the processes for game instances for my Diablo 2 style game.  

When players join the load balancer they get put on a random node (to help scale nodejs) -- but when they move around in the game I need to send messages through IPC.  

I was wondering would Nanomsg be the right solution for this, or node-ipc? Would there ever be a bottleneck if using nanomsg? Thanks

**Comment by gdamore** [comment]
sounds like a good use case for nanomsg to me.

**Comment by Dillybob92** [comment]
@gdamore, thanks! I will give it a try then! I am curious if there is going to be any added latency when pub subbing between processes (when a player is a moving around) -- I know there is probably something, but I wonder if it's even negligible. And I saw some benchmarks and I don't think I will ever surpass the msgs per second nanomsg provides...

**Comment by gdamore** [comment]
pub / sub and any IPC adds latency.  We're talking about TCP transitions here so its probably on the order of hundreds of microseconds.  Whether that is "significant" latency depends on your app.  For chat and gaming (even video and voice) a few hundred mikes is not noticeable.  For high frequency trading it can be tragic.
