### ISSUE TITLE
Please correct the typo in the BUILD section

### ISSUE THREAD

**Issue by museghost** [nanomsg/nanomsg#770]
Hi Team

At first, I appreciate you and the team for releasing the nanomsg 1.0 finally.
I am a fan and user for the nanomsg for a long time since 0.2.x branch.  Also the library is running on my production environment successfully.

So, as a fan, when I try to compile the library in Windows with CMAKE, I found the typo in the BUILD section. I think it would be changed from "ctest -G Debug ." to "ctest -C Debug .".

Could you please update on this, if it is correct ?

Thank you for your continuous effort !

Best Regards

**Comment by gdamore** [comment]
Yeah, we will fix it.  Thanks for filing this.

**Comment by reqshark** [comment]
nice catch @museghost!

while `ctest -G Debug .` works only on unix, it seems `ctest -C Debug .` works on both platforms :)
