### ISSUE TITLE
reqttl test fail on osx

### ISSUE THREAD

**Issue by reqshark** [nanomsg/nanomsg#771]
confirmed on osx 10.11:  

```go
      Start 38: cmsg
38/42 Test #38: cmsg .............................   Passed    0.00 sec
      Start 39: bug328
39/42 Test #39: bug328 ...........................   Passed    0.41 sec
      Start 40: ws_async_shutdown
40/42 Test #40: ws_async_shutdown ................   Passed    1.07 sec
      Start 41: reqttl
41/42 Test #41: reqttl ...........................***Exception: Other  0.09 sec
      Start 42: surveyttl
42/42 Test #42: surveyttl ........................   Passed    0.21 sec

98% tests passed, 1 tests failed out of 42

Total Test time (real) =  15.83 sec

The following tests FAILED:
	 41 - reqttl (OTHER_FAULT)
Errors while running CTest
```

let me know if i can provide any additional info here

**Comment by gdamore** [comment]
Is it reproducible?  I do test on MacOS X.

**Comment by reqshark** [comment]
yea i was hesitant at first because i thought you developed on osx, but it happens on both my macs.

what happens when you run `ctest -G debug;` or `ctest -C debug;` ?

**Comment by gdamore** [comment]
I’m not seeing problems, but I am using a multicore iMac 27”.

I’m also running 10.11.4.

**Comment by reqshark** [comment]
here's the isolated test output:

```go
Start testing: Jun 20 19:44 PDT
----------------------------------------------------------
41/42 Testing: reqttl
41/42 Test: reqttl
Command: "/Users/bent/nanomsg/build/reqttl" "5900"
Directory: /Users/bent/nanomsg/build
"reqttl" start time: Jun 20 19:44 PDT
Output:
----------------------------------------------------------
Failed bind to "tcp://127.0.0.1:5900": Address already in use [48] (/Users/bent/nanomsg/tests/reqttl.c:71)
<end of output>
Test time =   0.10 sec
----------------------------------------------------------
Test Failed.
"reqttl" end time: Jun 20 19:44 PDT
"reqttl" time elapsed: 00:00:00
----------------------------------------------------------

End testing: Jun 20 19:44 PDT
```

looks like i might need `SO_REUSEADDR`, what do you think?

**Comment by reqshark** [comment]
oh nevermind, sorry i needed sudo permissions to open AF_SP_RAW

when i run the test with sudo it passes

**Comment by Snaipe** [comment]
It's still weird that the error returns "Address already in use" -- API should probably set errno to EACCESS.

**Comment by reqshark** [comment]
to me it feels more like `EADDRINUSE` but yea it's also `EACCESS`

**Comment by Snaipe** [comment]
Now that I think about it, port 5900 shouldn't require sudo to bind to -- unless it's a port of a known OS X service?

Maybe sudo allows the port to be reused, but it really shouldn't be allowed to do so. What happens if you change the base port in the cmake config to something higher (and run w/o sudo)?

**Comment by reqshark** [comment]
> port 5900 shouldn't require sudo to bind to -- unless it's a port of a known OS X service?

i agree with you, it's not a sudo/permissions thing

sudo would only make sense if all AF_SP_RAW sockets required sudo

so it seems more like a port use issue, since now without using sudo i see the test pass...

**Comment by reqshark** [comment]
> If that's the only issue, we can just change the base port.

RFB uses 5900 by default https://en.wikipedia.org/wiki/RFB_protocol

**Comment by Snaipe** [comment]
Ideally we should be using an ephemeral port for tests, but since it's not yet supported, I propose a little fix to use port 49200 and higher, since it's in the reserved private range and will guarantee to not conflict with anything else.

**Comment by gdamore** [comment]
49200 is in the range of ephemeral ports.  These ports are more likely to conflict as they can have been assigned for ephemeral use. 

we should choose a new starting port but one below 16000 I think.

**Comment by gdamore** [comment]
recommend 12100 or 12500 as they have no known common uses or iana reservations.
