### ISSUE TITLE
How to use CMake compile nanomsg under the ARM cross compiler Toolchain?

### ISSUE THREAD

**Issue by skyformat99** [nanomsg/nanomsg#775]
Hi Team
At first, I appreciate you and the team for releasing the nanomsg 1.0 finally.
So, as a fan, How to use CMake compile nanomsg under the ARM cross compiler Toolchain?
The development environment:
1) Ubuntu 14.04 LTS
2) arm-linux-gnueabihf-gcc,  arm-linux-gnueabihf-g++  .  gcc version 4.8.4

root@ubuntu:~$ arm-linux-gnueabihf-gcc -v
Using built-in specs.
COLLECT_GCC=arm-linux-gnueabihf-gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc-cross/arm-linux-gnueabihf/4.8/lto-wrapper
Target: arm-linux-gnueabihf
Configured with: ../src/configure -v --with-pkgversion='Ubuntu/Linaro 4.8.4-2ubuntu1~14.04.1' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/arm-linux-gnueabihf/include/c++/4.8.4 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --disable-libitm --disable-libquadmath --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-armhf-cross/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-armhf-cross --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-armhf-cross --with-arch-directory=arm --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --disable-libgcj --enable-objc-gc --enable-multiarch --enable-multilib --disable-sjlj-exceptions --with-arch=armv7-a --with-fpu=vfpv3-d16 --with-float=hard --with-mode=thumb --disable-werror --enable-checking=release --build=i686-linux-gnu --host=i686-linux-gnu --target=arm-linux-gnueabihf --program-prefix=arm-linux-gnueabihf- --includedir=/usr/arm-linux-gnueabihf/include
Thread model: posix
gcc version 4.8.4 (Ubuntu/Linaro 4.8.4-2ubuntu1~14.04.1)

**Comment by Snaipe** [comment]
The first thing you need to do is to define a cmake cross compilation toolchain, as follows:

(assuming that your system is linux & that your toolchain is installed at /usr/arm-linux-gnueabihf)

```cmake
SET(CMAKE_SYSTEM_NAME Linux)
SET(CMAKE_SYSTEM_PROCESSOR arm)
SET(TRIPLE arm-linux-gnueabihf)

SET(CMAKE_C_COMPILER ${TRIPLE}-gcc)

SET(CMAKE_FIND_ROOT_PATH /usr/${TRIPLE})
SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
```

Save that as a `.cmake` file, like `arm-toolchain.cmake` for instance.

Then, you follow the normal build instructions while specifying the path to the toolchain file:

```bash
$ mkdir build && cd $_
$ cmake -DCMAKE_TOOLCHAIN_FILE=../arm-toolchain.cmake ..
$ make
```

This should do it.

**Comment by gdamore** [comment]
I'm going to close this, as this isn't a bug.  I think this is all standard "using CMake to cross compile" stuff.
