### ISSUE TITLE
nn_reallocmsg is hideously broken, corrupts memory.

### ISSUE THREAD

**Issue by Parakleta** [nanomsg/nanomsg#776]
I cannot believe a problem of this magnitude has been undiscovered in the code for 2 years now, especially given that you've chosen to bump to 1.0.

Essentially the problem is that `nn_chunk_realloc` correctly calls `nn_chunk_getptr` to find the start of the header, including the dead space that is injected by `nn_chunk_trim`, but then each of the two behaviour branches it one way or another assumes that the dead space is 0.

In the first branch it calculates the size that should be allocated as ignoring the dead space (via `nn_chunk_hdrsize`, which will truncate data if it was shifted forward by the dead space.  It then returns the data pointer assuming no dead space (via `nn_chunk_getdata`), which means that the dead space size and the tag will not be found if the dead space is not zero and all future `nn_chunk_getptr` calls will be incorrect which will lead to illegal memory access.

In the second branch it copies the data into the newly allocated block assuming that the old block had a zero dead space (again vai `nn_chunk_getdata`).  This destroys data, but at least it doesn't corrupt memory.

The requirement for these to fail is that the `nn_chunk_trim` function is called, which is the case when a message is received in the REQREP mode and the return address is extracted.  This means that the very basic `nn_recv(); nn_reallocmsg(); nn_send()` sequence to minimise allocations will fail every time.

The solution to the later case is simply to replace `memcpy (new_ptr, nn_chunk_getdata (self), self->size);` with `memcpy (new_ptr, *chunk, self->size);`.

The former may be more complex.  The naive solution is just to call `memmove(nn_chunk_getdata(self), *chunk, self->size);` to remove all of the dead space, and then `nn_putl ((uint8_t *) ((uint32_t*) (self + 1)), 0);` to wipe the size of the dead space and perform the rest of the reallocation as normal.

For a less naive solution we might consider whether some balance between the cost of `memmove`, `realloc` and potential wasted memory.  If we are sizing down the memory we could just change the `self->size` value and not perform a reallocation at all.  If we are increasing the memory but there is enough dead space to accommodate the new size we could use `memmove` instead of `realloc` if we make the assumption that it is cheaper (which it may not be if `realloc` can increase our size without moving the data).  If we are increasing the memory and have to call `realloc` we may chose not to use `memmove` first since it may be cheaper to just allocate the extra required dead space than do a `memmove` followed by an implicit `memcpy` when `realloc` allocates a new block.

As an aside, `nn_chunk_trim()` calculates the fixed header size itself directly, rather than using the result of the `nn_chunk_hdrsize()` function, leading to duplication of effort and potential future code divergence and errors.

**Comment by reqshark** [comment]
I pass my own buffers

**Comment by gdamore** [comment]
Ok, I think I see the problem.

In the refcnt.n == 1 case, we reallocate, and include the header in the allocation.  This is probably not strictly necessary.

What we'd like to do is preserve the data where it is, using "realloc" only if we're going to actually be able to benefit from the reallocation -- that is that we can save a separate alloc and data copy.   In that case it should just be an update to the size.

In the other case, we should just do the same as when refcnt.n != 1, and do an explicit alloc and copy.  Its not going to be any different than a libc based realloc in terms of performance.

Stay tuned for more.

**Comment by gdamore** [comment]
Yes, I see several more issues here.  This is going to take some time as I want to make sure that I get the semantics right here.

**Comment by Parakleta** [comment]
I thought about it some more and as the simplest solution I have just changed the `hdrsize = nn_chunk_hdrsize()` to use instead the difference `(uint8_t*)*chunk - (uint8_t*)self` and then when updating the chunk instead of `nn_chunk_getdata(new_chunk)` use instead `(uint8_t*)new_chunk + hdrsize`.

This is the simplest semantic correction but overlooks potential savings in consolidating the dead space, but then attempting to consolidate the dead space may turn out to be a case of premature optimisation if it's only ever small.

**Comment by gdamore** [comment]
Note that this is fixed in libnng... I still need to look at resolving this for nanomsg itself.

**Comment by gdamore** [comment]
Ok, looking at this in a bit more detail.

a) The empty space at the beginning is entirely optional, and cannot be reclaimed, or really referenced, in application.  Once an application calls chunk_trim() or chunkref_trim(), that's gone.  So we don't need to "preserve the space". 

b) We can *expand* into the space intelligently -- if the new size is small enough to do so, and memmove.

c) We only have to memmove if the new size is *larger*, and still fits in the extra space.

d) Arguably, we could save allocations if we 'always' moved data to the end when preserving data, but to be honest reallocmsg is probably called infrequently that it doesn't matter.
