### ISSUE TITLE
SIGABRT on connecting to inproc with type PAIR

### ISSUE THREAD

**Issue by djc** [nanomsg/nanomsg#777]
In

```
0   libnanomsg.5.0.0.dylib              0x0000000103cbbf8c nn_sinproc_handler + 1279
1   libnanomsg.5.0.0.dylib              0x0000000103cad227 nn_ctx_leave + 164
2   libnanomsg.5.0.0.dylib              0x0000000103cad234 nn_ctx_leave + 177
3   libnanomsg.5.0.0.dylib              0x0000000103cad234 nn_ctx_leave + 177
4   libnanomsg.5.0.0.dylib              0x0000000103cac441 nn_sock_add_ep + 163
5   libnanomsg.5.0.0.dylib              0x0000000103ca9ed2 nn_connect + 72
```

See https://github.com/nanomsg/nnpy/issues/17.

**Comment by gdamore** [comment]
So this is PAIR.  Basically we are saying that the socket is already paired, and we can't add additional ones.  Sadly we are aborting here rather than just returning a sane error code.  Stay tuned.

**Comment by gdamore** [comment]
This seems to be tied to inproc as well.

**Comment by gdamore** [comment]
I'm pretty sure the above fixes the issue.  Please feel free to verify for yourself.  I'll probably merge this shortly.
