### ISSUE TITLE
soname and version name mix and mismatch

### ISSUE THREAD

**Issue by a4z** [nanomsg/nanomsg#781]
build machine RHEL 6.8 32bit
downloaded this: https://github.com/nanomsg/nanomsg/archive/1.0.0.tar.gz

build and install, result in those library files

```
[me@computer lib]$ ls -l libnanomsg*
lrwxrwxrwx 1 root root     19 Jul 11 11:23 libnanomsg.so -> libnanomsg.so.5.0.0
-rwxr-xr-x 1 root root 357851 Jul 11 11:23 libnanomsg.so.1.0.0
lrwxrwxrwx 1 root root     19 Jul 11 11:23 libnanomsg.so.5.0.0 -> libnanomsg.so.1.0.0

```

I think this is wrong and should be 

```
libnanomsg.so -> libnanomsg.so.1.0
libnanomsg.so.1.0 -> libnanomsg.so.1.0.0
```

the soname of the library is 5.0.0, but should be 1.0.0

```
[me@computer lib]$ objdump -p libnanomsg.so.1.0.0 | grep SONAME
  SONAME               libnanomsg.so.5.0.0
```

it is unclear if this library is 5.0.0 or 1.0.0, it can not be both.
as it is, it will not pass packaging rules for some distributions

I also think the soname should be libnanomsg.so.1.0  to enable binary compatible updates with new patch level numbers.

if seems that in src/CMakeLists.txt this needs to be adopted 

```
    set_target_properties (${PROJECT_NAME} PROPERTIES
        VERSION "${NN_PACKAGE_VERSION}"
        SOVERSION "${NN_ABI_VERSION}")

```

possible to something like

```
    set_target_properties (${PROJECT_NAME} PROPERTIES
        VERSION ${MAJOR_VERSION}.${MINOR_VERSION}.${PATCH_VERSION}
        SOVERSION ${MAJOR_VERSION}.${MINOR_VERSION}
       OUTPUT_NAME nanomsg
)
```

where I assume the ${MAJOR_VERSION}.${MINOR_VERSION}.${PATCH_VERSION} variables are somewhere available.

values for the wrong ${NN_ABI_VERSION} come from
 src/nn.h, line 59

```

/*  The current interface version. */
#define NN_VERSION_CURRENT 5

/*  The latest revision of the current interface. */
#define NN_VERSION_REVISION 0

/*  How many past interface versions are still supported. */
#define NN_VERSION_AGE 0
```

they are read out in the CMakeList.txt in the root dir.

if you confirm this issue and if it's not to time critical I can give it a trial to fix it,  but it could be that you need to wait for the next weekend at least.

**Comment by JackDunaway** [comment]
Hi @a4z, thank you kindly for the detailed write-up here, but this turns out to be not a bug. Rather, it's the inherent mismatch between the **API version** (1.0.0 currently) and **ABI version** (5.0.0 currently). That mismatch is a bit confusing, and even unfortunate, but correct.

Check out the link from the source code that explains a bit further: https://github.com/nanomsg/nanomsg/blob/b8ec7e9c684a18e3eb144d4e16fb5dc320e80895/src/nn.h#L57

**Comment by JackDunaway** [comment]
Re-opening ... on the other hand, having just inspected more closely and even followed your download/build procedure (on OS X), I see the output is `libnanomsg.1.0.0.dylib` with symlink `libnanomsg.5.0.0.dylib`. This itself is probably incorrect.

**Comment by a4z** [comment]
good decision  @JackDunaway ,  you might also consider to rethink the API  ABI split, which is .. at least very special, and yes, I know about naming shemas, also tose from libtool.
I also guess that changing the API without the ABI and vice versa is not even possible, 
but anyway 
I think, if you want ever official packages of nanomsg see in distributions this version / abi mix needs to be fixed, 
the so name must match the MAJOR.MINOR concept, than someone can make a rpm nanomsg-1_0
the pachlevel for binary compatible changes, 
so  nanomsg-1_0-0 will be updated with  nanomsg-1_0-1 if the ABI is compatible (which requires a compatible API),
the next package can than be nanomsg-1_1 (with a changed API that generates a new ABI) and be installed alongside the nanomsg-1_0
as additional  reference:
https://en.opensuse.org/openSUSE:Shared_library_packaging_policy

I am pretty sure that package linter will reject nanomsg-1_0 with a soname 5.0.0, and this not just on openSUSE distros but also others that do those kind of checks.

**Comment by JackDunaway** [comment]
@a4z, so for clarity, you're suggesting that ABI and API should track each other exactly?

I'll mention @gdamore here for visibility, who has a broader understanding of packaging considerations across distros. If there's an action item here, we'll definitely want to fix it!

**Comment by Snaipe** [comment]
ABI and API version numbers never had the requirement to be equal -- it's even a mistake to have them follow each other tbh, as it makes it more difficult for everyone involved.

Furthermore, ABI versions *can't* go back, switching from 5.x to 1.x would potentially break older packaging dependencies (although one might argue that because earlier ABI versions were tied to beta releases, it matters less). Don't do it.

The filename of the shared object should only contain the ABI version, though, not the API, so having `libnanomsg.1.0.0.dylib` instead of `libnanomsg.5.0.0.dylib` here is wrong.

**Comment by Snaipe** [comment]
Also as a side note having a compound ABI version is weird, if not unconventionnal -- usually it's just an integer that increases with any ABI change, there is no notion of "major", "minor", or "patch". Maybe it would be better for nanomsg to simply switch to that ABI version format.

**Comment by JackDunaway** [comment]
@Snaipe, your analysis matches my understanding as well. @a4z has uncovered a bug indeed, just the inverse of the original report.

As for compound ABI versioning -- the link from `nn.h` source code (copied here for convenience: http://www.gnu.org/software/libtool/manual/html_node/Updating-version-info.html) makes a case for the rational of x.y.z versioning versus an ever-incrementing counter.

**Comment by a4z** [comment]
Hi @JackDunaway and @Snaipe 

here some additional info to this topic: 
this is all availalbe public elsewhere also, but here as a summary.

the ABI number is relevant, you might want to update the library without require recompile all apps linked against.
this can be done as long as you are ABI compatible.
that is why the ABI number should be MAJOR.MINOR.
and the library, with API number, is  MAJOR.MINOR.PATCH_LEVEL,
where MAJOR.MINOR can stay the same as long as the API stays ABI comatible ,

for internal changes, that do not break the ABI, you assign a new PATCH_LEVEL.
what means basically no changes in the public interface, simplified, otherwise, ABI compatibility is hard.
Note: if you change public interface (API) and think you stay ABI compatible, use a checker, like http://lvc.github.io/abi-compliance-checker/ to ensure that you are.

some references/examples:
https://gcc.gnu.org/onlinedocs/libstdc++/manual/abi.html
(is c++ since I am more a C++ guy, look at the breaking changes and check the naming, note they use no minor numbers)

or, an other example, 
/usr/lib/libsqlite3.so -> libsqlite3.so.0.8.6
with a SONAME libsqlite3.so.0

and just an other sample from any random lib on my system

```
cyrus-sasl-lib-2.1.23-15.el6_6.2.i686 : Shared libraries needed by applications which use Cyrus SASL
Repo        : local-rhel-i386-workstation-6
Matched from:
Filename    : /usr/lib/libsasl2.so.2.0.23

```
and
```
objdump -p /usr/lib/libsasl2.so.2.0.23 | grep SONAME
  SONAME               libsasl2.so.2
```
make this for all libs on your system, do you find a pattern in MAJOR.MINOR.PATCH_LEVEL , MAJOR.MINOR and package names?

Note that a lot of libraries do not care about MINOR numbers in fact, so theoretical 2 numbers, ABI_VERSION.IMPLEMENTATION_VERSION (to not use major/minor/..) could be enough, but major/minor/patch is used and gives more flexibility, the only decision you have to make is if you put minor into the ABI or not, this is handled individual by the software.

And **please note** that I talk about Linux, BSD might have slightly adopted conventions in their usage, so possible this is why MINOR is often not in the ABI for a lot of packages, but I would have to look that up. 

in short, I would suggest:
- use the naming as suggested and used by all other packages or something very similar, 
- fix the #define NN_VERSION_CURRENT since it has no meaning currently, you do not have that many ABI depended installations currently 
- stay as close to existing conventions to make the live of people that what to help, eg through building packages, as easy as possible.

but anyhow,
I do not want to force you to do anything you absolutely do not want.
so for me it is realy OK if you do however you want.

But there are criteria that needs to be satisfied if I package and use libraries, nanomsg does not fulfil this currently, some would say that is a bug, some would call it personal taste,  and if in doubt, I trust the package linter which works proven over years for thousands of packages ;-)

**Comment by JackDunaway** [comment]
> there are criteria that needs to be satisfied if I package and use libraries, nanomsg does not fulfil this currently

Aha -- I see this truly as the important issue that needs to be resolved. nanomsg should be able to perform for you here in an expected manner. Preventing you (and others) from making progress based on a couple numbers (assuming we can do a better job with those numbers) is insane.

Another potential "root problem" is that ABI versioning was strictly maintained well during the long pre-release alpha cycle prior to 1.0.0. It's not a problem, per se, but it does introduce a fork from the simplification of tracking ABI to API version that may not be usual for existing libraries.

I suggest allowing @gdamore to weigh in, and then move forward with a fix.

**Comment by gdamore** [comment]
Probably we are at the point where the ABI & API are stuck where they are.  I don't intend to make significant changes in 1.x.

The next ABI version will be as part of a more substantial set of changes (which will probably also have API changes) as part of nanomsg-2.0.  At that time, we should fix the links, and probably only publish the new ABI (presumably 6.0.0) -- and abandon the old "marketing" version link in the filesystem.

That said, I might change the library's name to nanomsg2 or nn2 or something.  We will see how drastic things get.

**Comment by gdamore** [comment]
What's really the case here is that libnanomsg.so.1.0.0 (or whatever) should *NOT* exist.

Instead the canonical version is libnanomsg.so.5.0.0 (which represents the ABI version, and has *nothing* to do with with the package version!)

I need to figure out how to convince cmake not to create the libnanomsg.so.1.0.0 (or whatever) link in the first.
