### ISSUE TITLE
nanocat: Option -Q (--quoted) requires at least one of the following options: --pull...

### ISSUE THREAD

**Issue by mpromonet** [nanomsg/nanomsg#782]
Hi,

The following command is working : 
`nanocat --push --connect "tcp://pi2.local:12345"  -D a`

However this command reports an error:
`nanocat --push --connect "tcp://pi2.local:12345"  -D a -Q`

> nanocat: Option -Q (--quoted) requires at least one of the following options:
>     --pull
>     --sub
>     --req
>     --rep
>     --surveyor
>     --respondent
>     --bus
>     --pair

I understand that there is no meaning to print in push mode, because there is no data to read. However the error message is confusing as `-Q` doesnot have these parameters.

Best Regards,
Michel.

**Comment by gdamore** [comment]
The wording is suboptimal, but I'm not sure what would be better.  nanocat is mostly just a test utility anyway -- I hope you aren't building on top of it.

**Comment by gdamore** [comment]
Looking at this in more detail, the generic option parser we're using is not capable of saying something better here -- I'd have to rewrite the option parser, or bypass it altogether.  For this use its simply not worth fixing.

I'm closing this as will not fix for now.  I may revisit this for nng's nngcat.
