### ISSUE TITLE
nanomsg leak FD to other process

### ISSUE THREAD

**Issue by taolinke** [nanomsg/nanomsg#784]
It's very strange.
I write a message distribute server upon nanomsg.
But after some time,when i restart the server, i failed because the listening port has been used.
Here is the situation:
[root@vsmHost12 src]# lsof -n -i:3333
COMMAND    PID USER   FD   TYPE   DEVICE SIZE/OFF NODE NAME
hsmcs   105013 root   **20u**  IPv4 **24845821**      0t0  TCP _:dec-notes (LISTEN)
hsmcs   105013 root   66u  IPv4 25366582      0t0  TCP 192.168.167.1:dec-notes->192.168.167.1:47826 (ESTABLISHED)
java    111946 root   *_20u*\*  IPv4 **24845821**      0t0  TCP *:dec-notes (LISTEN)
java    111946 root   34u  IPv6 25366581      0t0  TCP 192.168.167.1:47826->192.168.167.1:dec-notes (ESTABLISHED)
It's not because of the java, some other daemon may also have the problem.
Look at the FD number and DEVICE number, it's the SAME!
Can anyone explain it ?

**Comment by gdamore** [comment]
are you forking a subprocess?  nanomsg is not fork friendly.

**Comment by taolinke** [comment]
Is that mean i can not use functions like popen  or system?
Is nanomsg-1.0 fork friendly?
Or is there a way i can avoid it?

**Comment by taolinke** [comment]
Or is there any relative resource i can find to know what's going on?

**Comment by gdamore** [comment]
popen should be fine as is fork followed immediately by exec.

**Comment by gdamore** [comment]
We should verify that nanomsg uses close on exec everywhere that it can.

**Comment by gdamore** [comment]
It does attempt to set close on exec.  There are possible race conditions on some platforms (unavoidable, sadly), so its still an excellent idea for the programmer to ensure that unused files are explicitly closed between the fork() and the exec().  This can be done manually, or it can be arranged via posix_spawn() and file_actions.  (There are some non-portable extensions on some platforms to make this even faster than just looping through the maximum number of possible file descriptors and closing them -- for example MacOS X has POSIX_SPAWN_CLOEXEC_DEFAULT,
and illumos/Solaris have posix_file_actions_add_closefrom_np().

There is some thought that we could "freeze" nanomsg during a fork, to make situations where we attempt to create a file descriptor a 'fork-critical section' -- meaning that these functions would cause fork to block -- that would largely close this particular race, though it wouldn't do anything for the situation where some one just directly calls exec() without doing fork first.  (In that case I don't think there is anything that can be done.)  It's also unclear whether posix_spawn() would respect the necessary atfork() handler.  (It would appear that illumos' posix_spawn does *NOT* invoke the pthread_atfork() handlers.)
