### ISSUE TITLE
Survey protocol silently fails on Windows

### ISSUE THREAD

**Issue by forrestthewoods** [nanomsg/nanomsg#790]
I'm not able to get the survey protocol to work on a Win10 box. The respondent never receives a message. It just loops forever waiting.

I've been using the Pair protocol without issue. Both in my actual project and using the example code. I can not get the survey/respondent protocol to work. Neither in my project nor using the example code.

There appear to be no errors. Not in creation, binding, connecting, sending, or receiving.

So far this has all been done with IPC transport.

**Comment by gdamore** [comment]
This seems strange.  The tests run on Windows (but not Windows 10 I think -- probably 8.1 or somesuch -- depending on what AppVeyor runs), without problem, and include two tests for the survey protocol. 

Can you post a minimal reproduction case?  That will help me check to see if its a real problem in nanomsg, or perhaps something that you're missing in your code.

Note that you might need to wait a little bit after connection establishment to issue the survey, as there may be delays in the lower transport establishing; as survey is best effort this means that the initial survey can be lost.  (Most folks reissue surveys periodically, which avoids this being a real problem.)

I do recall that the third party site that had demo code had a bug (incorrect protocol details) in one of the examples -- maybe it was surveyor?  Did you copy/paste from that site into your own code?

**Comment by forrestthewoods** [comment]
User error.

My code had a bind/connect mismatch. The demo code had a timing error. `Sleep(1)` isn't enough for Windows batch. 

Sorry for wasting your time.

**Comment by macdew** [comment]
I just ran into the same issue, it would be good if the sample and/or documentation was updated accordingly
