### ISSUE TITLE
compile with autotools

### ISSUE THREAD

**Issue by kroggen** [nanomsg/nanomsg#795]
Is there any fork of version 1.0 that supports compilation with autotools as it was available with the 0.8 release?

I can't use cmake in my arm.

Why not keep both compile options for POSIX systems? It was very helpful.

Thanks in advance!

**Comment by gdamore** [comment]
No, its only cmake based, but there is a configure script that makes it look like autotools.

The problem with retaining both options was that it was a rather large amount of work to maintain both, and there was divergence in how the code was compiled and configured, leading to inconsistent results depending on which was most was recently updated and which was being used by the end-users.  We will not be brining back the mess that was autotools.

That said, I'm astonished that you cannot use CMake.  What platform are you running (not just ARM, but the OS as well?)

CMake is available in source form, so you should be able to build it if necessary.  It also supports cross compilation: http://www.vtk.org/Wiki/CMake_Cross_Compiling

My first guess is that you're cross compiling and were lacking the above information?  (Its pretty easy -- you just need to set up an environment file describing how to locate tools, and libraries and headers for building for your target.)

**Comment by kroggen** [comment]
Hi Garrett,

I can't use it because my mini-pc has not enough disk space to compile it from source. I already tried it. apt-get don't work as it is an old linux release.

I am currently using the nanomsg 0.8.

But I will try to use the autotools files from https://github.com/nanomsg/nanomsg/commit/cb127489776d17c9d289d6d68584b4edaa9348b0

Thank you for your response and the hard work on nanomsg.

**Comment by gdamore** [comment]
That's somewhat surprising... I don't think CMake has especially onerous compilation requirements.  If your environment is that constrained, probably you should look into cross compilation -- I imagine you have challenges with other tools too!
