### ISSUE TITLE
error while loading shared libraries

### ISSUE THREAD

**Issue by jockchou** [nanomsg/nanomsg#798]
/usr/local/nanomsg/bin/nanocat: error while loading shared libraries: libnanomsg.so.5.0.0: cannot open shared object file: No such file or directory

**Comment by museghost** [comment]
Hi, could you check LD_LIBRAR?Y_PATH indicates the library directory (i.e. /usr/local/xxxx) ?
I assume that it was caused by the environment variable in your shell configuration.

**Comment by jockchou** [comment]
[root@jockchou ~]# echo $LD_LIBRARY_PATH


nothing!!!

**Comment by museghost** [comment]
If so, please set $LD_LIBRARY_PATH with the location where the libnanomsg.so.5.0.0 .

**Comment by jockchou** [comment]
Ok. I Get, Thank U...

**Comment by Snaipe** [comment]
A more permanent solution would be to add `/usr/local/lib` to a file in `/etc/ld.so.conf.d/`.

**Comment by gdamore** [comment]
ideally nanocat would be built with this path compiled in.  Its strange that this is not the case.

**Comment by gdamore** [comment]
Which platform was this on?

**Comment by Snaipe** [comment]
@gdamore installing everything under `/usr/local` is the default behaviour when using cmake without `-DCMAKE_INSTALL_PREFIX=/usr`, and there are a lot of linux distros (Ubuntu being one) that do not add `/usr/local/bin` in the path or `/usr/local/lib` in the dynamic linker path.

I would perhaps recommend using the above cmake flag in the build instructions to avoid the issue for "non-cmake-fluent" users.

**Comment by gdamore** [comment]
Yeah, what I don't understand is why CMake doesn't add the library path into the ELF object itself... we really shouldn't require users to edit system linker configuration.  (Perhaps this is the only way on Linux?)

**Comment by gdamore** [comment]
This is the whole RPATH business in CMake, I mean.

**Comment by gdamore** [comment]
That commit should fix this... I'd like feedback.
