### ISSUE TITLE
NN_LINGER not implemented

### ISSUE THREAD

**Issue by james-lawrence** [nanomsg/nanomsg#799]
nanomsg version: 1.0.0
messages being dropped despite linger being -1. (was investigating when nn_close() was returned immediately despite messages not arriving)
I feel like i'm missing something obvious here.

note1: when not closing the socket and using the same socket for each message they all arrive.
note2: actually I can't even find any references to the linger option within the code that actually checks the value. I only see being it set. (the nn_get_sockopt is only place its read directly and I don't see any calls to nn_get_sockopt with NN_LINGER)

push:
```
#include <assert.h>
#include <stdio.h>
#include <nanomsg/nn.h>
#include <nanomsg/pipeline.h>
#include <string.h>

int emit (const char *url, const char *msg)
{
  int eid;
  int sz_msg = strlen (msg);
  int sock = nn_socket (AF_SP, NN_PUSH);
  assert (sock >= 0);
  int linger = -1;
  assert (nn_setsockopt(sock, NN_SOL_SOCKET, NN_LINGER, &linger, sizeof(linger)) >= 0);
  assert ((eid = nn_connect (sock, url)) >= 0);
  printf ("NODE1: SENDING: \"%s\" to \"%s\"\n", msg, url);
  int bytes = nn_send (sock, msg, sz_msg, 0);
  assert (bytes == sz_msg);
  printf ("SENT \"%s\" to \"%s\"\n", msg, url);
  return nn_close(sock);
}

int main (const int argc, const char **argv) {
  int i;
  char * address = "ipc:///tmp/example.ipc";
  for (i = 0; i < 10; i++) {
    char msg[1024];

    sprintf(msg, "%d", i);
    emit(address, msg);
  }
}
```

pull socket:
```
#include <assert.h>
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <nanomsg/nn.h>
#include <nanomsg/pipeline.h>


int recv(const char *url)
{
  int retval;
  int sock = nn_socket (AF_SP, NN_PULL);
  printf("binding to: %s\n", url);
  assert (sock >= 0);
  retval = nn_bind (sock, url);
  printf("binding result: %s\n", strerror(errno));
  assert (retval >= 0);
  while (1)
    {
      char *buf = NULL;
      int bytes = nn_recv (sock, &buf, NN_MSG, 0);
      assert (bytes >= 0);
      printf ("NODE0: RECEIVED \"%s\"\n", buf);
      nn_freemsg (buf);
    }
}

int main (const int argc, const char **argv) {
  char * address = "ipc:///tmp/example.ipc";
  recv(address);
}
```
push output:
```
SENDING: "0" to "ipc:///tmp/example.ipc"
SENT "0" to "ipc:///tmp/example.ipc"
SENDING: "1" to "ipc:///tmp/example.ipc"
SENT "1" to "ipc:///tmp/example.ipc"
SENDING: "2" to "ipc:///tmp/example.ipc"
SENT "2" to "ipc:///tmp/example.ipc"
SENDING: "3" to "ipc:///tmp/example.ipc"
SENT "3" to "ipc:///tmp/example.ipc"
SENDING: "4" to "ipc:///tmp/example.ipc"
SENT "4" to "ipc:///tmp/example.ipc"
SENDING: "5" to "ipc:///tmp/example.ipc"
SENT "5" to "ipc:///tmp/example.ipc"
SENDING: "6" to "ipc:///tmp/example.ipc"
SENT "6" to "ipc:///tmp/example.ipc"
SENDING: "7" to "ipc:///tmp/example.ipc"
SENT "7" to "ipc:///tmp/example.ipc"
SENDING: "8" to "ipc:///tmp/example.ipc"
SENT "8" to "ipc:///tmp/example.ipc"
SENDING: "9" to "ipc:///tmp/example.ipc"
SENT "9" to "ipc:///tmp/example.ipc"
```
expected result:
```
RECEIVED "0"
RECEIVED "1"
RECEIVED "2"
RECEIVED "3"
RECEIVED "4"
RECEIVED "5"
RECEIVED "6"
RECEIVED "7"
RECEIVED "8"
RECEIVED "9"
```

actual result:
```
RECEIVED "0"
RECEIVED "1"
RECEIVED "2"
RECEIVED "3"
RECEIVED "4"
RECEIVED "5"
RECEIVED "6"
RECEIVED "9"
```

**Comment by gdamore** [comment]
linger doesn't work with ipc (the operating systems don't support it!) -- and is never guaranteed in any event.   We do our best, but that's all we can do.

What's worse, is that nn_connect() isn't guaranteed to have actually established a connection, and so you may see messages get dropped simply due to delays in the time it takes to establish a connection (IPC should be fast though, but this would fail utterly with TCP.)

I recommend inserting a manual delay before the nn_close() if you want to simulate linger.    But better is simply not to close the socket -- opening and closing the socket for each message imparts quite a high per-message overhead, and is not a recommended pattern unless you have some one-shot use case. (E.g. a short lived program delivering a status message.)

If you want to be absolutely certain that your message was received by the other end, use REQ/REP, which provides for the ack (in the form of the REP) giving you a reliable form of delivery, with no need for lingering.  (Provided the REP socket is long lived of course.)

**Comment by gdamore** [comment]
Closing, as there isn't anything we can do here, beyond the user education in the reply.

**Comment by james-lawrence** [comment]
that is not what the documentation says at all though. 

NN_LINGER is documented as a generic socket level option which makes it not specific to a transport.
see: http://nanomsg.org/v1.0.0/nn_setsockopt.3.html
```
Sets the value of the 'option'. The 'level' argument specifies the protocol
level at which the option resides. For generic socket-level options use
_NN_SOL_SOCKET_ level. For socket-type-specific options use socket type
for 'level' argument (e.g. _NN_SUB_). For transport-specific options use ID of
the transport as the 'level' argument (e.g. _NN_TCP_).
```
NN_LINGER also EXPLICITLY calls out close in its documentation.
```
NN_LINGER
    Specifies how long the socket should try to send pending outbound messages after nn_close() have been called, in milliseconds. Negative value means infinite linger. The type of the option is int. Default value is 1000 (1 second).
```

the issue is more the document says one thing, and the code base is doing the complete opposite. Its compounded by the fact I didn't find any reference to NN_LINGER actually being used within the code base. but I'll grant that may just be my infamiliarity with the code.

so given that NN_LINGER is a generic socket option, and that it explicitly says on nn_close it'll wait for the specified time for a message to be delivered. The minimum I'd expect it to block and attempt the messages being sent until NN_LINGER is up or all messages are delivered.

```nn_connect() isn't guaranteed to have actually established a connection```
this is kind of immaterial, I'd be fine if the connections were failing completely and it attempted to deliver the messages for the specified nn_linger period, but that isn't what is happening.

```But better is simply not to close the socket -- opening and closing the socket for each message imparts quite a high per-message overhead, and is not a recommended pattern unless you have some one-shot use case.```
thats great and I agree but it has nothing to do with the issue. =)

```If you want to be absolutely certain that your message was received by the other end, use REQ/REP```
I don't want to be absolutely certain, I want it to behave according to the specification. =)

**Comment by gdamore** [comment]
I should update the documentation to NN_LINGER to indicate things more clearly.

Basically we do two things when NN_LINGER is used.  We wait until the socket drains to the kernel, and we also instruct TCP that we want it to continue to try to send the message after any underlying file descriptor is closed (using the SOL_LINGER socket option).  Unfortunately, operating systems vary in their support for this socket option, ... and it is generally only supported by TCP.

The fact is that once the data is handed to the kernel, if we call an underlying close(2) (or we exit(2)), then there is nothing we can do if the kernel doesn't support lingering.  This is simply not something you can fix with code in nanomsg.

**Comment by gdamore** [comment]
One thing we can do is if -1 lingering is specified, we can inject a forced delay regardless.  Since the user has demanded we try hard at any cost, they shouldn't complain if it takes us a few dozen extra msec to completely terminate.

**Comment by james-lawrence** [comment]
imo it should be removed from the general socket options long term then. since it doesn't apply to them all. though likely that will be a painful thing to do since its already been exposed.

**Comment by gdamore** [comment]
Well this is interesting... I cannot find a place where linger actually *does* anything.  In mangos (alternate implementation of nanomsg in Go) I wrote code to ensure it does, but it seems to be non-functional in nanomsg.  Weird.

**Comment by james-lawrence** [comment]
=) said that a couple times now. =P I've been looking as well. heh

**Comment by gdamore** [comment]
So this is a bit more hairy than I realized, because of the internal architecture of nanomsg.  We should certainly set the kernel TCP parameter, but given that nanomsg never actually "queues" anything, that's pretty much all we can do.

The socket option is generic, because other transports could implement it, even though TCP is the only one to do so at present.

**Comment by james-lawrence** [comment]
I don't believe that is true unless nanomsg queues things within the transports... just because they 'could' doesn't mean they ever will. as a result i'd agrue it shouldn't be exposed as a general option unless the goal is to get every transport to support it.

**Comment by gdamore** [comment]
In fact, the model here we are following is SO_LINGER, which is a generic socket option in UNIX / POSIX systems.  We do need to document that this option may or may not be implemented for various transports.

It is a programmer error to rely upon linger actually doing anything, both on UNIX and in generic nanomsg.  Its merely supposed to be a preference; not a core behavior.  I'm sorry if the documentation doesn't make this clear -- if you need to be sure your data isn't dropped at close, you need to keep the socket alive yourself.

**Comment by james-lawrence** [comment]
`It is a programmer error to rely upon linger actually doing anything`

then it is the most pointless option ever and should be removed, if a programmer can't even rely on it to keep attempting to deliver the emssage within the provided window. =)

**Comment by gdamore** [comment]
The more I look at this, the more I think I agree ... in fact, the historical usage of SO_LINGER is specific to solving problems with TCP state machines, and really should not be used at all in most applications.  (Its a sign of defective protocol design.)

I'm actually going to change the documentation to note that this is a NO-OP and should not be used in new code.
