### ISSUE TITLE
nn_slow() & nn_fast() are an antipattern

### ISSUE THREAD

**Issue by gdamore** [nanomsg/nanomsg#804]
nanomsg code tries to force nn_slow() and nn_fast() to impact branch prediction logic.

The problems with this are:

a) It substantially impairs readability, and
b) It is often wrong.  (In fact, its often wrong in our code base, e.g. when using non-blocking I/O we will wind up taking the nn_slow() path before the fast.)
c) Modern architectures with branch-prediction don't really need this (only older embedded CPUs do)

Generally, this is a strong sign of premature optimization.  We should remove these, then profile and only add when we can demonstrate a real benefit for doing so.

**Comment by reqshark** [comment]
I would profile their removal and confirm the performance benefit first

**Comment by gdamore** [comment]
id have done the profiling before adding them. 

im making this change. folks who want to gripe about it need to demonstrate proof.  eg before and after performance results. 

i know for certain that some of the cases are just flat out wrong.

**Comment by gdamore** [comment]
Not bothering to work on this, in favor of nng.  nng doesn't have any of this branch prediction "optimizations".
