### ISSUE TITLE
Adopt BSD coding style

### ISSUE THREAD

**Issue by gdamore** [nanomsg/nanomsg#806]
I've decided to go ahead and update the coding style -- as pretty much the only person doing much work on this code base (and I'm in the middle of large sweeping changes), it does not make sense for me to continue to pay a style tax for decisions made long before I was a maintainer.

I'm going to go ahead and impost my BDFL ruling here.

The new style will be BSD based, and we will convert gradually, rather than all at once.

**Comment by reqshark** [comment]
it would be a shame to muck up git blame on account of style. Style changes should only happen as far as need demands changes to operative logic

**Comment by gdamore** [comment]
yes i will break git blame.  get over it.  my pain working with this code base trumps your desire for git blame.  thats because i work on this code far far more than anyone else.

**Comment by gdamore** [comment]
to be clear.  i am enacting this through my bdfl powers.  this decision is not open for discussion or debate.  we tried that before and the people who bitched loudest failed to demonstrate any signs of continued contribution in the months since. 

there will be a sufficiently large amount of the code base changing functionally for this as to make git blame uninteresting anyway.  i am embarking on a major refactoring

**Comment by Crest** [comment]
@gdamore: Thank you. BSD sytle(9) code is much easier to read even if it breaks `git blame`.

**Comment by reqshark** [comment]
fair enough

**Comment by gdamore** [comment]
I've shelved this work in favor of a ground up rewrite -- see the nng project.  That project uses a style that is inspired by FreeBSD (though there are some subtle differences) -- and enforced via an uncrustify configuration.
