### ISSUE TITLE
nn_term man page not built/delivered

### ISSUE THREAD

**Issue by kuncao** [nanomsg/nanomsg#831]
in  http://nanomsg.org/v1.0.0/nanomsg.7.html
 this is a link nn_term(3) to http://nanomsg.org/v1.0.0/nn_term.3.html
 this page is not exist
 404

File not found

The site configured at this address does not contain the requested file.

If this is your site, make sure that the filename case matches the URL.
For root URLs (like http://example.com/) you must provide an index.html file.

Read the full documentation for more information about using GitHub Pages

**Comment by gdamore** [comment]
Thanks.  we will fix this.
