### ISSUE TITLE
global.c#L513 L514 redundant   nn_sock_rele (sock)  ？

### ISSUE THREAD

**Issue by skyformat99** [nanomsg/nanomsg#858]
file： global.c
line 513  & 514    as below:

/*  We have to drop both the hold we just acquired, as well as
        the original hold, in order for nn_sock_term to complete. */
    nn_sock_rele (sock);
    nn_sock_rele (sock);

nn_sock_rele (sock)  repeated, is it wrong?

**Comment by gdamore** [comment]
No, that is quite correct.  The comment above explains it.
