### ISSUE TITLE
Assertion Failed: self->next == NN_QUEUE_NOTINQUEUE

### ISSUE THREAD

**Issue by mascojames** [nanomsg/nanomsg#860]
Assertion Failed: self->next == NN_QUEUE_NOTINQUEUE (......./src/utils/queue.c:102)

Getting this same assertion failure while running on two different ARM processors (one is a raspberry pi) when a relatively large message (~1.7MB) is being published. It seems smaller messages work successfully, not sure if there is a hidden buffer restriction somewhere. Software in question is running properly on x86 processors.

**Comment by gdamore** [comment]
There is a restriction for very large messages -- you can't send more than 1.0MB unless you change the NN_MAXRCVSIZE socket option.

That said, this should not cause an assertion to occur; I think you may be encountering a bug we solved a while back.  What version of the library are you using?

**Comment by mascojames** [comment]
Using nanomsg 1.0.0, I have used nanomsg 0.8 and 0.6 in the past successfully on this hardware with a similar software build. I'll try reverting back to 0.8 tomorrow and see if that works, try to narrow down the issue.

Just grabbed a stacktrace of the assertion failure:
#0  __GI_raise (sig=sig@entry=6) at /usr/src/debug/glibc/2.24-r0/git/sysdeps/unix/sysv/linux/raise.c:58
#1  0xb6773620 in __GI_abort ()  at /usr/src/debug/glibc/2.24-r0/git/stdlib/abort.c:89
#2  0xb6f74d08 in nn_err_abort () from target:/usr/lib/libnanomsg.so.5.0.0
#3  0xb6f75da0 in nn_queue_item_term () from target:/usr/lib/libnanomsg.so.5.0.0
#4  0xb6f71e48 in nn_usock_term () from target:/usr/lib/libnanomsg.so.5.0.0
#5  0xb6f85968 in nn_atcp_term () from target:/usr/lib/libnanomsg.so.5.0.0
#6  0xb6f860a8 in ?? () from target:/usr/lib/libnanomsg.so.5.0.0

**Comment by gdamore** [comment]
Ok, that's helpful information.  I suspect you're running  into an edge case caused by the 1MB limit.  That's a bug, obviously.

**Comment by mascojames** [comment]
Just to let you know I tried 0.9 and 0.8 and both had to same error. I must have a misconfiguration somewhere, I'll try playing around with the sock opts.

**Comment by mascojames** [comment]
I set NN_RCVMAXSIZE to a higher value on my receiving side and that seems to prevent the assertion on the other end, however I would suspect that this is a bug if the subscribing side can take down the publishing side.

**Comment by gdamore** [comment]
Agreed, its definitely a bug.  To be completely honest, nanomsg isn't
“safe” for the hostile internet.  I have *much* greater faith in mangos,
and soon libnng.  (There are lots of ways malicious actors can make nanomsg
do bad things unfortunately.  iibnng is due to replace libnanomsg soon, and
it is being designed to be secure / hardened from the start.)  If you’re
faced with need an internet facing deployment, stick a mangos device
implementation in front, and you should be golden.  That way you can even
use websocket or TLS…
