### ISSUE TITLE
NN_REQ / NN_REP socket binded to Websocket 

### ISSUE THREAD

**Issue by batitous** [nanomsg/nanomsg#863]
Hello,

I'm currently trying to communicate directly with the web socket binding of nanomsg : I'm using pull / push / sub nanomsg socket without problem on web socket.
But the request / reply socket (NN_REQ / NN_REP) is not working when binded to the websocket.
At first, I was thinking that my code was wrong somewhere : I replicate the bug with the attached sample code in this issues. 

Any idea of what i'm doing wrong ? May be i'm not using properly the Javascript side ? Do you need additional tests ?

(see sample code, tested on Linux / MacOsX and Safari / Chrome with the release nanomsg 1.0.0.0)
[test-nanomsg-reqrep.zip](https://github.com/nanomsg/nanomsg/files/723630/test-nanomsg-reqrep.zip)
.

**Comment by gdamore** [comment]
That attached zip file is empty.   So I can't really help you.

**Comment by gdamore** [comment]
Probably you don't realize that to use the REQ/REP protocol with JavaScript on the browser, you have to have backtraces in the messages.  PULL/PUSH doesn't have any extra headers, but REQ/REP needs to have a "backtrace" that includes a request id and details of where the request came from.  Please read the RFCs in the rfcs/ directory.

**Comment by batitous** [comment]
Thanks for your support, I will read the RFCs and include the necessary backtrace on REQ/REP socket: 
Is the file "nanomsg/src/protocols/reqrep/req.c" can help me to understand the request id and extra headers needed on REQ / REP ?

 (Sorry about the empty zip file)
