### ISSUE TITLE
Use of abort within library causes unusability for graphical programs

### ISSUE THREAD

**Issue by crule42** [nanomsg/nanomsg#864]
The use of abort as a mechanism for catching errors in the library causes the library to be unusable for programs that do not support a terminal interface such as windows GUI's. 

As an example, assume this library was being used by a graphical based game and a case that isn't handled by the library comes up. The library will currently call abort and terminate the game with no way for the application to explain what happened and potential ways to correct the program. All that has occurred is to reduce the level of confidence the user has for the game working properly.

One could argue that the case that caused the call to abort should have been handled with a proper error return code, but I don't believe there will ever have 100% coverage on all possible errors that could occur. And even if the library did cover 100% today, it is at the mercy of changes to underlying implementations of the different interface types (sockets, inproc, etc.) potentially causing it to no longer be 100% covered in future OS updates. Note that this is not limited to Windows OS.

So the question is... Is the philosophy of this group such that the abort is here to stay, or would there be a willingness to compile it out?

**Comment by gdamore** [comment]
The libnng rewrite is taking the approach to *never* abort().  There are a few cases left in, but they are truly assert() conditions -- things that should never ever come up and frankly if anyone ever did see an abort() then it would represent a serious bug in the library.

Fixing all these in the current libnanomsg is something I'd be willing to see PRs for, but at the moment I'm investing more of my energy in the rewrite.

**Comment by gdamore** [comment]
And just to be clear, asserts() are not appropriate ways to handle error returns from syscalls -- as you've noticed this impacts reliability and portability into the future.  The libnng approach is to percolate these errors all the way to the application (except in a few cases where it makes more sense for us to do something different to handle them, such as backing off and retrying a connect() attempt or somesuch.)

**Comment by scubadriver** [comment]
agree with crule42 and second comment of gdamore. Abort is a killer. Imagine Apache or Firefox aborts on connection failures or timeouts.
As for asserts, in Windows dev world for example, ASSERT usually a DEBUG build feature and in release builds it is NoOp.
So, even there is an assert(), the next line usually (unless you super tired at 5am) an if() statement checking the error and return whatever error.
My 2c anyway.

**Comment by gdamore** [comment]
We have killed a few more assertions, though we're not done yet.  nng is safer in this regard.

**Comment by gdamore** [comment]
So, for now, unless you're triggering an actual assertion, I'm going to close this issue, because its not really actionable.  If you're getting an assertion failure, then please do open a specific bug.  That may represent a coding error, it may represent a case that shouldn't be an assert at all.  But what I'm not going to do at this late state in nanomsg is scrub them all out.   I will happily remove any that you feel are particularly problematic, but please provide details in such a case.
