### ISSUE TITLE
bus filter

### ISSUE THREAD

**Issue by cloudfee** [nanomsg/nanomsg#866]
some nodes in bus do not want to receive every msg， so can you provide options to set filter when receive msg from bus 。

**Comment by skyformat99** [comment]
ref the Writing custom protocol for nanomsg:
http://vitiy.info/writing-custom-protocol-for-nanomsg/

**Comment by gdamore** [comment]
Maybe pub/sub is a better pattern for what you want?

**Comment by gdamore** [comment]
This seems like a request for a different kind of protocol; at the moment I'm going to refer you to pub/sub.  If you want to have a different one still, please provide more detail, and open a new ticket.  The BUS pattern will probably always be fully broadcast, since that's part of its definition.
