### ISSUE TITLE
Some compiler warnings

### ISSUE THREAD

**Issue by skyformat99** [nanomsg/nanomsg#877]
Some compiler warnings appear below:

Warning	1	warning C4244: 'function' : conversion from 'uint32_t' to 'uint8_t', possible loss of data	\src\transports\ws\sha1.c	124

Warning	2	warning C4244: 'function' : conversion from 'uint32_t' to 'uint8_t', possible loss of data	\src\transports\ws\sha1.c	125

Warning	3	warning C4244: 'function' : conversion from 'uint32_t' to 'uint8_t', possible loss of data	\src\transports\ws\sha1.c	126

Warning	4	warning C4244: 'function' : conversion from 'uint32_t' to 'uint8_t', possible loss of data	\src\transports\ws\sha1.c	127

Warning	5	warning C4101: 'socket_address' : unreferenced local variable	\tests\bug777.c	33

**Comment by SG7** [comment]
I have the following setup: 
 macOS Sierra 
 Version 10.12.5

  iMac (27-inch, Mid 2010)
  Model Name:	iMac
  Model Identifier:	iMac11,3
  Processor Name:	Intel Core i7
  Processor Speed:	2.93 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	8 MB
  Memory:	16 GB
  Processor Interconnect Speed:	4.8 GT/s

Developer Tools:
  Version:	8.3.3 (8E3004b)
  Location:	/Applications/Xcode.app
  Applications:
  Xcode:	8.3.3 (12175.1)
  Instruments:	8.3.3 (62125)

I followed the installation procedure. 
These are some more relevant results:

**1)** compilation went well

-- **The C compiler identification is AppleClang 8.1.0.8020042**
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works

**With only one warning:**
[ 47%] Building C object src/CMakeFiles/nanomsg.dir/transports/ws/sws.c.o
/Users/SG/Documents/code/TTC/nanomsg/nanomsg-master/src/transports/ws/sws.c:782:51: warning: implicit conversion from 'int' to 'char' changes value from 136 to -120
      [-Wconstant-conversion]
    self->fail_msg [0] = NN_SWS_FRAME_BITMASK_FIN | NN_WS_OPCODE_CLOSE;
                     
1 warning generated.

[ 49%] Linking C shared library ../libnanomsg.dylib
[ 49%] Built target nanomsg

**2)** tests went well:

**100% tests passed, 0 tests failed out of 43**

**Total Test time (real) =  16.19 sec**

**3)** target install could not finish.

cmake --build . --target install

-- Install configuration: ""
CMake Error at cmake_install.cmake:31 (file):
  file cannot create directory: /usr/local/include/nanomsg.  Maybe need
  administrative privileges.

make: *** [install] Error 1

**Comment by gdamore** [comment]
I believe this is all fixed now.

The last complaint about install is instructive -- you have to have root if you want to install to /usr/local or somesuch.
