### ISSUE TITLE
nn_poll resets EBADF to EOPNOTSUP

### ISSUE THREAD

**Issue by SG7** [nanomsg/nanomsg#886]
I have current (1.0.0) nanomsg on macOS Sierra v 10.12.5

If fd descriptor is invalid  eg: -1

       struct  nn_pollfd items[1];
       // the problem may be even more serious for a bigger table which contains
       // mix of good and bad descriptors

        items[0].fd = -1;
        items[0].events = NN_POLLIN;

         int rc = nn_poll(items, 1, 5000); // wait 5 sec

nn_poll would fail immediately with errno=1.

**1.** I would prefer nn_poll to fail after the specified timeout.
**2.** The reported errno=1 "**Operation not permitted**" is not one of the 3 errors reported in the documentation http://nanomsg.org/v1.0.0/nn_poll.3.html
    **EBADF** (9)
        Some of the provided sockets are invalid.
    **EINTR** (4)
       The operation was interrupted by delivery of a signal before the message was sent.
     **ETERM** (156384765)
       The library is terminating.

**Comment by SG7** [comment]
**Since nn_poll is broken in so many ways, it should be fixed ASAP or removed from nanomsg library.**

**nn_poll,** at surface, seems to be a silver bullet, convenience function allowing to wait for a message on many sockets with a specified timeout.
This is far from the truth. The function only works on a sunny day and it is NOT a replacement for **nn_recv**.

Case study:
//***********************
// A.  nn_recv is used only
//***********************
Start a consumer application:
1) open (client) NN_PAIR socket, NN_RESPONDENT socket or NN_SUB socket. 
2) Connect the opened socket by `nn_connect` to a url.
3) Configure a socket to be a blocking one with a timeout (optional but recommended)

```
// timeout on a receive socket
int socket_receive_option(int fd, int timeout)
{
  	int ret = nn_setsockopt (fd, NN_SOL_SOCKET, NN_RCVTIMEO, &timeout, sizeof (timeout) ) ;
  	if(ret < 0)
  	{
  		printf("socket_receive_option failed %d %s \n", nn_errno(),  nn_strerror (nn_errno ()) );
  	}
  	return ret;
} 
//
```

```
//...
  socket_receive_option(sock, 5000);
//...

```
4) Wait for the messages in the loop:

```
  while (1)
    {
      char *buf = NULL;
      int bytes = nn_recv (sock, &buf, NN_MSG, 0);
       if (bytes >= 0)
       {
      		printf ("RECEIVED YOUR MESSAGE!\n");
      		nn_freemsg (buf);
      }
      else
      {
        printf ("Timeout errno=%d %s\n", nn_errno (), nn_strerror (nn_errno ()) );
      	sleep(5);
      }
    }
```

**Behaviour:** 

_a) The timeout on the input socket is obeyed:_

Your consumer program will print the following message: 

**Timeout errno=60 Operation timed out**

**every 10 seconds**.

5) Now, start producer application with: NN_PAIR (server), NN_SURVEYOR or NN_PUB.

Send a message every few seconds on the same URL as expected by consumer.

_b) The server will be noticed:_

Your consumer applications will START RECEIVING messages and printing:

**RECEIVED YOUR MESSAGE!**


//******************************
// B. `nn_poll` is used
//******************************
Now let us try consumer application with with **`nn_poll`**.
Do not execute step 3) which is setting a timeout for a socket.

4) Wait for the message in a new loop like this: 
  

```

int wait_for_message(char *debug_msg, int fd, int timeout_ms)
{
    // function returns:
    // 0 if there is no message
    // < 0 error
    // 1 message is waiting

    struct nn_pollfd items[1];

    items[0].fd = fd;
    items[0].events = NN_POLLIN;

	//***************************************************************************************
    int  nr_of_ready_inputs = wait_for_messages(debug_msg, items, sizeof(items) , timeout_ms);
    //***************************************************************************************

    return nr_of_ready_inputs;
}

int wait_for_messages(char *debug_msg, struct nn_pollfd polls[], int polls_size , int timeout)
{
	//struct nn_pollfd {
    //	int fd;
    //	short events;
    //	short revents;
	//};

	// Each entry in the array represents an SP socket to check. events field specifies which events to check for.

    int rc;
    //***************************************
     rc = nn_poll(polls, polls_size, timeout); // wait for message till set timeout ms sec, return number of sockets ready for read (or write if configured)
    //***************************************

	// Upon successful completion, the number of nn_pollfds structures with events signalled is returned.
	// In case of timeout, return value is 0. In case of error,
	// -1 is returned and errno is set the one of the values below:
	//	NN_POLLIN
	//	Check whether at least one message can be received from the fd socket without blocking.
	//
	//	NN_POLLOUT
	//  Check whether at least one message can be sent to the fd socket without blocking.

    if (rc < 0) {
        //print_time_stamp("","");
        printf(" %s nn_poll failed: errno=%d %s\n",
        debug_msg,
        nn_errno (),
        nn_strerror (nn_errno ()));
        //print_my_pid(1);

        switch (nn_errno ())
        {
        	case EPERM: //! not defined in the nanomsg doc for nn_poll
        	    printf(" EPERM:'nn_poll': %d\n", nn_errno ());
        	break;

        	case EBADF: // Some of the provided sockets are invalid.
			  printf(" EBADF:'nn_poll': %d\n", nn_errno ());
 			break;
			case EINTR: // The operation was interrupted by delivery of a signal before the message was sent.
			  printf(" EINTR:'nn_poll': %d\n", nn_errno ());
			break;
			case ETERM: // The library is terminating.
			  printf(" ETERM:'nn_poll': %d\n", nn_errno ());
       	 	break;
			default:
			  printf(" This errno is not defined for 'nn_poll': %d %s\n", nn_errno (), nn_strerror (nn_errno ()) );
			break;
        }

        return rc;
      }

    if (rc == 0) {
        // this is a normal timeout!!!
         // PrintTimeStamp(""," No data from 'nn_poll()' loop \n");
        return 0;
    }

    return rc; //  Upon successful completion, the number of nn_pollfds structures with events signalled is returned.
}

```


```
  while (1)
    {
      char *buf = NULL;
      
      //****************************************************************
     int nr_of_ready_inputs =  wait_for_message("CLIENT", sock, 5000);
     //****************************************************************
    	
    	if (nr_of_ready_inputs == 0)
				continue; // timeout or error rc > number of events waiting

		if (nr_of_ready_inputs < 0) // timeout is ignored!
		{
	        printf ("Error errno=%d %s\n", nn_errno (), nn_strerror (nn_errno ()) );
			sleep(5); 
			continue;
		}
      
     	int bytes = nn_recv (sock, &buf, NN_MSG, NN_DONTWAIT);
      
       	if (bytes >= 0)
       	{
      		printf ("RECEIVED YOUR MESSAGE!\n");
      		nn_freemsg (buf);
      	}
      	else
      	{
        	printf ("Error errno=%d %s\n", nn_errno (), nn_strerror (nn_errno ()) );
      		sleep(5);
      	}
    }//while


```

Behaviour: 

**The BAD**
_The nn_poll will ignore 5000 timeout. **nn_poll** immediately returns with the error:_

**nn_poll failed: errno=1 Operation not permitted** 

**The UGLY**

Even if your producer (server) will come online the **nn_poll** will **NOT NOTICE IT!**

_**The consumer will never start receiving messages!**_

**Comment by gdamore** [comment]
A few thoughts here:

a) poll is never *guaranteed* to wait for the entire poll time.  It may wake up early for a variety of reasons; this is true for ordinary poll as well.  (the timeout represents a *maximum* time to wait for a change, not a minimum).  nn_poll() does indeed return early when it finds that one of the fds passed to it are invalid.  (Basically it passes through the error from nn_getsockopt(), which is used to obtain underlying notification fds.)

b) poll will also return any errno coming from the underlying OS poll() call.  That's operating system specific.  Under normal circumstances, it works fine, provided you give it valid fds.

c) nn_poll is *not* a drop-in for regular select or poll -- that is you can't use it to build either timers without fds.  (For example, you cannot implement usleep() in terms if nn_poll().)

d) Probably the documentation and/or return codes should be updated.  Obviously if you pass invalid descriptors we need to provide some kind of meaningful error -- EBADF is probably better here.

Generally I hate nn_poll(), since its of very limited utility -- almost always you are wanting to multiplex with other file descriptors, and that means you need to use the OS-specific poll, along with the nn_getsockopt of NN_RCVFD and/or NN_SNDFD.  All nn_poll does is wrap that logic up in a convenient wrapper, which turns out not to really be so convenient in the real world.

Now its *also* the case that you're sending some garbage to nn_poll beyond just a -1 fd.  The *second* argument to nn_poll is a *count*, not a size.  That is in your case you should be passing the value 1, for one file descriptor, rather than a size.  Passing a size means you're passing sizeof nn_pollfd, which is probably 8, which means that the code will try to dereference into some strange place (probably the stack), and pass utter garbage down.

So, I'm disinclined to treat this as a bug, at least until your code is fixed.  You might want to have a look at the test code in tests/poll.c, which can serve as an example.  Look specifically at this stanza:

```
    /* Test nn_poll() function. */
    sb = test_socket (AF_SP, NN_PAIR);
    test_bind (sb, SOCKET_ADDRESS);
    sc = test_socket (AF_SP, NN_PAIR);
    test_connect (sc, SOCKET_ADDRESS);
    test_send (sc, "ABC");
    nn_sleep (100);
    pfd [0].fd = sb;
    pfd [0].events = NN_POLLIN | NN_POLLOUT;
    pfd [1].fd = sc;
    pfd [1].events = NN_POLLIN | NN_POLLOUT;
    rc = nn_poll (pfd, 2, -1);
    errno_assert (rc >= 0);
    nn_assert (rc == 2);
    nn_assert (pfd [0].revents == (NN_POLLIN | NN_POLLOUT));
    nn_assert (pfd [1].revents == NN_POLLOUT);
    test_close (sc);
    test_close (sb);
```

**Comment by gdamore** [comment]
In fact, I'm pretty sure you're seeing bad stack corruption as a result of this error.  That can lead to confusing the hell out of nn_poll itself, since it can wind up clobbering its own stack.  Lying about the number of pollfd entries you give nn_poll is *not* a good idea.

**Comment by SG7** [comment]
Thank you for taking look at the issue. Only first entry regarding behaviour for bad file descriptor is correct. The second entry suffered catastrophic error: `sizeof(items)` is totally incorrect.
  
> I'm pretty sure you're seeing bad stack corruption as a result of this error. 

I agree. Invalid file descriptors in inflated by mistake structure caused the error being return by `nn_poll `. That made `nn_poll ` unusable, even though the first entry had a valid descriptor. 
That actually exposed an issue with `nn_poll `. If `nn_poll `fails for any reason it cannot indicate the fact that some sockets are actaully ready to receive/send.  

It may be better to extend` struct nn_pollfd` by new struct member to indicate the error condition per fd. Otherwise any broken fd invalidates the whole `nn_poll `work all together.  
New structure:
   ```
 struct nn_pollfd {
     int fd;
     short events;
     short revents; // may have NN_POLL_ERROR 
     int error; // keeps the errno 
    };
```
In this new scenario `nn_poll ` would return after the timeout with 0 or sooner with number of ready sockets for read/write. `revents `could use NN_POLL_ERROR flag to indicate the problem for a given fd entry.

**Comment by gdamore** [comment]
Turned out we were just clobbering errno that was already set by nn_getsockopt.  Easy fix.
