### ISSUE TITLE
nn_term documentation is wrong

### ISSUE THREAD

**Issue by arossert** [nanomsg/nanomsg#888]
According to the documentation after calling [nn_term()](http://nanomsg.org/v1.0.0/nn_term.3.html) blocking operations like `nn_recv`/`nn_send` should retuen `ETERM` but in my case the error code is `EBADF` (using nn_errno()).

Is this a mistake in the documentation?

**Comment by SG7** [comment]
After termination a PUB socket with `nn_term `also non-blocking send will return `EBADF`. 

> errno=9 Bad file descriptor

That makes sense since socket is no longer valid.

**Comment by arossert** [comment]
So this is a mistake in the documentation?
We should expect `EBADF` in this scenario?

**Comment by gdamore** [comment]
It depends.  Pending blocked calls are woken up with ETERM.  New calls will return EBADF.  This is pretty annoying but its a legacy semantic.  I recommend treating both errors the same way.

**Comment by arossert** [comment]
This is not what I'm getting, look at this code:

```
int sock = nn_socket(AF_SP, NN_PAIR);
nn_bind(sock, "inproc://a");

std::thread t([]() {
	sleep(2);
	nn_term();
});

char buf[1000];
int res = nn_recv(sock, buf, sizeof(buf), 0);
if (res < 0) {
	cout << nn_errno() << ": " << nn_strerror(nn_errno()) << endl;
}

t.join();
```

I would expect to get `ETERM` on the blocking `nn_recv` but this is the output:
>9: Bad file descriptor

**Comment by gdamore** [comment]
This *might* be inproc messing things up...

**Comment by gdamore** [comment]
So... actually I forgot that the current behavior is as intended, as set up with #692  -- the only way ETERM occurs now is if you call nn_socket() to try to open a new socket after nn_term().  For everything else we just use EBADF everywhere.

I will fix the documentation for nn_term() to reflect that.

**Comment by gdamore** [comment]
It turns out that the docs also indicate that nn_term is nonblocking, which is not true anymore.
