### ISSUE TITLE
Emscripten WebWorkers support

### ISSUE THREAD

**Issue by promethe42** [nanomsg/nanomsg#891]
Hello,

[Emscripten](https://github.com/kripken/emscripten) is a C/C++ to JavaScript compiler.
It provides a [WebWorkers](https://en.wikipedia.org/wiki/Web_worker) abstraction using the following C functions:

* [worker_handle emscripten_create_worker(const char * url)](https://kripken.github.io/emscripten-site/docs/api_reference/emscripten.h.html#c.emscripten_create_worker)
* [void emscripten_destroy_worker(worker_handle worker)](https://kripken.github.io/emscripten-site/docs/api_reference/emscripten.h.html#c.emscripten_destroy_worker)
* [void emscripten_call_worker(worker_handle worker, const char *funcname, char *data, int size, em_worker_callback_func callback, void *arg)](https://kripken.github.io/emscripten-site/docs/api_reference/emscripten.h.html#c.emscripten_call_worker)

It's "kinda" like a simple socket API.
I would like to use nanomsg and define a WebWorker transport protocol.
I'm guessing it's very much like the IPC transport one, but I don't know where to start...

My final goal is to have a distributed application framework that allows different modules that run on the same device (IPC or WebWorkers messaging) or on a different device (sockets) to work together.
Those devices would be a server, an iOS/Android device and a Web browser.
Each module would perform different kind of computation, and they would communicate by messaging each other FlatBuffers based messages.

I'm starting with the Emscripten/WebWorker thing because I think it's the most challenging one.

How can I implement a custom IPC transport layer on top of Emscripten's WebWorker API ?

Best case scenario, it would be the exact same interface as the IPC transport (ipc:// endpoit and all...) but it would use the Emscripten WebWorker API when compiling with Emscripten.
Somekind of platform (Emscripten in this case) specific IPC transport...
Does that make sense?

Thank you!

**Comment by reqshark** [comment]
Keep in mind that (probably for reasons of security), socket network API calls are not implemented for web browser JavaScript. 

That means many of this library’s system headers will not be accessible by the emscriptem compiler, and therefore I would expect emscriptem to throw a bunch of compiler errors if your application code tries to include Nanomsg headers or lib symbols

**Comment by promethe42** [comment]
> socket network API calls are not implemented for web browser JavaScript.

Emscripten has POSIX sockets to WebSockets bindings.
I already developped a Linux C socket program that builds with Emscripten and runs in the browser.

Of course I'll have to make sure I exclude all problematic files from the the source list.
But I'm used to doing exactly that when working with Emscripten.

I'm "pretty sure" I can get the relevant stuff in nanomsg (sockets and the WebWorker IPC thing I want to add) to build with Emscripten.

**Comment by promethe42** [comment]
I'm pretty sure I have to add platform (Emscripten) specific stuff here:

https://github.com/nanomsg/nanomsg/tree/master/src/transports/ipc

But I don't know where to start...

**Comment by reqshark** [comment]
Hmm, that’s an interesting anecdote, I didn’t realize emscripten succeeded in mapping POSIX network calls to websocket. 

Heh well... full disclosure: I tried to do that a couple years so it sounds like maybe it’s possible now! :)

Can the emscripten linker actually translate a compiled network library’s symbols back to websocket?

**Comment by gdamore** [comment]
this sounds interesting. mapping POSIX sockets to websockets is not
possible but maybe they have some other solution. i will investigate.

**Comment by reqshark** [comment]
> Emscripten supports libc networking functions but you must limit yourself to asynchronous (non-blocking) operations. This is required because the underlying JavaScript networking functions are asynchronous.

<sub>-- [from the wiki](http://kripken.github.io/emscripten-site/docs/porting/guidelines/api_limitations.html
)</sub>

yea their limitation statement the C networking API is extremely vague. 

i gave up trying to make emscripten work with nanomsg some time ago. I never got it to work and even spent a good all nighter or two trying, things might have changed since then, but I kinda doubt it

**Comment by gdamore** [comment]
Having looked a bit more... there is some evidence of support for *nonblocking* socket equivalence, which may be useful in code used within nodejs.  However, there is *no* chance that a useful implementation will work in the browser; the browsers still restrict access to only websockets.

(TBH, this restriction, which I find to be made based on "security", seems pretty silly to me.  If I can open a websocket, or an HTTP socket, why can't I open any other kind of TCP socket.  I don't understand how there can be a security difference there, and I'm almost willing to chalk that up to my own ignorance -- but not quite.  Maybe someone who's watching can clue me in further.)

**Comment by reqshark** [comment]
browser functionality is accessed through the Web APIs defined by the [Web Platform](https://en.wikipedia.org/wiki/Open_Web_Platform)

you would think that consortium, whose's user interface and fundamental runtime is etched into request/response cycles over remote networks would be more keen on socket protocols

**Comment by promethe42** [comment]
Yes non blocking POSIX sockets work. They actually work pretty well IMHO.
Anyway... that's one thing.

What's with the IPC thing?

As detailed in my first post, the Emscripten API has:
* somekind of FD (the worker handler)
* passes char* data to that worker
* has a C function pointer callback mechanism to listen to the char* sent by the other proc (/worker)

Any chance I can get it to work by adding some platform specific code into the existing IPC code?
AFAIK the existing code has platform specific (Windows Pipe/POSIX IPC sockets) code already, right ?

**Comment by gdamore** [comment]
i dont understand why you would need to treat ipc any different than tcp.  its still just a socket.

**Comment by promethe42** [comment]
> i dont understand why you would need to treat ipc any different than tcp. its still just a socket.

I'm trying to built support for WebWorkers. And the closest thing in nanomsg IMHO is IPC since WebWorkers are considered just like a different process.

**Comment by gdamore** [comment]
So WebWorkers don't share address space or any kind of global data?

Implementing a new port for nanomsg is probably a mistake, IMO.  Instead, you might want to have a look at libnng... especially the changes I just merged into master.  There is support for a platform specific set of IPC calls, and I'd imagine that you could make a "JavaScript" (browser?) "platform" that offered up its own webworker based IPC implementation.  Alternatively, you could invent a new transport entirely, but IPC is probably a better model for you.

This whole thing starts to sound really interesting to me!

**Comment by promethe42** [comment]
> So WebWorkers don't share address space or any kind of global data?

Nope. The whole API is in my original post.

> Implementing a new port for nanomsg is probably a mistake, IMO.

I don't want to "port" nanomsg. I just want it to support a new platform.
It supports the Windows and POSIX APIs, and I'd like it to support the Emscripten API. Especially on the IPC side.

>  you might want to have a look at libnng

What is the relation between libnng and nanomsg?
Is the purpose of libnng to make it easier to support more platforms/transports?

**Comment by promethe42** [comment]
So if I try to build nanomsg using Emscripten, it might "just work" if my app uses non blocking sockets?

**Comment by gdamore** [comment]
It might!

**Comment by promethe42** [comment]
> It might!

That's a good start!

Now if I want to use not the socket transport, but the IPC transport.
What are the required POSIX functions?

**Comment by gdamore** [comment]
To use IPC on nanomsg, you'd have to have the entire family of AF_UNIX calls, including socket(), bind(), listen(), send(), recv() (and poll() or whatever) and support for the AF_UNIX sockaddr family.  This is probably not something that can trivially be done if your platform lacks support for it.

You could create your own port of the IPC transport, using the existing code as a model (note that Windows emulates the POSIX functionality).  I'm not going to guide you through this for libnanomsg, because frankly I don't want to invest the time here, and I don't think you should either.  (Writing new transports for libnanomsg is *not* easy.)  Instead I think you should have a look at nng; it has platform hooks for IPC that should be pretty easy to implement.

For now closing this against nanomsg so it doesn't count "against" it as a bug/issue.  Feel free to continue to discuss here though.
