### ISSUE TITLE
server cant send long message

### ISSUE THREAD

**Issue by kangseung** [nanomsg/nanomsg#893]
I am not good at english.  

I use request /reply  send a long message to client . rc is data bytes. but the client recv is blocking,cant receive any message. server in while(true) receive same request ,send message continuesly.

**Comment by SG7** [comment]
Could you post the code for your case?

**Comment by gdamore** [comment]
if the message is over 1MB you will need to change the maxrcvsize option.
we discard messages larger than this - for security reasons.

**Comment by kangseung** [comment]
how can change maxrcvsize option ?  T^T  i try to change it but it doesn't work.   please watch my codes

I update some codes

1.
https://github.com/kangseung/nanomsgquestion/blob/master/jsclient.cpp

(this->socket in https://github.com/kangseung/nanomsgquestion/blob/master/jssocket.cpp)

I press button  call this function onPressReqHistoryChart() and this->socket.send(json); and json = this->socket.recv(); blocking.   and I think it works correct.

2. in server
https://github.com/kangseung/nanomsgquestion/blob/master/main.cpp

I receive message and call this function 
```

else if (msg_head == "reqHistoryChartData")
{
	my_logger->info("reqHistoryChartData");
	**jsreply.publishHistoryChartData(&socket);**
 }
```

https://github.com/kangseung/nanomsgquestion/blob/master/JSReply.cpp

 **void JSReply::publishHistoryChartData(JSSocket *socket)**

send a very long message, then main.cpp while(true) will receive  duplicate message  and call **jsreply.publishHistoryChartData(&socket);** again and send message again.

client will never receive any message and blocking forever.

https://github.com/kangseung/nanomsgquestion/blob/master/jssocket.cpp

`JSSocket::JSSocket(int domain, int protocol) :socket(domain,protocol)
{
	int queue_length =1000*1024*1024;
	this->socket.setsockopt(NN_SOL_SOCKET, NN_RCVBUF, &queue_length, sizeof(queue_length));

 
	this->socket.setsockopt(NN_SOL_SOCKET, NN_SNDBUF, &queue_length, sizeof(queue_length));

	/*if (protocol == NN_PUB)
	{
		int queue_length = 900000000;	
		this->socket.setsockopt(NN_SOL_SOCKET, NN_RCVBUF , &queue_length, sizeof(queue_length));
	}
	else if (protocol == NN_SUB)
	{
		int queue_length = 900000000;
		this->socket.setsockopt(NN_SOL_SOCKET, NN_SNDBUF, &queue_length, sizeof(queue_length));
	}*/
}`

I don't know this buffer code  write correct?

help me thank you  T^T

**Comment by kangseung** [comment]
I am thinking...

if I divide the long message how to send many times by req reply mode?

I only can use publish subscribe mode to send many times messages?

**Comment by kangseung** [comment]
Finally, I use publish subscribe divide long message.
