### ISSUE TITLE
Documentation not available

### ISSUE THREAD

**Issue by bou6** [nanomsg/nanomsg#905]
Hello,

I want to use nanosmg but it seems that the documentation [https://twitter.com/dysinger/posts/2013-09-16-getting-started-with-nanomsg.html] is no more available, can anybody tell me where i can find the documentation ?

Thanks in advance

**Comment by gdamore** [comment]
I have an AI to repost this content somewhere ...

**Comment by gdamore** [comment]
Closing as a dup of #872
