### ISSUE TITLE
RDMA support

### ISSUE THREAD

**Issue by simonzhangsm** [nanomsg/nanomsg#906]
Please help to support RDMA protocol, it's very harry that more and more applications are build on high speed networks with RDMA.

**Comment by simonzhangsm** [comment]
TCP are old and low throughput

**Comment by gdamore** [comment]
Not really. But RDMA will win for larger messages. However I am probably
not going to put that effort into nanomsg but instead in nng.

**Comment by bou6** [comment]
I want to help you in this subject

**Comment by ComputationalAdvertising** [comment]
Doesn't nanomsg support running on high speed networks with RDMA? nanomsg has zero-copy function. Is it necessary to use RDMA interface to run on high speed network? @gdamore @simonzhangsm

**Comment by ComputationalAdvertising** [comment]
@bou6  In support of RDMA, do you already have a solution?

**Comment by gdamore** [comment]
RDMA support is something we might consider for nng - I probably won't ever backport it to legacy libnanomsg.

**Comment by gdamore** [comment]
This is never going to happen for nanomsg.   For NNG its a possible future effort, but it would really need to have some commercial support to make it happen.

**Comment by gdamore** [comment]
See https://github.com/nanomsg/nng/issues/480

I'm closing this as will not fix for nanomsg.  NNG... who knows... show me the money. :-)
