### ISSUE TITLE
#define NN_STATIC_LIB

### ISSUE THREAD

**Issue by V3rtuoso** [nanomsg/nanomsg#908]
Hi, 

I built nanomsg with the NN_STATIC_LIB Parameter using CMake.
![Error](https://i.gyazo.com/f8601fb49ce8c3bcaad82080e25c81f1.png)

I've included the library in the linker too. Did i miss anything else?

**Comment by payas** [comment]
I'm using the libnanomsg.a and I have undefined symbols too, I think we have the same problem.

[ 50%] Linking CXX executable iadlsrv
/usr/local/lib/libnanomsg.a(dns.c.o): In function `nn_dns_start':
dns.c:(.text+0x50e): undefined reference to `getaddrinfo_a'
/usr/local/lib/libnanomsg.a(dns.c.o): In function `nn_dns_notify':
dns.c:(.text+0x5ee): undefined reference to `gai_error'
/usr/local/lib/libnanomsg.a(dns.c.o): In function `nn_dns_shutdown':
dns.c:(.text+0x7a6): undefined reference to `gai_cancel'
collect2: error: ld returned 1 exit status
CMakeFiles/iadlsrv.dir/build.make:96: recipe for target 'iadlsrv' failed
make[2]: *** [iadlsrv] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/iadlsrv.dir/all' failed
make[1]: *** [CMakeFiles/iadlsrv.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2


libnanomsg.so works just perfect, the static version is the problem

 any idea?

**Comment by gdamore** [comment]
Well, since I can't see your link line, I can't answer that.

You need to link against the .LIB -- not a .DLL.

**Comment by nxtreaming** [comment]
On Fri, Oct 13, 2017 at 2:45 AM, Alejandro Cortés <notifications@github.com>
wrote:

> I'm using the libnanomsg.a and I have undefined symbols too, I think we
> have the same problem.
>
> [ 50%] Linking CXX executable iadlsrv
> /usr/local/lib/libnanomsg.a(dns.c.o): In function nn_dns_start':
> dns.c:(.text+0x50e): undefined reference togetaddrinfo_a'
> /usr/local/lib/libnanomsg.a(dns.c.o): In function nn_dns_notify':
> dns.c:(.text+0x5ee): undefined reference togai_error'
> /usr/local/lib/libnanomsg.a(dns.c.o): In function nn_dns_shutdown':
> dns.c:(.text+0x7a6): undefined reference togai_cancel'
> collect2: error: ld returned 1 exit status
> CMakeFiles/iadlsrv.dir/build.make:96: recipe for target 'iadlsrv' failed
> make[2]: *** [iadlsrv] Error 1
> CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/iadlsrv.dir/all'
> failed
> make[1]: *** [CMakeFiles/iadlsrv.dir/all] Error 2
> Makefile:127: recipe for target 'all' failed
> make: *** [all] Error 2
>
> libnanomsg.so works just perfect, the static version is the problem
>

try to link the "Ws2_32.lib" as well.

**Comment by gdamore** [comment]
Yeah, you have to link the various winsock, windows libraries.  (or whatever is appropriate for your platform.) 

You can have a look at the CMAKE logic -- we link against these libraries:

```
  -l ws2_32 -lmswock -ladvapi32
```

These are standard required libraries for Windows socket code.

**Comment by gdamore** [comment]
I believe the questions are now answered.  Submitter, can you confirm?

**Comment by gdamore** [comment]
I've added some more details in the README now.  Closing this.
