### ISSUE TITLE
NN_USOCK_ERROR assertion failure @ streamhdr.c#L265

### ISSUE THREAD

**Issue by sreedhaa** [nanomsg/nanomsg#914]
Issue is very similar to #895 except that the assertion failure happens at a different place: https://github.com/nanomsg/nanomsg/blob/master/src/transports/utils/streamhdr.c#L265

The fix for #895 needs to be expanded to take care of this scenario also.

**Comment by gdamore** [comment]
Thanks for filing this.  I went ahead and fixed already --- see #870  

Closing this as a dup.
