### ISSUE TITLE
Can use the new hash algorithm

### ISSUE THREAD

**Issue by skyformat99** [nanomsg/nanomsg#918]
There are the following remarks in file hash.c:

/*  TODO: This is a randomly chosen hashing function. Give some thought
        to picking a more fitting one. */

Perhaps it's more appropriate to use the hash algorithm in the NNG library。

**Comment by gdamore** [comment]
This is unlikely to take place... the existing hash algorithm is sufficient for now, and I'm not sure that the algorithm we use in NNG is appropriate for this usage.   TBH, I'm just less interested in spending time performance tweaking the nanomsg library -- investment of that nature is more appropriate for NNG.
