### ISSUE TITLE
Few minor warnings on Windows

### ISSUE THREAD

**Issue by SG7** [nanomsg/nanomsg#920]
A few minor warnings when building nanomsg on Windows 10 (64 bit) 

C:\Projects\nanomsg\nanomsg-master\build>cmake -DCMAKE_GENERATOR_PLATFORM=x64 ..
-- Building for: Visual Studio 14 2015
-- Selecting Windows SDK version  to target Windows 10.0.15048.
-- The C compiler identification is MSVC 19.0.24215.1
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detected nanomsg ABI v5.1.0
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
-- OS System is Windows
-- OS Version is 10.0.15048
-- Looking for InitializeConditionVariable
-- Looking for InitializeConditionVariable - found
-- Performing Test NN_HAVE_GCC_ATOMIC_BUILTINS
**-- Performing Test NN_HAVE_GCC_ATOMIC_BUILTINS - Failed**
CMake Warning at CMakeLists.txt:260 (message):
  Could not find asciidoctor: skipping docs
  
    Done Building Project "C:\Projects\nanomsg\nanomsg-master\build\ALL_BUILD.vcxproj" (default targets).
  
  cmake --build .
  
  [...]

Build succeeded.

"C:\Projects\nanomsg\nanomsg-master\build\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\Projects\nanomsg\nanomsg-master\build\async_shutdown.vcxproj" (default target) (3) ->
"C:\Projects\nanomsg\nanomsg-master\build\src\nanomsg.vcxproj" (default target) (4) ->
(ClCompile target) ->
  C:\Projects\nanomsg\nanomsg-master\src\utils\chunk.c(143): warning C4267: 'function': **conversion from 'size_t' to 'uint32_t', possible loss of data** [C:\Projects\nanomsg\nanomsg-master\build\src\nanomsg.vcxproj]
  C:\Projects\nanomsg\nanomsg-master\src\utils\strcasestr.c(31): warning C4267: 'initializing': **conversion from 'size_t' to 'int', possible loss of data** [C:\Projects\nanomsg\nanomsg-master\build\src\nanomsg.vcxproj]

    2 Warning(s)
    0 Error(s)

Time Elapsed 00:01:30.10

**Comment by gdamore** [comment]
The CMake "warnings" are normal on Windows; you can ignore them.  (You could install asciidoctor if you wanted to silence those particular warnings, but the lack of GCC atomics is something that is an aspect of your environment.  The "failure" here is completely normal.)

The warnings in chunk.c and stacasestr.c should be fixed, but at the same time they should be harmless.
