### ISSUE TITLE
Linking error 

### ISSUE THREAD

**Issue by bou6** [nanomsg/nanomsg#921]
By having a look at the `tests/term.c` I have noticed that the source file `../src/utils/thread.c` is included instead of the header file `../src/utils/thread.h`.

Including the header file results in linking errors, is it made intentionally or this is a bug ?

NOTE: including c files is not recommended since it will results in linking errors (duplicate definitions ...)
https://stackoverflow.com/questions/232693/including-one-c-source-file-in-another

**Comment by gdamore** [comment]
The .c is included intentionally.

**Comment by bou6** [comment]
OK, why exactly ? could you please explain further

**Comment by gdamore** [comment]
I am pulling in a private bit of implementation that is not normally
exposed. It is just for this test and not something normal apps should ever
do.

**Comment by gdamore** [comment]
So you should not use the tests directory to learn how to use the API -- look in the demo/ directory instead.   We do stuff that is non-good in tests/ because we have to test "internals", which is something ordinary apps don't have to do.
