### ISSUE TITLE
sending after term aborts calling process

### ISSUE THREAD

**Issue by nickdesaulniers** [nanomsg/nanomsg#926]
in https://github.com/nickdesaulniers/node-nanomsg/pull/182, I'm trying to upgrade to nanomsg to 1.1.0.  We currently have one test failing: https://github.com/nickdesaulniers/node-nanomsg/blob/master/test/standalone/term.js

test calls:
1. nn_send
2. nn_term
3. nn_close

We wrap the nn_send to be async, so it seems that nn_term runs first, then when the send call is invoked `abort` is called. calling nn_close before nn_term prevents the abort.

I noticed that nanomsg/tests/term.c doesn't test this case, but maybe there is a more elegant way to fail than aborting the caller?

**Comment by gdamore** [comment]
nn_term is one of the more ill considered parts of nanomsg. i will look at
it but i would really advise to just not call it all, or only do so via
atexit().

**Comment by nickdesaulniers** [comment]
I started hacking up a test case, but I can't repro.  Let me take a close look at our library.

```c
#include "../src/nn.h"
#include "../src/pair.h"

#include "testutil.h"

int main ()
{
    int s = test_socket (AF_SP, NN_PAIR);
    const char* msg = "hello";
    const size_t len = strlen(msg) + 1;
    nn_term ();
    nn_send (s, msg, len, 0);
    test_close (s);
    return 0;
}
```

does not reproduce the `abort`

**Comment by nickdesaulniers** [comment]
sorry, the abort is coming from libuv:

```sh
➜  node-nanomsg git:(nanomsg_upgrade) gdb node
(gdb) b abort
(gdb) r test/standalone/term.js
Thread 1 "node" hit Breakpoint 1, __GI_abort () at abort.c:51
51	abort.c: No such file or directory.
(gdb) bt
#0  __GI_abort () at abort.c:51
#1  0x00000000015bc330 in uv__io_poll (loop=loop@entry=0x228e7c0 <default_loop_struct>, 
    timeout=0) at ../deps/uv/src/unix/linux-core.c:245
#2  0x00000000015abc56 in uv_run (loop=0x228e7c0 <default_loop_struct>, mode=UV_RUN_ONCE)
    at ../deps/uv/src/unix/core.c:362
#3  0x0000000001384309 in node::Start(uv_loop_s*, int, char const* const*, int, char const* const*) ()
#4  0x000000000137de20 in node::Start(int, char**) ()
#5  0x00007ffff6b63830 in __libc_start_main (main=0x92e2b0 <main>, argc=2, argv=0x7fffffffdf48, 
    init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, 
    stack_end=0x7fffffffdf38) at ../csu/libc-start.c:291
#6  0x000000000092fef1 in _start ()
```

**Comment by gdamore** [comment]
Lol.  Glad you figured it out.
