### ISSUE TITLE
Peer's IP change detection

### ISSUE THREAD

**Issue by clearday4** [nanomsg/nanomsg#936]
Hello

I'm applying the nanomsg pub/sub on the redundant system.
When switching over occurs, pub or sub's IP will be changed.
If the pub's IP is changed, the sub needs to re-connect to the changed new IP address.
In the middleware's point of view, I think 
sub sockets detect the pub's IP change, and try to re-connect to pub socket automatically.
If pub recognize the switch-over, pub try to re-bind the new IP address and send the IP change notification to all subs before rebind.
I think Before pub socket re-bind the new IP address, send the IP change notification using inner nanomsg header to all sub sockets.
It would be better If sub gets that notification using CMSG.
In the case of sub recognize the switch-over, just close, open and re-connect to pub.

Is there any way to detect peer's IP change?

**Comment by gdamore** [comment]
If the socket is opened using a DNS name, and the server side (bind side) closes the connection, then the clients will automatically attempt to redial to the server using that name, which can return a different IP address.

Alternatively, if you know in advance that you have multiple possible IP addresses, you can set the clients to dial them.   This way they will automatically be connected to the different IP addresses.

Today there is no way for a server to tell the client it is going to change IP addresses.  This is actually very atypical, and given the reconnection properties we already have, not really needed.

**Comment by gdamore** [comment]
This  is a question, not a defect or feature request.  Closing as such.
