### ISSUE TITLE
question?

### ISSUE THREAD

**Issue by benghopy** [nanomsg/nanomsg#937]
Does nanomsg support noblock socket, I just want to using select to choose which soket want to read or write?

**Comment by benghopy** [comment]
Can I using the fcntl function to set the nanomsg socket to noblock?

**Comment by SG7** [comment]
nanomsg supports nonblocking send as well as nonblocking receive.
Check: http://nanomsg.org/v1.1.2/nn_recv.html . Socket options are set by nn_setsockopt  function
http://nanomsg.org/v1.1.2/nn_setsockopt.html. To see some simple examples how nanomsg can be used  go to http://nanomsg.org/gettingstarted/index.html

**Comment by gdamore** [comment]
You cannot issue fcntl's on nanomsg sockets, as they are not real operating system sockets.   Under the hood nanomsg uses nonblocking operations on the sockets and file handles/descriptors that it uses.

As mentioned above, you can select non-blocking operation with NN_DONTWAIT, but I'd recommend instead using nn_poll() to check for socket readability (or if you need to interact with other polling loops you can obtain a magical file descriptor by using the socket options for NN_SNDFD and NN_RECVFD.  These file descriptors will become "readable" when the underlying socket can either send or receive without blocking.

**Comment by gdamore** [comment]
Please also feel free to ask questions on the mailing list.  We try to use the issue tracker only for tracking defects and feature requests.

Closing this.

**Comment by benghopy** [comment]
Ok, I will try this way, and if I have any questions about how to using the nanomsg, I will asking on the emailing list.
Thaks a lot!
