### ISSUE TITLE
nanomsg nn_global self and use in multiple shared libraries

### ISSUE THREAD

**Issue by kiranpradeep** [nanomsg/nanomsg#938]
I work on Ubuntu 16.04 LTS. I have a two shared libraries (further referred to as modules), each using nanomsg(**statically** linked) to communicate with each other. When these modules are loaded by a single process, modules cannot communicate with each other. It appears this issue is for each module having its own nanomsg self variable([1](https://github.com/nanomsg/nanomsg/blob/377080485af82099eb0500cdcec018f913ec26bb/src/core/global.c#L176)). Shouldn't the application that uses nanomsg, declare the self variable rather than the nanomsg library itself declaring it?

All works well if modules are dynamically linked to nanomsg (single global self). Use case: Azure/iot-edge([2](https://github.com/Azure/iot-edge/issues/446)) uses nanomsg for communication between modules and they are forced to use nanomsg as a shared library.

**Comment by gdamore** [comment]
I assume you're referring to the use of the inproc transport.  The problem here is that as you notice, there is some global state, and when you try to share state, it doesn't work properly.  Code running with one instance of the library has no awareness of the presence of the other instance.

The idea of offering an API for applications to supply their own state is not a bad one.  If you want to come up with a PR for this, I'd be happy to review it.

**Comment by gdamore** [comment]
I'm pretty sure at this point that I would *not* be accepting a PR for this kind of change for legacy libnanomsg. 

I've also been thinking about how to do this for nanomsg and nng in general.  Really the only thing I can come up with is some kind of socket descriptor (using socketpair) and a custom handoff protocol.  This is a significant enough amount of work that I really would rather not deal with it.  Making this work correctly across multiple instances of the library is going to be very tricky to say the least.

In the short run if you have to pass state like this, you should use the IPC or TCP (with loopback) transports.

**Comment by gdamore** [comment]
Ok, I'm just going to close this -- there is no way that I'm going to support having separate instances of the shared library talk to each other *except* via some external transport (TCP).  Its impossible to do anything else safely.
