### ISSUE TITLE
Failures with multiple simultanous requests via reqrep

### ISSUE THREAD

**Issue by thomaslea** [nanomsg/nanomsg#942]
The problem demonstrated by this code is that when there are multiple clients
simultaneously sending requests (reqrep) sometimes replies are lost.  When
this happens, something like this will be printed:

client thread 2 unable to recv message, returned -1

If you dont have boost installed, you should be able to just change the boost 
threads to c++ threads (Ubuntu 16.04's g++ did not have std::thread).

[nanotest.tar.gz](https://github.com/nanomsg/nanomsg/files/1643291/nanotest.tar.gz)

**Comment by skyformat99** [comment]
create thread own nanosock in each child thread.

**Comment by tleacmcsa** [comment]
Dang, ok.  Thanks.

**Comment by gdamore** [comment]
I haven’t looked at your code but unless you use raw mode you must reply to
each request before receiving a new one. In other words this is strictly
synchronous. You can use multiple threads if you observe this limitation.

Raw mode will let you bypass this but then you must take care to save the
headers from the requests and include them in the replies. Those headers
contain the routing information to get the reply back to the requestor.

I believe you can look at the asyc demo or the thread demo in the demos
directory for examples of how to do this.

**Comment by tleacmcsa** [comment]
Yeah, it makes sense.  Thanks for the reply!

**Comment by gdamore** [comment]
Yep, I just looked at your code.  You're reusing the *client* socket (which was not what I expected, btw).  Just give each client it's own socket.  (You can also use raw sockets if you want to share, but you have to do the work to match replies to requests yourself, and frankly its easier just to give each client it's own socket unless you have some unusual circumstances.)

This is not a nanomsg bug, so I'm closing it.
