### ISSUE TITLE
WS message length corruption?

### ISSUE THREAD

**Issue by tehn** [nanomsg/nanomsg#943]
I'm attempting to get a basic echo working and have reduced the code to the bare minimum:

```
#include <assert.h>
#include <string.h>
#include <nanomsg/nn.h>
#include <unistd.h>
#include <nanomsg/pair.h>
#include <nanomsg/nn.h>
#include <nanomsg/ws.h>
#include <stdio.h>

int echo(int sock)
{
  char *buf = NULL;
  int result = nn_recv (sock, &buf, NN_MSG, 0);
  if (result > 0)
    {
      printf ("RECEIVED \"%s\" len: %d\n", buf, strlen(buf));
      nn_send(sock, buf, strlen(buf), 0);
      printf ("SEND \"%s\"\n", buf);
      nn_freemsg (buf);
    }
  return result;
}

int main (const int argc, const char **argv)
{
  if (argc > 1) {
    int sock = nn_socket (AF_SP, NN_PAIR);
    assert (sock >= 0);
    assert (nn_bind (sock, argv[1]) >= 0);

    int to = 100;
    assert (nn_setsockopt (sock, NN_SOL_SOCKET, NN_RCVTIMEO, &to, sizeof (to)) >= 0);
    to = NN_WS_MSG_TYPE_TEXT;
    assert (nn_setsockopt (sock, NN_WS, NN_WS_MSG_TYPE, &to, sizeof (to)) >= 0);


    while(1)
        {
            echo(sock);
            sleep(0.1);
        }
  }
  else
  {
      fprintf (stderr, "Usage: pair <URL>\n");
      return 1;
  }
}
```

and then execute with `test-echo ws://*:5555`

I'm pairing with a very basic javascript based on https://codepen.io/matt-west/pen/tHlBb

but have changed the necessary line:

`var socket = new WebSocket('wss://192.168.1.26:5555',['pair.sp.nanomsg.org']);`

---
Symptom:

Sending a packet such as "123" is echoed correctly but then a shorter packet "a" is seen by nanomsg as "a23" (and it then echos this back to the javascript). This happens reliably but unpredictably, not just with these lengths of packet but the issue is length identification which can lead to garbage in the packet. I suspect something is going on with `nn_recv()`

I've checked netstat and the javascript side does seem to be sending the correct data.

Any ideas where I should look next? Thanks.

**Comment by SG7** [comment]
Make sure to send a terminating 0 for the string.

int result = nn_recv (sock, &buf, NN_MSG, 0);

nn_send(sock, buf, strlen(buf), 0);  // strlen(buf) +1

**Comment by tehn** [comment]
Thanks for the response.

I've tried this, but it also doesn't address the primary issue which is the packet length corruption of incoming packets from javascript.

Your suggestion ensures proper line endings for packets sent to the js from c, which I haven't had any problem with.

**Comment by tehn** [comment]
Solved.

nn_recv() gets confused if the message doesn't have a trailing \0

This was a problem with the javascript, so whatever server is used at wss://echo.websocket.org doesn't care about \0

Thank you and sorry for the noise.

**Comment by gdamore** [comment]
nn_recv() shouldn’t require a trailing nul byte.  HOWEVER, the wss protocol
expects that each message is contained in a complete websocket message.
The legacy nanomsg code probably cannot deal with fragmented messages
either.  (The new code in nng can however.)

Having said that, its a common mistake in application programs to assume
that messages are null terminated, and that you can just printf() the
contents.  If the sender doesn’t send a null byte, then they aren’t, and
the receiving program will need to add a final NUL byte if is expecting to
work with C strings.  (This is most often a problem for people coming from
other languages, where NUL terminated strings are not used, but instead the
string is some kind of language construct with an explicit length.)

So, my guess is that this isn’t an error in your javascript, nor in nanomsg
itself, but in your C program which may be making false assumptions about
message content.

 - Garrett

**Comment by gdamore** [comment]
This is absolutely the case now that I read the code.  You need to use the "result" to determine the *actual* length that was sent, and not assume that strlen() is usable.

Here's modified code which should work:

```
int echo(int sock)
{
  char *buf = NULL;
  int len = nn_recv (sock, &buf, NN_MSG, 0);
  if (len > 0)
    {
      printf ("RECEIVED \"%s\" len: %d\n", buf, strlen(buf));
      nn_send(sock, buf, len, NN_MSG);
      printf ("SEND \"%s\"\n", buf);
    }
  return result;
}
```

You'll note that I am not using strlen at all, but instead am using the length of the received message (strlen will lie depending on the contents of memory).  While here I also used NN_MSG in the argument to nn_send, so that we don't need to explicitly free the message.  This also avoids an extra data copy, so its more efficient.

**Comment by tehn** [comment]
You are entirely correct, thank you for clarifying. I misread the return value from nn_recv() as being a success/fail flag and not the length of the data received, which would've cleared everything up right away. Thanks again.
