### ISSUE TITLE
cmake command error for windows version

### ISSUE THREAD

**Issue by xuanwolanxue** [nanomsg/nanomsg#944]
In the document of README.md, in section "Quick Build Instructions" for windows, the command of
"ctest --config Debug ." is wrong, the ctest command haven't parameter of "--config", it should be replace with "-C" or "--build-config". 

Note: my cmake version is: 3.10.2

**Comment by gdamore** [comment]
so the cmake command to use really depends on whether you are using studio
or some other generator. its pretty annoying in that regard.

I will review the docs again.
