### ISSUE TITLE
Can nanomsg be used as a http client?

### ISSUE THREAD

**Issue by wenq1** [nanomsg/nanomsg#946]
I know that nanomsg can use TCP as a transport. Is adding an extra layer of http parser enough to make it an http client?

Websocket support is appreciated, which means that handshake code is already in place. I just would like to know whether http parser is the only missing piece?

**Comment by gdamore** [comment]
http is “hard” and the websocket in libnanomsg is a toy that cannot easily
be extended for generic http purposes. Having said that libnng does have an
http client in that is pretty functional but the api is not public (yet). I
expect that to be resolved by this time next week.

**Comment by wenq1** [comment]
So cool!
