### ISSUE TITLE
What happens in non-blocking mode

### ISSUE THREAD

**Issue by wenq1** [nanomsg/nanomsg#947]
when sending fails (nn_send) with EAGAIN in non-blocking mode, does all of the message or part of the message needs to be resend?

Doc says either it is successful and nsends == nsends_requested, or -1 is returned.

**Comment by gdamore** [comment]
the docs are correct.

**Comment by wenq1** [comment]
Reopening to ask a side question. The answer means that stream reading is in a separate thread and signaled back to the user-defined main thread via the fd (nn_getsockops (nn_recv))? How is this fd only 'signaling' but not 'readable'? Even eventfd needs to be read so that EPOLLIN won't be triggered next time
