### ISSUE TITLE
vcpkg support

### ISSUE THREAD

**Issue by jmin911** [nanomsg/nanomsg#954]
Are there efforts to add this to Microsoft's Visual C++ package manager, vcpkg?  It is much easier to get library that way.
Thanks,

**Comment by gdamore** [comment]
I'm not aware of any specific efforts.    That said, it looks like it would be fairly straight-forward.  There is an example for zeromq that could probably be easily modified for nng or nanomsg.

I'm not sure what criteria the curators of the vcpkg ports tree use to determine whether a package should be included or not.  Maybe they just accept any PR?

**Comment by gdamore** [comment]
https://github.com/Microsoft/vcpkg/blob/master/CONTRIBUTING.md seems to cover it reasonably well.

**Comment by gdamore** [comment]
Not going to do this for nanomsg.  But how about NNG?

**Comment by gdamore** [comment]
Closing this -- we integrated details as the Microsoft team has done it for us. :-)
