### ISSUE TITLE
build problem with travis CI

### ISSUE THREAD

**Issue by kroggen** [nanomsg/nanomsg#955]
Hi!

Does someone know why the build instructions are failing with travis CI? I am using the exact steps informed here, and it used to work before.

Here is the command and the error:

```
$ sudo cmake --build . --target install
sudo: cmake: command not found
```

Here is the [complete log](https://travis-ci.org/litereplica/litereplica/builds/339751563) and the [.travis.yml](https://github.com/litereplica/litereplica/blob/master/.travis.yml) file.

**Comment by gdamore** [comment]
You need to have cmake installed — I guess it isn’t in the $PATH on travis
by default?

**Comment by kroggen** [comment]
But the 2 previous commands worked:

```
cmake ..
cmake --build .
```
And [your .travis.yml](https://github.com/nanomsg/nanomsg/blob/master/.travis.yml) does not contain the suggested command for installation:

`sudo cmake --build . --target install`

It was working on travis in the previous releases.

**Comment by kroggen** [comment]
I found that it is related to this issue:

https://github.com/travis-ci/travis-ci/issues/9113

So intead of

`sudo cmake --build . --target install`

we must use

`sudo -E cmake --build . --target install`

or

`sudo env "PATH=$PATH" cmake --build . --target install`

But only the last one worked.

**Comment by gdamore** [comment]
ah. another arbitrary breaking change by the travis team. honestly I am
less and less satisfied with travis and have been moving stuff to circle ci
as I find time to do so.

**Comment by gdamore** [comment]
So if you take a look at my .travis.yml, you'll notice that I'm not using sudo.  This is a problem with the installation of cmake on Travis (it isn't in root's path, but it is in the default user's path), and nothing I can do about it - -this isn't a nanomsg issue at all.

I generally do *not* recommend even using sudo or root privileges -- nothing in nanomsg specifically requires it.
