### ISSUE TITLE
nanomsg crash bug when Not under SP protocol connect

### ISSUE THREAD

**Issue by skyformat99** [nanomsg/nanomsg#956]
A test method for nanomsg crash,  Not under SP protocol connect.
Steps:
1) modify the local_lat. C in perf directory, 
    modify NN_PAIR to NN_PULL mode, 
    and then run local_lat. exe tcp : //*:5555, 1000 9999.   (example)

2) download webBench tool. 
         http://home.tiscali.cz/~cz210552/webbench.html
         or  https://github.com/cnnewjohn/webbench

3) compile  webbench,  then  run it ,  Such as:
         ./webbench -f -c 100 -t 100 -p 127.0.0.1:5555  http://www.google.com/
          100 thread ,  100 s ,   -p  proxy ,use it connect nanomsg  local_lat. exe

4)  local_lat. exe (server side) will crash:
     Unexpected action: state=2 source=1 action=5     \transports\ TCP \atcp.c:228
       
This bug is easy to happen when multiple client connections under non SP protocol.
NNG lib has the same problem.

**Comment by gdamore** [comment]
I'm not sure if I'm going to fix this or not.  Its clearly an ugly bug, but at the same time I'm trying to get NNG released.

**Comment by gdamore** [comment]
I recommend using NNG... its hardened against bad network protocol stuff.  nanomsg is a bit more brittle here.

**Comment by skyformat99** [comment]
ok
