### ISSUE TITLE
Multithread rpc server performance?

### ISSUE THREAD

**Issue by ZhitongLei** [nanomsg/nanomsg#959]
In the pthread_demo, I found that the more worker threads, the less requests can be processed by server.

Here is my benchmark result：

|    Worker num    | QPS    | Latency per request |
| ---------------- | ------ | ------------------- |
| 1                |  15047 | 0.066457ms          |
| 5                |  12908 | 0.077469ms          |
|10                |  11960 | 0.083607ms          |
|20                |  10087 | 0.099130ms          |

(One client, client and server are running on different machines, server machine has 24 CPUs)

Is there something wrong with my test?

Here's the server-side code:

```
void worker(int fd) {
    while (true) {
        void *buffer = nullptr;
        void *control = nullptr;
        struct nn_msghdr hdr;
        struct nn_iovec iov;

        memset(&hdr, 0, sizeof(hdr));
        iov.iov_base = &buffer;
        iov.iov_len = NN_MSG;
        hdr.msg_iov = &iov;
        hdr.msg_iovlen = 1;
        hdr.msg_control = &control;
        hdr.msg_controllen = NN_MSG;

        //std::cout << "[Info] thread " << std::this_thread::get_id() << " start....\n";
        int ret = nn_recvmsg(fd, &hdr, 0); 
        if (ret < 0) { 
            fprintf(stderr, "[Error] recvmsg failed: %s", nn_strerror (nn_errno ()));
            nn_freemsg(buffer);
            nn_freemsg(control);
            continue;
        }   
        ret = nn_sendmsg(fd, &hdr, 0); 
        if (ret < 0) { 
            fprintf(stderr, "[Error] sendmsg failed: %s", nn_strerror (nn_errno ()));
            nn_freemsg(control);
            continue;
        }   
    }   
}

// Omit code for socket initialization
// ......

std::vector<std::thread> tmp_thread_pool;
for (size_t i = 0; i < thread_num_; i++) {
    tmp_thread_pool.emplace_back(std::bind(worker, fd));
}

for (auto &thread : tmp_thread_pool) {
     thread.join();
}
```

**Comment by gdamore** [comment]
I think you're running into some core scaling problems in legacy nanomsg.  It has just a single backing thread for processing, and so all those other threads are just contending on resources and waiting for the single processing thread to run.

I'd be interested to see if NNG behaved any differently.

One thing I'm planning to do soon is release a different model for concurrency that should work far better, with a simpler model and hopefully a much higher level of attainable concurrency.  That should be posted in the NNG repository this week.

**Comment by ZhitongLei** [comment]
I would like to use NNG in my benchmark, it sounds great. Beyond that, I will try something like the reactor pattern: worker threads get new inbound request from queue instead of being spawned on a single socket.

**Comment by gdamore** [comment]
For now I'm going to close this.  Please let me know on the NNG repo about your results there.

**Comment by enjoyjoy** [comment]
How about  NNG's benchmark ?   Any  REQ/REP pattern performance improvement
