### ISSUE TITLE
nn_pubsub man page could show bind/dial

### ISSUE THREAD

**Issue by Framnk** [nanomsg/nanomsg#960]
This has tripped me up a couple of times.  For some reason when creating a nn_socket for an IPC address (ipc:///test/service) on Windows, it is necessary to call nn_bind() on the socket for any subscribers to receive messages.

The documentation for pub/sub and the examples don't seem to include the nn_bind() but I've been unable to get it to function without doing it.

**Comment by gdamore** [comment]
This isn't a bug, although perhaps the example in the man page could be clearer.  (The man page example is not an example of a complete program.) 

If you look in the demo/ directory the examples there (specifically the pubsub example) do include a bind.

This should make sense intuitively -- without a bind (or a dial), how would a pubsub socket know what address you wanted it to use?

I may go ahead and add a bind statement in the pubsub man page just to make it clearer.
