### ISSUE TITLE
it may be a "ipc" transport bug

### ISSUE THREAD

**Issue by DaneSpiritGOD** [nanomsg/nanomsg#966]
I create 2 threads.One is the main thread which created the ipc socket ,and the other is a **loop thread** which `nn_recv` the message.
when i want to exit the app. in Main thread,I invoke the `nn_close`  to destroy the socket and then try invoke `abort()` the **loop thread**.
A `AccessViolationException`(in C#) is thrown at the code line of `nn_recv`(in **loop thread**).What a horrible thing is that i cannot catch the exception.Finally,the **loop thread** is crashed and i have no idea.

In addition,i have run `normally` all the codes which are same as above except the transport (which is `tcp` ).`normally` means that code returns -1 that i can catch.
Hope for your help,thanks!

**Comment by gdamore** [comment]
I take it you are using Windows?

I don't know if abort() is meant to function in the way you mean on C#.  For C programs it just sends SIGIOT or SIGABRT to the calling program, which should cause it to crash.  User programs should not normally ever call abort().  Maybe this is different and a different abort() in C#?

**Comment by DaneSpiritGOD** [comment]
@gdamore Yes,it is on C#.
`Main Thread`
```
        protected virtual void Dispose(bool disposing)
        {
            if (!disposedValue)
            {
                if (disposing)
                {
                    // TODO: dispose managed state (managed objects).
                    _socket?.Shutdown(_endpoint);
                    _socket?.Dispose();
                    abortWokerThread();
                }

                // TODO: free unmanaged resources (unmanaged objects) and override a finalizer below.
                // TODO: set large fields to null.

                disposedValue = true;
            }
        }
        const int ThreadAbortAndJoinTime = 1000;
        private void abortWokerThread()
        {
            if (_workerThread == null || !_workerThread.IsAlive) return;
            _workerThread?.Abort();
            if (_workerThread.Join(ThreadAbortAndJoinTime))
                _workerThread = null;
            else
                throw new WorkerThreadCannotAbortImmediatelyException();
        }
```
`Loop Thread Core function`
```
        public static ReceivedBuffer ReceiveFrom(NanomsgSocketBase socket)
        {
            if (socket == null || socket.SocketID < 0) throw new ArgumentNullException(nameof(socket) + " is null.");

            var zero = IntPtr.Zero;
            int num = Interop.nn_recv(socket.SocketID, ref zero, Interop.NN_MSG, (int)SendRecvFlags.NONE);
            if (num < 0) throw new NanomsgPlusException($"{nameof(ReceiveFrom)}", true);
            return new ReceivedBuffer(zero, num);
        }
```

**Comment by gdamore** [comment]
I'm not sure what Thread.Abort() does, but the underlying nanomsg library is written in C, and will of course remain blocked in the code unless you close the socket, that's normal -- you've issued a blocking call.  The same behavior would occur in C with a thread.  If you want to have an interruptible read, you might consider combining nn_poll() or using select() or poll() with the descriptor given by NN_OPT_RECVFD, and using a non-blocking read.  You can use a second descriptor to signal a wake up on the polled descriptor list.

For the future, NNG will offer a more elegant solution using callbacks.

I don't think you should Abort() the receiving thread at all.  GIven what you're doing, closing the socket should be sufficient.

Now having said that, I'm not familiar with the C# wrapper for nanomsg.  If close() does more than just close the underlying socket (such as deallocating some wrapper structure), then its possible that this could cause an assertion.  That would be a defect in the design of the C# wrapper library -- its important that close of the socket not be tied to destruction of the socket *unless* there is some kind of reference counting in place to ensure that deallocation does not occur until all outstanding operations have terminated properly.

**Comment by DaneSpiritGOD** [comment]
@gdamore thanks for your answer.
The matter in "tcp" is different from "ipc" mode in my practice.
And i will try your method.
