### ISSUE TITLE
need the 'nn_ws’ model 

### ISSUE THREAD

**Issue by IrisHan** [nanomsg/nanomsg#968]
Excuse me and take the trouble to bother
I hope to implement a ‘Multi-Client Single-Server Design’ system as discussed in this article: https://github.com/nanomsg/nanomsg/issues/809.
But this will open too many 'handle'
I saw that ‘nanomsg’ has a new model: ‘nn_ws’ that may solve my problem. Like this: http://nanomsg.org/v0.8/nn_ws.7.html
But I didn’t see it in ‘mangos’
Do you plan to implement ‘nn_ws’ in mangos?

**Comment by gdamore** [comment]
This already exists in mangos.  See https://github.com/go-mangos/mangos/tree/master/transport/ws

**Comment by gdamore** [comment]
Closing since this is resolved.  Its also the wrong repository for a mangos issue! :wink:
