### ISSUE TITLE
Checking for library nanomsg : not found The configuration failed

### ISSUE THREAD

**Issue by aliridha1510** [nanomsg/nanomsg#970]
**$ ./waf configure**

Setting top to                           : C:\Users\usernaame\Desktop\nanomsg\nanomsgxx
Setting out to                           : C:\Users\ausernaame\Desktop\nanomsg\nanomsgxx\build
Checking for 'msvc' (c compiler)         : C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\CL.exe
Checking for 'msvc' (c++ compiler)       : C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\CL.exe
Checking for library nanomsg             : not found
The configuration failed
(complete log in C:\Users\usename\Desktop\nanomsg\nanomsgxx\build\config.log)

**Comment by gdamore** [comment]
I guess maybe nanomsg itself isn't installed here?  I haven't really spent any time with the C++ version.
