### ISSUE TITLE
problem with boost.asio 

### ISSUE THREAD

**Issue by PooyaEimandar** [nanomsg/nanomsg#982]
Hi there
I want to use nanomsg tcp req/rep for client application and the tcp server used boost.asio.
I tested server with telnet and worked fine, also nanomsg connected successfully, but could not receive message and always returns -1. 
The socket created with domain AF_SP: and protocol: NN_REQ.
should I add specific socket option for nanomsg?
Thanks in advance for helping me on this issue.

**Comment by gdamore** [comment]
I would need more information.  Note that req protocol cannot receive until
you have first sent a message.  Attempts to call receive before then will
return an error.

**Comment by PooyaEimandar** [comment]
> Note that req protocol cannot receive until
> you have first sent a message

Thanks
