### ISSUE TITLE
inproc and pair mode wait for long time

### ISSUE THREAD

**Issue by webbery** [nanomsg/nanomsg#983]
Hi,  
I create a thread using "inproc://recognize" and pair mode to send data. And received thread is a python script which run a deeplearning algorithm cost more than 75% CPU and 8G memory. So if I receive data once, the program will work fine and data transfer well. But if I have not receive data, it will suspend for long time and I don't know how long should I waiting.  
My first code in C++ is:
```
            #include <boost/python.hpp>
            ......
           //following snap code running in a thread, but can not receive data
            python::object test_module = python::import("recognize");
            python::object loop = test_module.attr("loop");
            loop(model, "inproc://recognize");
```
After I change code from inproc to ipc in a thread then is work. So how to explain that?

**Comment by gdamore** [comment]
This should probably be an FAQ.

**Comment by gdamore** [comment]
Closing this -- it's not an open issue.
