### ISSUE TITLE
PUB/SUB Message Format

### ISSUE THREAD

**Issue by gonzalovinas** [nanomsg/nanomsg#994]
Hi there,

I've tried the a PUB/SUB sample and when running the CLIENT, this sends ONE message before receiving the messages from the BROADCASTER...

I would like to know what is the purpose of this message and its format...if possible.

Thanks!

**Comment by gonzalovinas** [comment]
Plus, received message has 9 more data-bytes filled with zeroes... before actual payload... also .. wondering whats the purpose.. 

I couldn't find any doc on this... maybe should I refer to zeromq's spirit?

Thanks in advance

**Comment by gdamore** [comment]
If you’re looking at the binary data, there are details about the setting up the transport, and that message has details such as the fact that the client connecting is a SUB socket.

This is at the transport layer.  See the nanomsg rfcs for details.

 - Garrett
