### ISSUE TITLE
SUB can not reconnect

### ISSUE THREAD

**Issue by GuiRCN** [nanomsg/nanomsg#996]
Yesterday, my publisher app CRASHED. And my subscriber app in another machine remains flagged as ESTABLISHED . I use tcpdump to watch subscriber's local port but got nothing.
Today I restart my publisher  app and bind the same port. There is no new connection.
The subscriber just like do not know publisher  crash or restart.
I searched source code and tcp keepalive can not be found. 
Should I write something like heartbeat in my app?

**Comment by gdamore** [comment]
That sounds unusual. You should use netstat -af inet to look for bound
ports.  If the dialer is nanomsg or nng or mangos then it should auto
redial.  This may take a while for it to discover. You could also use TCP
keepalives to help. And you can tune both the redial/reconnect time and
keepalives with socket options.

 - Garrett

**Comment by GuiRCN** [comment]
Thanks for your answer.
I use tcpdump eth0 my port on the Linux where my subscriber app deployed. When the publisher crashed, 
I receive a series of FIN packets from the publisher machine, but return nothing to it. The tcp connection remains flagged as ESTABLISHED which should be CLOSE_WAIT. It looks like the FIN packets were dropped by TCP/IP stack for some reason. 

Today I set SO_KEEPALIVE in my subscriber app, and the reconnect behavior can correctly perform now.

-- GuiRCN

**Comment by gdamore** [comment]
Well, it seems like the problem was in your stack then, and it sounds like you figured it out.
