### ISSUE TITLE
Windows  IPC  Assertion failed: !self->pipesendbuf

### ISSUE THREAD

**Issue by 363568233** [nanomsg/nanomsg#997]
nanomsg-1.1.4\src\aio\usock_win.inc : 413

I do not know the reason . It hard to reappear.
My send buf is a boost::shared_ptr<char>   construct by jemalloc and deconstuct by jefree

**Comment by gdamore** [comment]
I would need to have more information here.  Can you provide a snippet of your code, how you're sending?

**Comment by 363568233** [comment]
The server has just closed, then this error occurred on the client.   Just  once appeared,

**Comment by 363568233** [comment]
boost::shared_ptr<char> pack((char*)je_malloc(pack_size), je_free);
    if (!pack)
    {
        return error_bad_alloc;
    }

    char error_msg[128];
    if (!encode(pack.get(), pack_size, g_uuid.c_str(), g_group_uuid.c_str(), operation, key, value, value_size, error_msg, sizeof(error_msg)))
    {
        return error_encode;
    }

    //send
    if (-1 == nn_send(sock, pack.get(), pack_size, 0))
    {
        return error_ipc_send;
    }

    //recv
    bool ret = 0;
    if (-1 == nn_recv(sock, &ret, sizeof(ret), 0))
    {
        return error_ipc_recv;
    }

    if (!ret)
    {
        return error_ipc_rep_req;
    }

**Comment by gdamore** [comment]
It looks like the problem is due to failing to clear the pipesendbuf if an error occurs.
